### ISSUE TITLE
Pact Configuration API: Contract.setParameter and Configuration.getString/Double/... inconsistent

### ISSUE THREAD

**Issue by andrehacker** [stratosphere/stratosphere#101]
To pass parameters via configuration I use `Contract.setParameter` in the plan assembler and `Configuration.getDouble/String/...` in `open()`. There is an inconsistency:
Contract offers only 3 implementations of `setParameter`: String, boolean and int.
Configuration, however, additionally offers: getDouble, getFloat, getLong, getBytes.

I think this is a bad user experience for a very common taks and this should be improved.

Additionally, I would propose to add an implementation to send any object with the `Value` type (using base64 encoding). I already have the code but didn't find the time to add a pull request. The existing method `Configuration.getBytes` is already pretty close to this and tells me that someone else had the same requirement.

Another nice-to-have proposal: Add a boolean parameter "isMandatory" to the getParameter method that automatically throws a specific RuntimeException if the parameter is missing.

Actually, what I'd like best as a long term solution is the proposal from Aljoscha https://github.com/dimalabs/ozone/pull/73. It significantly reduces the amount of code needed to pass any parameter to a udf (makes Configuration obsolet).

**Comment by rmetzger** [comment]
I totally agree. Being able to pass arguments via the constructor would greatly improve the user experience!

**Comment by rmetzger** [comment]
Fixed with https://github.com/stratosphere/stratosphere/pull/73.
