### ISSUE TITLE
Mailing List for Ozone-Development

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#114]
Hello,

I created a Google Groups-based mailing list for all ozone developers.

You can find the Group here: https://groups.google.com/forum/#!forum/stratosphere-dev
The address of the mailing list is: stratosphere-dev@googlegroups.com

This is not any kind of official mailing list or so. I did not ask anybody for "permission" to create it. I just have the feeling that we need a tool to discuss things which are not an actual issue or question.
I know that there is already an official list for stratosphere. (But its not really used, its TU hosted and not publicly available (or the archives are not working))

If we want to be an _open_ open-source project, every discussion should be publicly available.

**Comment by ktzoumas** [comment]
Great! We agree :-) Change the welcome message to something more welcoming to newcomers, put a link at the ozone README, and let us use this from now on
