### ISSUE TITLE
Add scala-frontend to stratosphere

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#118]
@aljoscha is about to finish the Scala frontend-implementation.

I'd like to discuss here if we are going to add the frontend into the main ozone-codebase or if we are going to let it stay in the ozone-scala repository.

It is not possible to (git) merge the two repositories, so if we add scala to the main code, we have to copy the files into the repo.

I vote for adding scala into the main repository. This is a major feature of our system. Having the code here would also include it into the testing system (travis).
It is easier for users to check out only one repository.

**Comment by aalexandrov** [comment]
The current version depends on an old Scala compiler version and from my experience has a painful to almost impossible setup process depending on your environment (Eclipse version, etc.). I think Andre has a similar experience. 

As long as these problems are solved with the next version, I would prefer it to be in the same repository. 

On the other hand, we also have to think about users who will want to have Stratosphere with Meteor. A clear modularization dictates that  the base project should have only the common base components, and alternative upper layers should be available on top. 

This does not mean that we have to maintain a separate repository for each language stack, the problem could be solved differently (e.g. a mvn profile for each language?). Overall the main requirements from my perspective are:
- keep components and orthogonal features (scala vs meteor) clearly separated and visible
- don't overpopulate the account with maven projects
- integrate full stack (including the language layer) into Travis

Does anybody have a strategy that provides a good answer for all?

**Comment by aljoscha** [comment]
It would be nice to have it compile the various frontends conditionally. So they would not be in the ozone repository but in their own repo and then when you check them out into the ozone root folder (possibly using git submodules) the maven build picks that up and stratosphere-dist puts everything in the created distribution.

Anyone knows whether that's possible?

**Comment by fhueske** [comment]
My opinion is to keep it simple. Maven profiles, git submodules, come on... People don't want to read a 40 page manual to learn how to build the system.
Wasn't one of the main goals to simplify things and lower the setup effort?

**Comment by ktzoumas** [comment]
I assume that scala is stable. If so, I am in favor of adding it to ozone,
as this is a major feature of the November release. We could have an option
in maven to build the system with or without scala and/or meteor
