### ISSUE TITLE
Accumulators

### ISSUE THREAD

**Issue by andrehacker** [stratosphere/stratosphere#119]
There is currently no support for global counters and histograms in ozone. To workaround this lack of expressiveness a user currently has to output the things he wants to track in pact records and merge later, which is pretty complex.

Hadoop + Spark have it (they call it accumulators and even mention it in their overview as a main concept, see [here](http://spark.incubator.apache.org/docs/latest/scala-programming-guide.html)) (search for Shared Variables/Accumulators)

Having explicit support to populate **distributed histograms** would be even nicer, here to obtain the distribution of number of non-zero features for a sparse dataset: `histNumFeatures.addSingle(myVector.numNonZeros())` which is equivalent to `histNumFeatures.add(myVector.nonZeros(), 1)`.

The global counters (and histograms) should **only be accessible after the job ended**. Similar to the counters in Hadoop. This way the implementation should be feasible: We can collect the counters (and histograms) on each Tasktracker in memory and when the last UDF ended we can send the result accumulated to the Jobtracker or to the client (didn't think about this part yet).

**Use cases**
- Use cases like the one above (there are plenty)
- Automatically use counters to show most important properties after execution of the  job (similar to hadoops default counters)
- Debugging
- Profiling: E.g. show how well load was distributed in partitioning. (I see that https://github.com/dimalabs/ozone/issues/8 talks about a distributed histogram too)

**Comment by aljoscha** [comment]
I thought about this and I see some difficulties when it comes to complex data flows where multiple UDFs could run concurrently. Hadoop and Spark have a very linear flow of execution. Even in spark where there are more complex concepts such as joins and iterations you know which UDFs run after which other UDFS. In stratosphere we do not have that luxury, unless I'm wrong, of course.

**Comment by andrehacker** [comment]
I talked to aljoscha afterwards and we saw there was a misunderstanding.
The global counters (and histograms) should only be accessible after the job ended. Similar to the counters in Hadoop.
So I did not mean a global variable where one can write to in one udf and read from in another.
I will update the issue to clarify.

**Comment by andrehacker** [comment]
I am currently looking into ZooKeeper to see if it is an option to implement counters. So let me know if there is anything you ever wanted to know about Zookeeper;)
Stephan had the idea to use ZooKeeper and asked me to look into it since it might be interesting for other features too (iterations).

My first impressions:
Very flexible, relatively simple, good performance, low overhead, nice APIs (e.g. Netflix Curator), but not trivial to integrate. HBase and Giraph both [ship and automatically manage](http://hbase.apache.org/book/zookeeper.html) ZooKeeper by default, so there is a lot of code that could be copied. One can either start ZooKeeper in a separate JVM or run it in the same JVM, e.g. in JobManager. Giraph does the first, HBase [supports both.](http://hbase.apache.org/book/standalone_dist.html)

If you wonder what ZooKeeper is: Think of it as a fault-tolerant replicated in-memory low-latency database for small data (typically configuration or coordination data). Data are stored exactly as in a hierarchical file system, except that directories can also have data. The data-nodes of the hierarchy store their data as byte[] (< 1MB recommended).
All TaskManagers could access the database, making it easy to coordinate (there are many highlevel constructs like barriers, leader election, etc.) or to transfer small data like counters. Even shared variables could be easily implemented (write in one udf, read in other). To conclude: very powerful, since it is basically a central database.

This is meant as an intermediate update.

**Comment by rmetzger** [comment]
Thanks for the update. I'm really happy that someone is taking care of this.

When using Zookeeper, we must ensure that users do not have to care about it (unless they explicitly want, for example if they have a shared zookeeper for their whole hadoop cluster (e.g. when using a Hadoop distribution)).

I'm not a Zookeeper expert, I though is used for distributed configuration. I don't know how many concurrent accesses zookeeper can handle (imagine a large job with many short-running operators).

Wouldn't it be easier to just use a HashMap or so for each Operator on each TaskManager and collect them using the JobManager once the job has finished?
(You could also do more periodic updates (similar to hadoop counters) using the heartbeat machanism of Stratosphere. (See `ClusterManager.reportHeartBeat()` ) (there is already a SerializableHashMap, so you don't have to care about network transport) The counters could also be shown in our new web front end.)
I guess we would also need a reduce/combine-style function to tell the framework how to combine the results of each TM.

(Sorry for the overuse of parentheses)

**Comment by uce** [comment]
(Thanks @andrehacker and no problem @rmetzger.)

**Comment by ankurcha** [comment]
This is just an opinion:

Having had my share of using and running zookeeper in production for a couple of projects. I will have to say, it's not the easiest beast to tame, especially with network latency and failover is concerned. 
It would be nice to have global counters but we need to be aware that zookeeper adds some significant operational complexity. 

I have in the past had to put a whole lot of "exception" catching code to deal with edge cases. 

I would like the core engineers to consider simpler alternatives before going for zookeeper, maybe have a pros and cons document with alternatives before committing to any new technology.

**Comment by andrehacker** [comment]
Thanks @rmetzger and @ankurcha for feedback and sharing your experiences! I agree with basically everything you wrote, see my comments below.

The idea is to collect the counters in the RuntimeUDFContext for every task and send them to the JobManager (JM) at the end of each task using Nephele or ZK (I did not mean to send every single counter-increment with ZK). Sending once at the end of the job is a harder problem, because the TM doesn't know which is the last task. Then the counters are returned to the calling client. We can still decide to store them in the JobManager for display purposes.

Initially we discussed to go through Nephele, but this has some disadvantages (Nephele is PACT-agnostic and sometimes not so easy to go through all Nephele layers) and we decided to look at ZK, since it might be interesting for other stuff like iterations and fault tolerance. Using ZK for Counters alone would be overkill.

My current impression is (similar to ankurcha) that the integration of ZK is a too big project to do it in december. So I now focus less on ZK and more on counters and how to do it with Nephele.

To @rmetzger comments:
- Yes, the addition of ZK must be completely transparent to the user: Per default ship&manage ZK automatically (e.g. in JobManager JVM), and optionally let the user specify a connect-string to an existing ZK.
- ZK is not only for dist. configuration, but also for arbitrary coordination (the paper is called Wait-free coordination for Internet-scale systems).
- ZK is designed to be fast: Adding more ZK-nodes lets it scale to tens-of-thousands request per seconds according to paper. But there is a read/write tradeoff: Adding more ZK-nodes makes reads faster but writes slower.

To @ankurcha feedback
- Did you directly use the ZooKeeper API or any wrapper? Curator has 2 levels on top of the basic ZooKeeper API and they say this removes most of the retry- and exception handling.
- Can you give a hint what use cases you used it for?

I'll write more regarding the counters later...

**Comment by rmetzger** [comment]
Hi Andre,

> Nephele is PACT-agnostic and sometimes not so easy to go through all Nephele layers

We want to change this anyways. So change it (it can also "know" pact-details) so that it fits your needs.. (The upcoming renaming also reflects our intentions).

**Comment by andrehacker** [comment]
Thanks @rmetzger , that's good to know!

**Comment by StephanEwen** [comment]
We continued the discussion and have a tendency to not including zookeeper. We do not need the biggest parts of zookeeper's functionality and have most mechanisms already in place to implement lightweight aggregates on top of. It seems adding the missing parts to our own system is less work than taming the zookeeper.

**Comment by andrehacker** [comment]
@rmetzger, your questions from #340 are still open:

> Do you think it would be a cool addition to have a way to explicitly disable the accumulators?

Yes, there are two options: system-wide or per-job. Not sure if we need system-wide: The overhead is very low if accumulators are not used (there is no additional network traffic except one RPC call from client after the job ended, which is done directly, without having to wait for polling intervals). A reason for system-wide would be if we consider the feature to be not stable enough.
But job-wide makes more sense IMHO: If you use accumulators, e.g. for debugging or to find out more about your data, you might want to activate and deactivate them on demand without commenting-in or -out.
Not sure if it is a good idea to add this to 0.4 - I think we better have a feature freeze and make 0.4 as stable as possible.

> ... Standard accumulators

Yes, I proposed this too in this issue. I like the ideas you proposed to activate this. Below is a list of the default counters for inspiration. I guess this is for release 0.5...

> I don't know if it is a good idea that you can call getAccumulator() on non-existing accumulators.
> I just had the case that I copy pasted my accumulators from some mappers to a match (for counting incoming and outgoing tuples) and I accidentally forgot to change the name. Having a "createAccumulator" method could throw a exception "accu already exists"

I guess you are talking about the `private <V, A> Accumulator<V, A> getAccumulator(String name,
            Class<? extends Accumulator<V, A>> accumulatorClass)` which is called internally by the convenience functions? Then I agree. I also prefer the more explicit versions addAccumulator(name) and getAccumulator(name). But isn't the `addAccumulator` method what you mean by `createAccumulator`? We could rename the convenience functions to e.g. `createLongCounter` and let them throw an exception if it already exists (we should then also rename `addAccumulator` to  `createAccumulator`). Have to leave now and will think about this again tomorrow...

#### Hadoop default counters

```
File System Counters
    FILE: Number of bytes read=2832086166
    FILE: Number of bytes written=4364548708
    FILE: Number of read operations=0
    FILE: Number of large read operations=0
    FILE: Number of write operations=0
    HDFS: Number of bytes read=641297954
    HDFS: Number of bytes written=870300
    HDFS: Number of read operations=42
    HDFS: Number of large read operations=0
    HDFS: Number of write operations=8
Job Counters
    Launched map tasks=5
    Launched reduce tasks=4
    Data-local map tasks=5
    Total time spent by all maps in occupied slots (ms)=1,472,619
    Total time spent by all reduces in occupied slots (ms)=961,785
Map-Reduce Framework
    Map input records=781265
    Map output records=59157312
    Map output bytes=1419775488
    Map output materialized bytes=1538090232
    Input split bytes=700
    Combine input records=0
    Combine output records=0
    Reduce input groups=43068
    Reduce shuffle bytes=1538090232
    Reduce input records=59157312
    Reduce output records=43068
    Spilled Records=167838785
    Shuffled Maps =20
    Failed Shuffles=0
    Merged Map outputs=20
    GC time elapsed (ms)=3123
    CPU time spent (ms)=749,110
    Physical memory (bytes) snapshot=6735572992
    Virtual memory (bytes) snapshot=27861659648
    Total committed heap usage (bytes)=8372879360
Shuffle Errors
    BAD_ID=0
    CONNECTION=0
    IO_ERROR=0
    WRONG_LENGTH=0
    WRONG_MAP=0
    WRONG_REDUCE=0
File Input Format Counters
    Bytes Read=641296299
File Output Format Counters
    Bytes Written=870300
```

**Comment by andrehacker** [comment]
Regarding accumulator API:
We could completely remove the convenience functions like `getIntCounter`. Then we have the following interface in the UDF:

```
public <V, A> void addAccumulator(String name, Accumulator<V, A> accumulator)
public <V, A> Accumulator<V, A> getAccumulator(String name)  // throws ex if not existing
public HashMap<String, Accumulator<?, ?>> getAllAccumulators()
```

 We could also rename `addAccumulator` it to `registerAccumulator`.

I will talk about this with Stephan, but open for comments.

**Comment by rmetzger** [comment]
I really like the convenience functions!

Regarding your previous comment: Job-wise disabling makes more sense to me.

> We could rename the convenience functions to e.g. createLongCounter and let them throw an exception if it already exists (we should then also rename addAccumulator to createAccumulator)

Exactly. I just ran into the problem that I used a Mapper multiple times in my plan and I was wondering why the counters where unexpectedly high.
