### ISSUE TITLE
New Front-Page for stratosphere.eu

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#120]
Just to let everybody know, I started to rework the stratosphere.eu website together with @uce.

This is a very early preview, with placeholder texts: http://rmetzger.github.io/ozone/

**Comment by aalexandrov** [comment]
Looks great, I'll help you with that tomorrow.

**Comment by rmetzger** [comment]
I'll be late tomorrow or probably won't even come. But Ufuk is there.

On 30.09.2013, at 23:45, Alexander Alexandrov notifications@github.com
wrote:

Looks great, I'll help you with that tomorrow.

—
Reply to this email directly or view it on
GitHubhttps://github.com/dimalabs/ozone/issues/120#issuecomment-25409145
.

**Comment by rmetzger** [comment]
Hey guys,

@uce and me are a bit unhappy with the current Stratosphere logo. What do you think about these two ? See it as a source of inspiration. Its just a draft (I did not create them)

What do you thing about the Idea of changing the logo? 

![1376666_642095089157579_406820309_n](https://f.cloud.github.com/assets/89049/1246248/665447d4-2aab-11e3-8cd2-bf20988302ab.jpg)
![1374658_642095082490913_528670652_n](https://f.cloud.github.com/assets/89049/1246250/68f44d54-2aab-11e3-9887-d275c9814c62.jpg)

**Comment by ktzoumas** [comment]
Does the current logo even appear in your website design?

**Comment by rmetzger** [comment]
No it does not appear (I don't know the most recent changes from @uce). But I think we want to add the logo to the site.

This is the current logo:
![currlogo](https://f.cloud.github.com/assets/89049/1246392/0e4e9f24-2aad-11e3-8f46-4b726ac3f786.png)

**Comment by uce** [comment]
No, it doesn't. But mainly because we didn't like it. For example it says Strato**S**phere (at least the version we got from Fabian), which is inconsistent with how we write it.

Of the two proposals, I think I like the second one more (but I am unsure if we need/want a cloud in it ;)).

**Comment by aljoscha** [comment]
I think both of the new drafts are better than the old one.

**Comment by rmetzger** [comment]
@uce: I don't know if we want the term "cloud" in our logo. The cloud hype is over, and our logo should not change too often ;) 

Please write if you have any other ideas for logos! We could also improve the current logo .. something that has to do with the stratosphere.

**Comment by ktzoumas** [comment]
Agreed about the "above the clouds", we also removed the cloud references
recently in some posters. If we don't need a logo for the website right
now, let us not use one. But let us not discuss this in this mailing list,
I would rather hire a designer to do that if we decide to change it.

**Comment by fhueske** [comment]
Actually, the old logo is related to the stratosphere. The blue circle resembles the earth and the gray ring the stratosphere...
Please be also aware that changing the logo is not only a question of style or taste.

**Comment by rmetzger** [comment]
I think one thing is missing from the current website draft (http://rmetzger.github.io/ozone/). There is no description of what Stratosphere does on the front page! It only tells features. But if someone does not know anything about our system, it is hard to find out, what it is about.

I think we should have two sentences explaining our system.
"Stratosphere is a distributed data processing system for Big Data. Its novel, extensible operator model natively supports complex data analytics tasks."

**Comment by rmetzger** [comment]
I'm not happy with the white bar on the front-page.
