### ISSUE TITLE
Remove generated comments

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#122]
I suggest to remove all Eclipse-generated comments from the source like

```
/* (non-Javadoc)
         * @see eu.stratosphere...
*/

/**
     * {@inheritDoc}
     */
```

Such comments offer zero value to a reader.

**Comment by aljoscha** [comment]
I agree, we just need the resident regex wizard to come up with the all-powerful regex to remove all that stuff.

**Comment by rmetzger** [comment]
+1

I think that we also wanted to remove all `@author` tags.
We should probably do this with as few pull requests as possible (@uce has a large pull request pending).

**Comment by aljoscha** [comment]
We should first merge in the big stuff because after changing basically every file a merge (or rebase) can get quite nasty.
