### ISSUE TITLE
Strange (and faulty) Iterations Behaviour #2

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#124]
I have a new example job to calculate a transitive closure (both java and scala frontend) where I have a union of the iteration input after using the input earlier. The udf with the union will just stall and nothing will happen. It does not happen when I unroll the iteration and it does also not happen when I emulate the reducer that has the union using a CoGroup.

Source Code: https://github.com/aljoscha/ozone/blob/9ae7afff9308996b16de67f8003822e1813d5059/pact/pact-examples/src/main/java/eu/stratosphere/pact/example/shortestpaths/TransitiveClosure.java

Stacktrace: https://gist.github.com/aljoscha/113353aa6ff89108eb2b

**Comment by aljoscha** [comment]
@sscdotopen I don't have a stacktrace, the job will just stall and there will be no more output. I'm using the LocalExecutor, by the way.

**Comment by sscdotopen** [comment]
You can take one with jstack or your IDE

**Comment by aljoscha** [comment]
Ok, I'll do that when I'm at DIMA tomorrow where I have the code.

**Comment by aljoscha** [comment]
I've added the stacktrace. It seems that all the tasks are waiting for something.

**Comment by rmetzger** [comment]
This reminds my of an issue that I have with the telecom use-cases https://github.com/dimalabs/ozone/issues/109
It also involves the sorter.

**Comment by aljoscha** [comment]
But you didn't solve that one yet, right?

**Comment by rmetzger** [comment]
No, I have a workaround that is not applicable to you.

(I have two `FileDataSource` for the same file, so that each contract that
needs the data can read it from its own source). The workaround is based on
various experiments. I did not understand the problem. I'm also unable to
create a smaller sample job that repeats the error

On Fri, Oct 4, 2013 at 1:35 PM, Aljoscha Krettek
notifications@github.comwrote:

> But you didn't solve that one yet, right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dimalabs/ozone/issues/124#issuecomment-25692617
> .

## 

Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Comment by aljoscha** [comment]
@StephanEwen I have added a failing test case for this in https://github.com/aljoscha/ozone/tree/iteration-with-union-bug

**Comment by StephanEwen** [comment]
This turned out to be a more general problem in the nephele channels and readers. Union readers and events don't seem to work together in general, it is actually not iteration specific.

**Comment by StephanEwen** [comment]
It seems like the logic in the UnionReader is fundamentally broken. I assume that this streches to more cases then we have discovered, yet.

With #25 this would get fixed as well. It would be good to have a fix for this fast, though. #25 is not prioritized right now.

**Comment by uce** [comment]
@StephanEwen Will you look into this? Or should I try my luck? I was planning to start today with looking into the iterations stuff.

Alternatively I would sync with @vasia and pick something else.

**Comment by StephanEwen** [comment]
I will try to concoct a quick fix. Extending the iterations is more pressing right now, I suggest you go ahead with that.

**Comment by StephanEwen** [comment]
Fixed in 1228a5ec60452200e12cb77a9bb0623d340e87d2
