### ISSUE TITLE
Versions, Artifact IDs, Maven Central

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#125]
Hello,

I recently merged this https://github.com/dimalabs/ozone/pull/64 pull request  by @Aheise into the main code line.
It automatically uploads successful builds to the Sonatype OSS Snapshot repository (https://oss.sonatype.org/content/repositories/snapshots/eu/stratosphere/ozone/).
I therefore changed the version of Stratosphere to `0.4-ozone-SNAPSHOT`.

You can now add us as a dependency by adding the snapshot repository to your pom:

``` xml
 <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
</repositories>
```

And us as a dependency:

``` xml
<dependency>
    <groupId>eu.stratosphere</groupId>
    <artifactId>ozone</artifactId>
    <version>0.4-ozone-SNAPSHOT</version>
</dependency>
```

(there is one little issue: it is not really working this way ;) But I'm on it (Help is appreciated ;). You have to add pact-clients and pact-common as a dependency. )

We always push two versions to Sonatype: `0.4-ozone-SNAPSHOT` (which is hadoop v1) and  `0.4-ozone-hadoop2-SNAPSHOT` (hadoop v2, with yarn support).

I'm also going to release a `0.2-ozone` version to maven central! You then won't have to add the snapshot repository manually.

I have the following questions for you. I'd like to know what you think, how other projects are doing this and so on.

1) I'm not happy with the version names. They are too long. The "-SNAPSHOT" is currently hardcoded into our poms. I could change the versions back to 0.2-ozone and let a script change the version before deploying them to Sonatype. 

2) @aalexandrov changed the artifact ID in the main pom to `ozone`. This is how our main pom currently looks like:

``` xml
<groupId>eu.stratosphere</groupId>
<artifactId>ozone</artifactId>
<version>0.4-ozone-SNAPSHOT</version>
```

This means that our project is called `ozone`, which is not the case. I suggest to change the name back to `stratosphere`.
As @ktzoumas suggested, we can use other atmosphere gases such as Nitrogen, Oxygen, Neon, Helium, Krypton, Xenon, Iodine. We could append these to the version numbers. Like `0.6-neon`, `0.10-helium` etc.

**Comment by aljoscha** [comment]
What is your problem with having to include pact-clients and pact-common instead of "ozone"?

**Comment by rmetzger** [comment]
Nothing.
I somehow thought that it should work by including just the `ozone` artifact. Based on my experience with open source projects, you usually only have to include one artifact to use the project.
It is also dissatisfying for me not to understand, why it is not working!

**Comment by aljoscha** [comment]
I think the difference might be that other projects only have one pom to begin with. For us the "ozone" pom is just the parent pom of the project, it does not contain any code artifacts. I think it is more correct to have to include the exact pom that you want. If it where not like that you would always get the whole shebang (scala, meteor, nephele stuff, tests) even if all you want to do is develop a simple java pact job.

**Comment by aljoscha** [comment]
In spark you add spark-core as a dependency, this is not the top-level pom of spark.
