### ISSUE TITLE
Create Sample/Quickstart Stratosphere Project

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#127]
This is an idea from @asteriosk (I could not find any issues or comments describing this, so I created one.)

He suggested to add a project skeleton for Stratosphere Jobs. It should contain 
- an maven pom with all the required dependencies
- a main() method with the LocalExecutor
- Some documentation on where to put the code, how to run locally and distributed

Should we add this sample code into the main repository or into a separate project?
Would it make sense to create a maven archetype for that (are these suited for this usecase? )

**Comment by fhueske** [comment]
Isn't that exactly what a Maven Archetype should provide?

**Comment by fhueske** [comment]
We could have separate Archetypes for the Java and the Scala programming interfaces.

**Comment by rmetzger** [comment]
Based on the experience I had yesterday with the Big Data Beers Meetup in Berlin, I'd say we need to go for the most convenient and simplest solution.
We need to have something fast instead of the perfect approach in 2 months.
I think it is possible to hack together a very simple "SDK" in less than 1 hour. I think I'll do that today..

Is it possible to create a project with maven archetypes with one command? Thats what we need?

Something like: "mvn create -u http://stratosphere.eu/awesome".
We could also do the `curl` hipster thing like:
`curl http://stratosphere.eu/sdk.sh | bash`.

**Comment by fhueske** [comment]
A Maven archetype generates a POM file(incl. all dependencies) and some code templates (AFAIR).
When starting a new Maven project in Eclipse you can select an archetype which will do that automatically.
I'm sure other IDEs offer similar functionality.

That's the way to go instead of some custom shell scripts, IMHO.

[Apache Maven documentation for archetypes](http://maven.apache.org/guides/introduction/introduction-to-archetypes.html)

**Comment by StephanEwen** [comment]
Archetypes are good. But nothing contradicts having an additional shell script that calls maven to create a project based on an archetype. If the hipsters like that ;-)

**Comment by rmetzger** [comment]
https://github.com/rmetzger/stratosphere-sdk

**Comment by rmetzger** [comment]
Okay.
The quickstart archetype is on Sonatype.

Try it out:

```
curl https://raw.github.com/rmetzger/stratosphere-quickstart/master/quickstart.sh | bash
```

The sonatype server is a bit slow and I had a NullPointerException in Maven ;) ;)

**Comment by StephanEwen** [comment]
Nice, looks good to me.

Btw: I have seen that people start using 

```
#! /urs/bin/env bash
```

instead of

```
#! /bin/bash
```

Is that really an advantage? I have seen problems with path translation on our cluster that happens when going through env, but which work when going to bash directly.

**Comment by rmetzger** [comment]
For Linux, it does actually not really matter. But other Unixes like BSD or solaris has some strange path's for the bash, so this seems to be the way to go.

**Comment by rmetzger** [comment]
You should also take a look into this issue https://github.com/dcramer/mangodb/issues/23 (also read the comments)

**Comment by rmetzger** [comment]
Okay. I moved the repository into @stratosphere. The archetypes are now automatically pushed to sonatype using travis.

I'm going to update the website's QuickStart soon with the archetype.

@aljoscha needs to create a Scala Quickstart.
@AHeise could, if he wants, also add a meteor quickstart.

I'll close the issue, once @aljoscha is done.
