### ISSUE TITLE
Change dimalabs to "stratosphere", rename "ozone" to "stratosphere".

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#133]
Hi,

I was able to get the @stratosphere GitHub account!
In a meeting earlier today, we discussed to move ozone to "stratosphere-eu". But I think @stratosphere is just the best account name that is possible!

What I like to do is the following:
- Delete the @stratosphere account
- Rename @dimalabs to @stratosphere
- Rename the repository from "ozone" to "stratosphere".
  Depending on what happens to our website:
- (Create a @dimalabs account) (create a ozone repo and push "gh-pages").(github says that it automatically creates redirects from the old name to the new one until somebody else takes the account)
- Set up the stratosphere.eu domain correctly for the new "stratosphere" account.
- Update links on website to new account
- Set up travis for @stratosphere (generate new keys for sonatype deployment)
- grep code and wiki for "dimalabs" references. (for example the maven poms contain references to dimalabs)
- delete the @stratosphere-eu github account.

Every local clone (with all remotes) needs to change the repository URL "dimalabs/ozone" to "stratosphere/stratosphere".

:warning: **Did I forget anything?**
I think I'll do the migration tomorrow. So everybody has 24 hours to intervene.

This migration will probably cause some troubles, but we will end up with a very nice project structure.

**Comment by aljoscha** [comment]
Did anyone check whether renaming would work if the other account was just deleted. We should test that with some  new accounts.

**Comment by sscdotopen** [comment]
Please don't do it this week. The code for the AIM3 course is also
living inside the @dimalabs account, if you change stuff, this might
cause havoc to my students here. The course is over next week, so than
the migration should be fine.

Thx,
Sebastian

**Comment by rmetzger** [comment]
Okay, seems like the @stratosphere references are not working. This is the url of the current account: https://github.com/organizations/stratosphere (but it is only there for blocking the username). 
I think I will not turn the account into an organization, because the URL is not nice!

**Comment by rmetzger** [comment]
@sscdotopen Okay, sure.

**Comment by ktzoumas** [comment]
What about transfering the ozone repository? It seems to be the "correct" github way: https://help.github.com/articles/how-to-transfer-a-repository

What would be the problem with that?

**Comment by ktzoumas** [comment]
Could you also ask the GitHub help team what would be the best way to do this?

**Comment by aljoscha** [comment]
If a repo transfer would also transfer issues and all the discussion (which I feel it will) then this would be the way to go I think.

**Comment by ktzoumas** [comment]
Yes, let us ask the GitHub help team to make sure it does

**Comment by rmetzger** [comment]
I asked them.

**Comment by rmetzger** [comment]
Okay, I got the answer:

> You should just be able to transfer your repository to the stratosphere organization.
> When you transfer a repository, its issues, pull requests, wiki, stars, and followers are also transferred. Forks continue to point to the root repository.

So everything seems to be fine with moving "ozone" to the stratosphere organization. 
@sscdotopen would even be unaffected by this. (But I will still wait because your students probably also access the ozone repo).

But I suggest (if @aljoscha agrees) to move the ozone-scala repository to stratosphere. This could be a perfect testbed. (Should we also rename it to stratosphere-scala?)

**Comment by aljoscha** [comment]
Yes, you can move (and rename) it.

**Comment by rmetzger** [comment]
Done

**Comment by rmetzger** [comment]
I'm going to do the move in the next few hours.

**Comment by rmetzger** [comment]
Move and rename done.
The website is still up.

now, everybody should update the urls of the remotes.

**Comment by rmetzger** [comment]
Okay. I changed all links on the website.
Travis seems to work with the new name.

The only thing we noticed is that some issues are not assigned anymore.

**Comment by rmetzger** [comment]
Meteor and stratosphere-testing has been moved, too.
