### ISSUE TITLE
Replacing Nephele's IOReadableWritable with Hadoop's Writable interface

### ISSUE THREAD

**Issue by temptest1** [stratosphere/stratosphere#134]
I was wondering if we should remove our `IOReadableWritable` interface and use Hadoop's `Writable` instead. Despite a small difference in the name of the read method, they are identical:

```
public interface IOReadableWritable {
    void write(DataOutput out) throws IOException;
    void read(DataInput in) throws IOException;
}
```

```
public interface Writable {
    void write(DataOutput out) throws IOException;
    void readFields(DataInput in) throws IOException;
}
```

This would allow Hadoop users to directly work with their `Writable` implementations in Stratosphere (for example Mahout's `VectorWritable`).

Does anybody see problems with this?

**Comment by uce** [comment]
OK, sorry. This was me with my still logged in temporary account (because auf #133). :baby:

**Comment by sscdotopen** [comment]
BIG +1 on that. Would be a great step towards integration with the rest of the world.

**Comment by StephanEwen** [comment]
I am also in favor. Are there any other implications? I can think of:
1. Delete the nephele Record type and the Pact Value type, both will be replaced by the Hadoop type.
2. Adjust all Examples...
3. The richer value types which allow the runtime to do some extra stuff must inherit from the Hadoop type.

What about our key type? Should it inherit from WritableComparable?

**Comment by rmetzger** [comment]
We should also make our `FSDataInputStream` compatible to Hadoop's `FSDataInputStream`.

**Comment by StephanEwen** [comment]
The new java api will accept hadoop writables. This issue is therefore subsumed by #537
