### ISSUE TITLE
MatchTaskTest sometimes fails with ConcurrentModificationException

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#139]
According to https://github.com/dimalabs/ozone/issues/94 there are at least 3 cases on Travis-CI where the MatchTaskTest failed.

Someone needs to investigate this issue.

**Comment by StephanEwen** [comment]
Refer to #94 for detailed comments.

**Comment by StephanEwen** [comment]
Fixed in 7b0c53b4c501690866523468f6c3e7f06438658c
