### ISSUE TITLE
Migration of wiki documentation

### ISSUE THREAD

**Issue by asteriosk** [stratosphere/stratosphere#140]
Hi,

today I made a couple of scripts and migrated the old dokuwiki to the github wiki:
https://github.com/dimalabs/ozone/wiki

Some issues remain however. We have to:
- find broken links to code that are broken because of the refactoring of Ozone
- resize images when needed 

Thus, I would like to ask you to do a pass over the documentation in order to find possible problems and fix them. You can declare here (with a comment) which part of the documentation you would be taking over. 

We will close this issue when this is done. 

cheers,
Asterios

**Comment by asteriosk** [comment]
I am taking over the following pages and their "subtree":
-   **[Setup &  Configuration](#"wiki:")**
  -   [Cluster
    Setup](#"wiki:clustersetup")
  -   [Cloud
    Setup](#"wiki:cloudsetup")
  -   [Instances and Parallel
    Scheduling](#"wiki:instancesandscheduling")
  -   [Configuration
    Reference](#"wiki:configreference")
  -   [Using Nephele with Channel
    Compression](#"wiki:nephelecompression")

**Comment by rmetzger** [comment]
We decided to create a comprehensive introduction/tutorial on the website. 
Scala is the primary languages for the examples.
Assigned to @asteriosk (and @uce)

We are going to have a new Java programming interface that is similar to Scala's.

**Comment by fhueske** [comment]
I will do a first pass over the Java API section once the renaming #257 is done.

**Comment by fhueske** [comment]
I ported and reworked the programming model section of the documentation: #334
