### ISSUE TITLE
Simple Webinterface for Jobmanager

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#143]
assigned to Markus Holzemer
Simple jetty server running inside the Jobmanager.

("nice to have" - for release)

**Comment by rmetzger** [comment]
Hello guys,

Markus started to work on this task today.
We need to specify how we would like to have the webinterface.
I suggest that we orient us on the JobTracker interface of Hadoop. 
So a list of waiting, running and completed jobs.
An interface to view logfiles.
A very basic progress overview.

**Comment by StephanEwen** [comment]
There is no notion of waiting jobs right now, so I guess we should go with the running ones (most likely only one most of the time) and then the completed ones.

I think that hadoop is using a dedicated server for job histories, because in YARN, the jobmanager lives only for a single job typically.

**Comment by andrehacker** [comment]
Regarding the logfiles I think it is very important to be able to view the logs for a specific job only.
Logs include the things written to log (from the system or UDF) and std-out (from UDF).

I can confirm what stephan writes about yarn, there is a separate job history daemon. They even added a log aggregation feature called "yarn.log-aggregation-enable" to copy all aggregated logs for a job to hdfs, since log analysis is such a common task.
Although yarn has a different architecture, they do offer such log-per-job web interface and it is a good orientation.

**Comment by fhueske** [comment]
I see two main use cases for the web interface:
1) Progress monitoring of running job
- Show status of currently running tasks
- How many subtasks of each task are in which status (scheduled, started, running, finishing, finished, ...)
- Dependencies of tasks (Which tasks is input of which task (should be displayed as a graph in the end, but right not some text format might be sufficient)

2) Performance debugging (of finished jobs)
- Provide log files
- Provide timestamps / timeline visualization of subtasks (when did which subtask finish, which tasks a stragglers, on which node did tasks run, etc.)
- this requires to save all information, either in a tmp file or some database like Derby or SQLite
- can be later extended to work on currently running job

In my opinion, progress monitoring is easier implement and more important right now. Performance debugging can be added later but should be considered when designing the infrastructure of the web interface.

Btw. AFAIK Nephele is actually queuing jobs and gives out at least the job name and job ID of waiting jobs. But I am not sure which additional information is available (e.g., JobGraph or ExecutionGraph)

**Comment by markus-h** [comment]
This issue can be closed I think.

**Comment by fhueske** [comment]
Agreed.
