### ISSUE TITLE
Make Stub and Input/Output Formats Serializable

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#147]
Currently, all stubs need to manually declare serializability, to be able to be shipped as code. This causes non-runnable stubs, if they forget this declaration (easy trap) and ugly user code.

We should either
- declare serializability in the Stub, so it does not need to be added to all implementations. It still required to either ignore the serializability warning, or declare a serial version uid. - OR -
- use a different serializer than the java default serializer, fir example kryo. I am not sure how that interplays with the scala frontend, since scala serializes closures through java's default serialization.

We may be able to use both, meaning we use java serializability if a stub declared the java.io.Serializable interface, and use kryo otherwise. That would lead to the best support for user code.

**Comment by aljoscha** [comment]
At the beginning I declared serializability in the stub. I decided against this though because serializability does not just mean implementing Serializable, you also have to make sure that your class is actually serializable. It has to be a deliberate choice by the user.

**Comment by rmetzger** [comment]
I don't know if you know that @aljoscha's implementation is able to handle both, classes and objects as stubs.

I think Hadoop users are used to define classes in their stubs and configure them using the Configuration. If (advanced) Stratosphere users want to pass objects, they have to take care of serializability.

**Comment by uce** [comment]
I would be curious to see how much we would gain by using Kryo instead of Java serialization (see https://github.com/eishay/jvm-serializers/wiki for some numbers).

Scala classes need some extra setup though (https://code.google.com/p/kryo/#Scala).

Spark for example uses Java serialization for closures (see `spark.closure.serializer` at http://spark.incubator.apache.org/docs/latest/configuration.html) and recommends Kryo for general object serialization (see `spark.serializer`) although Java serialization is the default (because users have to manually register their classes with Kryo).

**Comment by aljoscha** [comment]
But we only use java serialization in non-performance-critical stuff, right? So I wouldn't worry about this to much.

**Comment by uce** [comment]
Yeah, sure. I think I wanted to say that we might also think about the performance-critical stuff in the long term.

**Comment by aljoscha** [comment]
So, will we close this issue?

**Comment by uce** [comment]
Yes, I think so.

A different issue would be to think about using classes instead of objects in the examples if we think that @StephanEwen points (easy trap + ugly code) are valid.

**Comment by StephanEwen** [comment]
Yes, I think it is resolved as follows:

Serialization is implemented at the level where the writer of the class can guarantee serializabililty. For udfs, that is the writer of the udf. For library input and output formats, it is the format itself (CsvFormat or delimited Format)
