### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by physikerwelt** [stratosphere/stratosphere#149]
The readme file is outdated.

It's said
cd stratosphere-dist/target/stratosphere-dist-0.2-ozone-bin/stratosphere-0.2-ozone/
this folder does not exist.

**Comment by aljoscha** [comment]
Thanks for the hint. :smile:

**Comment by rmetzger** [comment]
I guess the fix is not valid, since our version (currently!) is 0.4-ozone-SNAPSHOT ;)

One other thing, you should probably add to the README is a little note that your eclipse plugin links are only for eclipse x.y.

**Comment by aljoscha** [comment]
Ok sorry, maybe I was a bit to quick there.
