### ISSUE TITLE
Rework Nephele Task Hierarchy

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#165]
I'll keep it short and just quote @StephanEwen from #112:

> That Nephele Class hierarchy has has always bothered us with respect to duplicate logic in souce and sink tasks. The Regular Pact Task has many static methods to set up outputs for example, such that the logic can be called from an input task. [...]
> 
> We should think about changing that class hierarchy, such that all tasks inherit from the same task class and implicitly become input and outputs. Potentially with a property to be set or a marker interface.
> 
> That would also help us to get around fake tails in the iterations.

I think the timeline here should be post release, right?

**Comment by StephanEwen** [comment]
Probably post release, yes.

The other fixed will for now duplicate code from RegularPactTask into DataSinkTask (like @fhueske did for the sorted sink fix)

**Comment by StephanEwen** [comment]
I am moving this to version 0.6
