### ISSUE TITLE
Nephele visualization not working on OS X

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#172]
```
$ bin/nephele-visualization.sh 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no swt-gtk-3346 or swt-gtk in swt.library.path, java.library.path or the jar file
    at org.eclipse.swt.internal.Library.loadLibrary(Library.java:219)
    at org.eclipse.swt.internal.Library.loadLibrary(Library.java:151)
    at org.eclipse.swt.internal.C.<clinit>(C.java:21)
    at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:63)
    at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:54)
    at org.eclipse.swt.widgets.Display.<clinit>(Display.java:128)
    at eu.stratosphere.nephele.visualization.swt.SWTVisualizationGUI.<init>(SWTVisualizationGUI.java:125)
    at eu.stratosphere.nephele.visualization.swt.SWTVisualization.main(SWTVisualization.java:91)
```

**Comment by StephanEwen** [comment]
To make it work, you need a different version of the swt dependency. Unfortunately, last time I checked, Maven central had no appropriate one for Mac OS x, but that may have changed now. 

That problem is one more reason to migrate to a Web-based solution.

**Comment by mleich** [comment]
Last time I checked, there's also a bug in the UI code, that prevents the user from selecting a job for visualization. If it's still there, I'll create a pull request.

**Comment by uce** [comment]
I used it last week on Ubuntu and was able to select different jobs for visualization.

**Comment by mleich** [comment]
It's a Mac OSX specific bug.

```
SWTVisualizationGUI#widgetSelected(SelectionEvent arg0)
```

checks whether a widget has been selected twice within the double click interval (this is probable meant to just check whether a widget has been double clicked upon).
On Mac OSX, once a widget has been selected with one click, the system will _not_ issue another selection event if the widget didn't get deselected before.
In short: the double selection event this method checks for will never occur on Mac OSX unless you manage to selected, deselect, and select again the widget within the double click interval.
My dirty hack around the issue was to simply listen for single selection events.
What do you guys say?

**Comment by uce** [comment]
(In my last comment I thought that you mean that there was a general bug with selection.)

I think your outlined change is fine. It seems to be the simplest thing to do to get it working and since the long term goal is to get to a web-only interface, I wouldn't invest more time than necessary.

**Comment by mleich** [comment]
In #187 you can find the fix for the job selection issue.

**Comment by rmetzger** [comment]
Is it this library? https://code.google.com/p/swt-repo/

**Comment by StephanEwen** [comment]
The select issue is fixed in ebba4fd74adf7caa5ea5f9f46351ff90ee6c4cb0

@rmetzger That is the library. I thought the cocoa versions are not compatible with the latest MacOS X, but a Mac guy would have to verify that.

**Comment by uce** [comment]
Will do :bowtie:

**Comment by StephanEwen** [comment]
Eclipse comes with swt, so there is a version that works with the latest MacOS X. Let's try and find a repository for that.

Do we add maven profiles then for visualization on different platforms?

**Comment by mleich** [comment]
Cocoa is just fine on the latest Mac OS X (didn't test the one that's supposed to be released today).

Stay away from anything that has "Carbon" in its name, though.

**Comment by rmetzger** [comment]
If someone can tell me the exact coordinates of a OS X maven dependency, I can easily create a specialized profile for that.

You can activate profiles based on the operating system (http://maven.apache.org/guides/introduction/introduction-to-profiles.html ) (OSX users have to build their own statosphere then)

**Comment by uce** [comment]
https://code.google.com/p/swt-repo/

(See your _own_ comment :laughing:)

**Comment by StephanEwen** [comment]
The visualization has been moved to stratosphere-experimental and will no longer be maintained. It is also license incompatible with the Apache License.
