### ISSUE TITLE
Add spark-inspired LocalExecutionContext and ClusterExecutionContext

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#176]
I would like to propose a new way to submit jobs since I find the currently existing way to cumbersome. The idea is heavily inspired by spark, but still valid.

With the new way you would do something like this:

val ec = LocalExectionContext()
val input = ec.textFile("<file>")
val counts = input.flatMap { _..split(" ") map { (_, 1) } }
  .groupBy { case (word, _) => word }
  .reduce { (w1, w2) => (w1._1, w1._2 + w2._2) }
  .write("<output>")

To run on the cluster you would do:
val ec = ClusterExecutionContext("<job manager ip>", ...)
...

The execution context would have methods to check whether the job is complete and so on.

**Comment by aljoscha** [comment]
Do you think this is something I should pursue?

**Comment by fhueske** [comment]
I like the idea to simplify job submission. Doing this via a main method is a nice idea. 
However, there are some things that should be possible with low effort:
- Choosing the execution environment for a job (local, cluster, yarn) without changing the code and having the user to implement different paths to select the context.
- Changing job parameters (obviously)

How about having an abstract class with a main method that does the parameter parsing and execution context configuration and calls an abstract getPlan method. A job class inherits from that class and implements the getPlan method. That should be only a small change compared to the current interface. The setup would be quite similar to the way the integration tests work with the test base.

**Comment by fhueske** [comment]
In any case, I think we should try to keep the Java and Scala program submission as similar as possible.

**Comment by aljoscha** [comment]
How would this work with file paths? i.e. "file:///" vs: "hdfs:///"

**Comment by fhueske** [comment]
The main method has a number of fixed parameters for the execution environment and other common configuration stuff (e.g., sync. or async job submission) and variable parameters for the job that is executed, such as input and output files which need to be fully specified incl. the filesystem.

**Comment by uce** [comment]
A big :+1: from me.

What would be the problem of providing something similar for Java job submission?

Is it possible to figure out the jar to be shipped automatically (e.g. dependency visitor) for cluster submission?

**Comment by asteriosk** [comment]
Great idea!

**Comment by asteriosk** [comment]
Especially useful for local debugging and testing on a cluster deployment from within your IDE.

**Comment by aljoscha** [comment]
@uce It might be possible, I talked about this with @StephanEwen once. But right now the spark guys also require you to specify the jar file.
