### ISSUE TITLE
New Quickstart on the Website

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#177]
Please review the new Quickstart site on our website: 
This is a preview: http://rmetzger.github.io/stratosphere/quickstart/

It is "task focused", and reflects what users actually want.

Can somebody do the same for the Scala frontend?
Pull requests against the branch are welcome: https://github.com/rmetzger/ozone/tree/new-quickstart

**Comment by fhueske** [comment]
Nice, but I also have some comments ;-)
- The "cd quickstart" on the Java Job quickstart is indented.
- I find the font color and background of the code snippets a bit too similar. 
- What do you think about including the wordcount job into the archetype? Modifying something that works is usually easier than starting on green ground.

**Comment by fhueske** [comment]
Also the text in the right box is to much. How about: 
"Set up and run an example"

**Comment by rmetzger** [comment]
Related: https://github.com/stratosphere/stratosphere/issues/77

**Comment by aalexandrov** [comment]
I would swap the positions of the right and left boxes and rename them as follows:
- Set up Stratosphere
- Write a job in Scala
- Write a job in Java

**Comment by fhueske** [comment]
I agree with Alex.

**Comment by rmetzger** [comment]
I agree with the shorter names.
But I'm not sure if we should put "Set up .." first. Because there isn't a lot to see ;)
I'm going to track the quickstart interactions with google analytics to see how they are used.

> I find the font color and background of the code snippets a bit too similar.

Yes. I'm in general not very happy with the theme/coloring. But it is really hard to decide such stuff.

> What do you think about including the wordcount job into the archetype? Modifying something that works is usually easier than starting on green ground.

It is actually a good idea. BUT I'm really unhappy with the current word count. It is too complicated. We need a word count that is as short as possible.

**Comment by uce** [comment]
> Yes. I'm in general not very happy with the theme/coloring. But it is really hard to decide such stuff.

Ok, I'll try to adjust them this weekend. I'll also look at the white bar and other stuff that doesn't seem to work correctly. I think we got 80% of the way really fast, but somehow dropped everything after that.

> It is actually a good idea. BUT I'm really unhappy with the current word count. It is too complicated. We need a word count that is as short as possible.

I'll propose a simpler one (e.g. simple Java String splitting etc.) and then we can decide if we want to include it.

And one important thing: we need an overview page. Can somebody propose a first text/bullet points? We quietly assume that everyone who lands at the website already knows what they want.

**Comment by rmetzger** [comment]
Yes, we need a 5 sentence text to explain stratosphere (as I already said here 15 days ago https://github.com/stratosphere/stratosphere/issues/120#issuecomment-25682079)

**Comment by rmetzger** [comment]
Please review the newest preview, with @aljoscha's contribution (Scala Quickstart).

I'm going to publish the new quickstart this evening, because we need it for tomorrow's Scala Intro tutorial.

**Comment by rmetzger** [comment]
Could you also review our first blogpost? 
http://robertmetzger.de/stratosphere/blog/2013/10/21/open-source.html

**Comment by rmetzger** [comment]
Okay, new Quickstart guide and reworked contact page is online.

**Comment by StephanEwen** [comment]
Please see also comment https://github.com/stratosphere/stratosphere/pull/184#issuecomment-26857457

**Comment by StephanEwen** [comment]
Are there any remaining issues? If not, @rmetzger  please close this issue.
