### ISSUE TITLE
Rework Nephele Discovery Service

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#18]
Currently, the nephele discovery service adds extra startup time and port conflicts, but is never used. It was originally designed for certain cloud setups and is obsolete in this version.

**Comment by StephanEwen** [comment]
The Discovery service is in some form required to detect the correct public addresses of the taskmanagers for data transfer. It might be possible to merge that with the jobmanager's ipc port, so we have one less port to worry about (for example in shared settings like YARN).

The JobManager discovery via UDP broadcast can be excluded.

**Comment by rmetzger** [comment]
Since I'm working on the Yarn integration (https://github.com/stratosphere/stratosphere/pull/137) (which breaks the Discovery service anyways) it seems to be reasonable to remove it completely together with adding Yarn support.

**Comment by StephanEwen** [comment]
The taskmanager needs to figure out its public IP. That part, the discovery service did well, in my opinion, although I am not sure how it would work if a computer was in two or more subnets at the same time.

Do we have a good alternative to that?

**Comment by rmetzger** [comment]
We could just use the mechanism to detect the TMs own public IP.
I think we could try on each public IP to reach the JobManager (whose address we know for sure from the configuration file)

I need to look more closely into the code. If you are okay with removing the autodiscovery feature (which seems to be dead anyways), I'll see what I can do.

**Comment by StephanEwen** [comment]
Auto-discovery should go. That one rarely works.

If you manage to detect the right IP Address without the UDP ping, that would be perfect. Saves us one more port that is currently not configurable.
