### ISSUE TITLE
Travis Testing often hangs and terminates on correct tests

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#181]
There seem to be frequent issues with Travis hanging in tests, even if these tests are singlethreaded and without I/O operations.

For example this test

```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/12730622/log.txt
```

hung in the PactrecordITCase, which is a CPU intensive test that takes a while (normally some 10-20 seconds), but is single threaded and isolated.

It seems that the Travis VMs frequently freeze more or less, causing tests to take very long (longer than the threshold) and to get marked as erroneous. The build is then marked as failed, even though all tests cases are actually working.

**Comment by rmetzger** [comment]
I asked travis.

**Comment by StephanEwen** [comment]
Seems that we must accept that test spuriously fail. My last test failed because the maven artifact download took forever and the build timed out.

We may want to remove the build status image,though, because we will get failures marked publicly that are actually no failures.
