### ISSUE TITLE
start scripts depend on "bc", which is not available on a fresh ubuntu.

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#182]
Introduced by https://github.com/stratosphere/stratosphere/pull/163

I'm running a fresh ubuntu 13.04 ([advertisement]from our new demo-vms: https://github.com/rmetzger/stratosphere-vms [/advertisement])

``` ./start-local.sh
/home/vagrant/stratosphere/bin/../bin/nephele-jobmanager.sh: line 34: bc: command not found
```

I hope there are other ways in bash to add two numbers

**Comment by rmetzger** [comment]
More stuff is not working:

```
./start-pact-web.sh 
mkdir: cannot create directory ‘’: No such file or directory
Starting PACT Webfrontend
/home/vagrant/stratosphere/bin/../bin/pact-webfrontend.sh: line 75: /nephele-vagrant-pact-web.pid: Permission denied
```

**Comment by uce** [comment]
I think, we would only need bc for floating point numbers.

Try:

```
a=10
b=10
c=`expr $a + $b`
```

Is this working?

**Comment by rmetzger** [comment]
Yes

```
vagrant@packer-virtualbox-ubuntu:~/stratosphere/bin$ a=10
vagrant@packer-virtualbox-ubuntu:~/stratosphere/bin$ b=10
vagrant@packer-virtualbox-ubuntu:~/stratosphere/bin$ c=`expr $a + $b`
vagrant@packer-virtualbox-ubuntu:~/stratosphere/bin$ echo $c
20
```

**Comment by uce** [comment]
OK, this last one is a bug I seem to have introduced in the last commit changing the YAML config.

We have two options (I was going with the first one, but maybe we should rethink that):
- Add the following to `pact-webfrontend.sh`:

```
if [ -z "${NEPHELE_PID_DIR}" ]; then
    NEPHELE_PID_DIR=$(readFromConfig ${KEY_ENV_PID_DIR} "${DEFAULT_ENV_PID_DIR}" ${YAML_CONF})
fi
```

I chose to set the env variables only in the needed files, e.g. if you don't run a script which needs to set the pid dir, it won't get set.
- Put every env setting into `nephele-config.sh`. Not just the common ones. You know what I mean?

**Comment by rmetzger** [comment]
1) fixes the Problem.

You have to explain me the background more detailed. Lets discuss this in person (except somebody else wants to know the details, too).

**Comment by rmetzger** [comment]
Can you also change back the port of the webinterface to 8080. All the existing documentation is using this port!

**Comment by uce** [comment]
yes, sure. must have been an accident. didn't mean to change it to 8088.
