### ISSUE TITLE
Remove IPv4 Stack Hint

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#189]
Nephele has in many scripts hints to Java to run an IPv4 stack. If I recall correctly, the hint was necessary for the discovery manager broadcast-message-discovery in cloud setups.

Since we do not use that mechanism any more, we should be able to remove these hints from the scripts and test setups.

**Comment by uce** [comment]
OK, this was kind of a fail. First I didn't check out the new branch from master, which I noticed after doing the PR. Then I noticed that @StephanEwen had conflicting changes on our master branch in a pom file.

So that's why it says that I reference this issue three times. :zzz: :punch:

**Comment by StephanEwen** [comment]
Fixed as of 361e469bb9ac742bd3c2ddaf930cdebe160300f1
