### ISSUE TITLE
Restructure pact-tests

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#19]
The abstract classes for running in-jvm tests should be available to the outside (e.g. to framework built on-top of ozone)

**Comment by uce** [comment]
[TestBase2](https://github.com/stratosphere/stratosphere/blob/bdd378c8b754d05a32ad260ada6843c104ffbf2a/stratosphere-tests/src/main/java/eu/stratosphere/test/util/TestBase2.java) has been moved from the tests folder of `stratosphere-tests` to the main folder with the renaming and is available to the outside. Is this enough?

Discussion in #433 may be(come) relevant.

**Comment by StephanEwen** [comment]
This seems solved. The test base is now directly visible. Utilities for specific test (test data generation and validation) are available through the test jar.
