### ISSUE TITLE
LocalExecutor does not properly stop.

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#196]
Very often when executing a plan using the LocalExecutor and calling stop() it happens that there are lingering threads and the program won't stop. It does not seem to happen when simply starting the LocalExecutor and then stopping.

Does anyone have any idea why this is happening. It is really annoying and I want to use this in the upcoming ExecutionContext.

**Comment by StephanEwen** [comment]
The RPC Service has some lingering Threads, that is a known problem. Do you see any other ones?

**Comment by aljoscha** [comment]
No, only the RPC threads. I tried manually closing them somehow in the NepeheMiniCluster but had no luck.

**Comment by StephanEwen** [comment]
The rpc service is pretty crappy, it needs to be changed as part of the JobManager reworking. Does the service mark its threads as daemons, or do they keep the vm alive?

**Comment by aljoscha** [comment]
If have no idea, and no time to look into it right now.

**Comment by StephanEwen** [comment]
Fixed in 9306beb181fcb218f44d7a9a50e4bbb3258c1b79
