### ISSUE TITLE
SequenceFileInputFormat

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#198]
Along the lines of #134 I think it would make sense to have a `SequenceFileInputFormat` delivered with Stratosphere.

Has anyone ever implemented this?

**Comment by StephanEwen** [comment]
There is a sequence file format implementation by Michael Hülfenhausen. We can merge that one in. Onto the core project or into an extensions project?

**Comment by uce** [comment]
I think core is fine.

**Comment by rmetzger** [comment]
+1

**Comment by rmetzger** [comment]
@StephanEwen: Is there any other valuable code lying around at the TU?

We should get everything usable we have into the project.

**Comment by fhueske** [comment]
see #199

**Comment by rmetzger** [comment]
https://github.com/rmetzger/stratosphere-sequencefile

**Comment by rmetzger** [comment]
This is now possible with https://github.com/stratosphere/stratosphere/pull/437
