### ISSUE TITLE
Add a dedicated pact-connector Maven submodule

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#199]
We have code that connects Pact to other software, such as input formats for HBase, Avro, Hadoop Sequence files, etc.
We already had discussions whether to extract this code into a dedicated repository but in the end decided to keep it in the main repo for now.

However, I think it makes sense to have at least a dedicated Maven submodule for such code. This could for example be named pact-connectors or pact-connect.
The code from the current pact-hbase could go into this, as well as all other input formats and other code that is not part of the core system. This would also be beneficial if we decided at one point in time to extract this code into another repo.

**Comment by StephanEwen** [comment]
Sounds reasonable to me.

**Comment by uce** [comment]
I don't like the separate repo idea, but having a separate module sounds really good. I also like the name proposals. :v:

I assigned the release milestone to this issue.

**Comment by fhueske** [comment]
Btw, what is contained in the pact-array-datamodel module?

**Comment by uce** [comment]
Some magic  :blush: which allows you to do stuff like:

```
 private final Value[] outputRecord = new Value[] { this.word, this.one };
```

But was this really the question? Are you asking whether we should move it into `pact-connectors`? Or if we should remove it?

I've never used it and always find it inconvenient when Eclipse proposes classes from it for auto complection when I actually want the quasi default PactRecord stuff. :grin: But that's just me... it also demonstrates that we are not tied to PactRecord.

**Comment by rmetzger** [comment]
I also like the idea of an additional maven module for (in|out)put formats / connectors.
But, there is currently one issue with `pact-hbase`. We include this module only when building with the Hadoop 2.x (YARN) profile.

**Comment by rmetzger** [comment]
Okay,
I'm going to add the following to the current project structure (This is required to merge-in https://github.com/stratosphere/stratosphere/pull/279 and the other input formats)

```
stratosphere
    `- pact
    `- pact-scala
    `- nephele
    `- stratosphere-dist
    `- stratosphere-addons
        `- hbase-bulk
        `- hbase-simple
        `- jdbc
        `- sequencefile
        `- avro
```

It is necessary to have a separate maven project to
- only add those dependencies if the user includes the addon
- conditionally include or exclude the package on different build profiles

I'm in favor of keeping this code inside the main distribution to ensure test coverage and maintenance!

The new maven module also fits into our new naming scheme (https://github.com/stratosphere/stratosphere/issues/257).

**Comment by StephanEwen** [comment]
Looks good. Just to clarify: are the bullet points below stratosphere-addons individual Maven projects, or java packages?

**Comment by rmetzger** [comment]
Individual Maven projects. They have all very different (and heavy)
dependencies.

Sent from my iPhone

On 25.11.2013, at 08:53, Stephan Ewen notifications@github.com wrote:

Looks good. Just to clarify: are the bullet points below
stratosphere-addons individual Maven projects, or java packages?

—
Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/issues/199#issuecomment-29182892
.

**Comment by fhueske** [comment]
What about moving the array dm also into stratosphere-addon?
Is it used somewhere in the main code base?

**Comment by StephanEwen** [comment]
Lets move it.
Am 25.11.2013 09:03 schrieb "Fabian Hueske" notifications@github.com:

**Comment by rmetzger** [comment]
The code for Sequencefile Input format is now located here: https://github.com/rmetzger/stratosphere-sequencefile
(if anybody is interested in integrating it) (Its probably better to implement generic support for the SerDe framework!)
