### ISSUE TITLE
Combiner is cannot be chained if Reducer DOP differs from the DOP of its input.

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#201]
Currently, the DOP of the combiner is set to the DOP of the reduce task. In case, that the Reduce task has a different DOP than its input, an inserted combiner is not chainable since this requires an identical DOP with the sender task.

This bug was detected and described in more detail in this issue #138.
Since, #138 also includes another bug, I created a new issue.

**Comment by fhueske** [comment]
I have implemented a fix for this bug, but for some reason it causes another test to fail. 
The fix is in a branch of my repository [combinerBugFixes](https://github.com/fhueske/ozone/tree/combinerBugFixes). 

The failing test is the compiler test [IterativeKMeansTest](https://github.com/fhueske/ozone/blob/combinerBugFixes/pact/pact-tests/src/test/java/eu/stratosphere/pact/compiler/iterations/IterativeKMeansTest.java) and the the assertion error is
     <code>java.lang.AssertionError: expected:&lt;PARTITION_HASH&gt; but was:&lt;FORWARD&gt;</code>

I checked that the modification of [GroupWithPartialPreGroupProperties](https://github.com/fhueske/ozone/blob/59b81b64e3d6bff28c64b260e21ca4cd96a3191c/pact/pact-compiler/src/main/java/eu/stratosphere/pact/compiler/operators/GroupWithPartialPreGroupProperties.java) triggers the test to fail.
There seems to be some other bug in the Pact compiler.

@StephanEwen Can you check what causes the test to fail and fix it so we can merge my fix into the main branch?

**Comment by StephanEwen** [comment]
Fixed as of 80551cb783a5e3bf47c20f6c1b4059dd8c691220
