### ISSUE TITLE
Workset Iterations: "No Match Found" Behaviour of Solution Set Join

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#202]
If I do a solution set match and there is no corresponding entry in the solution set index a RuntimeException is thrown and the job fails. Therefore the initial solution set must already contain every element which will be in the final solution set.

I'm not sure if this is a real limitation, but I find it inconvenient. When I was playing around with the workset connected components I couldn't just use parts of my test data, because it resulted in a solution set join where records couldn't be matched.

I just wanted to think out loudly here. Did anybody else find this inconvenient? What alternative should we provide?

**Comment by StephanEwen** [comment]
The exception if no element is found is a unwanted restriction for lack of support in the hash index. We definitely want to support this.

There is ongoing work to refactor the hash table / hash join to support these operations. It is linked with issue #162. W
