### ISSUE TITLE
Syntatic sugar for flatMap

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#205]
Allow users to directly return an instance of IterableLike without having to call .iterator

**Comment by fhueske** [comment]
This refers to #159

**Comment by aljoscha** [comment]
Right now, when you import eu.stratosphere.scala.operators._ you will get implicit conversions from Traversable/Array/Option to Iterator. So you can leave of the .toIterator.

**Comment by sscdotopen** [comment]
Awesome, thx!
