### ISSUE TITLE
Remove Java 1.6 compatibility?

### ISSUE THREAD

**Issue by mleich** [stratosphere/stratosphere#214]
In stratosphere-sopremo we consider removing JDK 1.6 compatibility. One thing less to worry about.

While stratopshere-sopremo could throw out support for 1.6 it does not make sense to do so, if Stratosphere retains support for 1.6.
It would be incoherent and in the worst case, people run Stratosphere with 1.6 on one system, Sopremo with 1.7 on another and don't understand why things stop working.

So, Sopremo can only stop supporting 1.6 if Stratosphere does the same, hence this issue.

I created my pro/con list, feel free to comment:

Pro:
- one JDK version means easier maintanance
- we can finally use all the Java 7 features
- Oracle doesn't provide patches anymore for JDK 1.6 [citation needed](apparently it does for paying customers)

Con:
- raised barrier of entry, there may be people who just didn't bother to update to 1.7 even though they could have
- use of Stratosphere may be even impossible for some users because the can't switch to 1.7 for whatever reason

[Disclaimer] I just moved this discussion to an issue, so everyone can participate, don't kill the messenger :-P

**Comment by physikerwelt** [comment]
I think we could remove jdk 1.6 support without long discussion, if the intersection of the jdk 1.6 users and the stratosphere 0.4-users is an empty set.

**Comment by StephanEwen** [comment]
Is it really bad if Meteor/Sopremo requires 1.7 and the lower layer does not? You can state that as a Meteor requirement.

If someone starts with Stratosphere without Meteor and then adds meteor, he might have to upgrade Java. Is an impractical requirement? I am not sure...

**Comment by physikerwelt** [comment]
Who said that it's bad? mleich pointed out that that it would be incoherent.
I'm not 100% sure how coherent software is defined, but I guess it's correct so state that the coherence decays  if the requirements diverge.

**Comment by StephanEwen** [comment]
I am a bit uncomfortable with any restriction that is not needed.

So, I wonder, does it really make a difference for Sopremo users if the lower level has fewer requirements?

Concerning coherency: Componentization of software is exactly to allow for divergence in development cycles and requirements. Higher layers may pose more requirements than lower ones.

**Comment by rmetzger** [comment]
Which issues do you have with 1.6 in Sopremo?
Did anybody prove that Sopremo with 1.7 and Stratosphere with 1.6 don't work together?
We use apache commons-io in version 2.2 which is compiled for java 1.5. So backward compatibility should be given. 

Why should we drop support for something that is working perfectly fine.
Even if we run on java 7 jvms, our code is compiled for java 1.6.

I can not remember maintenance issues with Java 6.

The JVM on our cluster (cloud-11) at dima is a Java 6 one. Its an  Ubuntu 10.04.4 LTS which probably does not even have Java 7 in its repos.

So I vote for keeping Java 6 support!

I would personally recommend everybody to use Java 7, because there are no security patches for Java 6 anymore.

**Comment by physikerwelt** [comment]
@rmetzger So you say cloud-11 is the user that requires java 1.6?

**Comment by rmetzger** [comment]
We are currently doing a research cooperation with the Deutsche Telekom,
evaluating Stratosphere.
Java 6 is on their server as well.

On Fri, Oct 25, 2013 at 6:09 PM, physikerwelt notifications@github.comwrote:

> @rmetzger https://github.com/rmetzger So you say could-11 is the user
> that requires java 1.6?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stratosphere/stratosphere/issues/214#issuecomment-27104962
> .

## 

Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Comment by sscdotopen** [comment]
I don't understand the problem. Sopremo can move to Java 7 and without any problems use a Java 6-based Stratosphere.

**Comment by physikerwelt** [comment]
There is no problem, if less coherence is not is a problem.

**Comment by sscdotopen** [comment]
You trade two things off here: Easier development through a more modern version of the language vs the size of a possible user base

There are no problems with coherency. Java is so successful, because you can always use your old code with new versions of the language.
