### ISSUE TITLE
TestBase2 is not platform independent (WINDOWS)

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#217]
A student from IMPRO-3 who is using Windows 7 reported a bug with Testbase2.

The methods "getTemp*Path()" have the prefix "file://" hardcoded.

I assigned @markus-h to this issue, since he is a Windows user.
I think there is a way in java to find the platform's way to separate directories.

use "mvn verify" to trigger the bug.

**Comment by markus-h** [comment]
I started working on the issue. Looks like not only file paths need to be adjusted in the testings but also most exec commands.
Moreover I tried to use the shell scripts to start the server (eg start-local.sh), but they seem not to work under cygwin for me. Would perhaps be a nice enhancement?

**Comment by rmetzger** [comment]
We had once a PR that claimed to make Stratosphere Cygwin compatible.

Where do we have exec commands? Do you mean the scripts in /bin ?

**Comment by uce** [comment]
What is the problem with the scripts?

I remember @aljoscha adding a function to change the filepaths on cygwin installations. The changes we introduced afterwards only affected the call to `uname` to figure out on what kind of system we are running. Strange.

**Comment by StephanEwen** [comment]
I think the only problem we are facing here is that the file URI prefix is hard coded.

It should do to replace 

```
file:// + f.getAbsolutePath()
```

with

```
f.toURI().toString()
```

Se we need to externalize the path prefix which contains the scheme

**Comment by uce** [comment]
Yes, sure. @rmetzger checked it yesterday on a Windows machine and indeed `file:\\` does the trick.

But @markus-h's problem with the scripts sounds independent of this to me. Afaik there are no hardcoded paths in the scripts.

**Comment by markus-h** [comment]
The issue for the hard coded URI prefixes is quite easy to resolve, like StephanEwen mentioned. 

But there are multiple exec calls out of Java in the testcases (Runtime.getRuntime().exec(cmd)). For example in ExternalProcessFixedLengthInputFormatTest, ExternalProcessInputFormatTest and even in the ExternalProcessInputFormat class. These seem to be a little bit harder to resolve in windows.

**Comment by fhueske** [comment]
As the name suggests, an ExternalProcessInputFormat starts an external process and parses its output into records.
The process is of course not OS independent. Not sure if the tests can be adapted in a way that the call to Runtime.exec() call or Process that represents the external process is mocked.

Is there a way in Maven to provide platform dependent tests or disable certain tests for different platforms?

**Comment by StephanEwen** [comment]
I think it would be file to do a OS detection in the test. If the OS is
windows, the tests are skipped (the test method just returns directly). We
still get the test coverage on the Linux systems, which is where we build
anyways, and I would not want to invest too much time in having this very
specific test platform independent.

**Comment by fhueske** [comment]
I agree, sounds like a plan.

**Comment by rmetzger** [comment]
+1

**Comment by rmetzger** [comment]
@StephanEwen: `f.toURI().toString()` will result in paths like `file:/tmp/input` (if `f instanceof java.io.File`). For some reason I don't understand, we usually use `file:///tmp/input` for local paths. 
I think it will work with `file:/tmp/input` too, because `eu.stratosphere.nephele.fs.Path.toUri().getScheme()` is able to extract "file" as the scheme.

I know the URI's for HDFS must contain `hdfs:///` to specify the Namenode host.

**Comment by StephanEwen** [comment]
Solved by #299 in 385c0be988eef4fe93602e0d13e526c22179c37e
