### ISSUE TITLE
Replace Cross by CrossWithSmall and CrossWithLarge

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#218]
The Cross operator is currently very dangerous. Until we have incremental plan rollout, the optimizer has to rely on fallback heuristics when estimates are not available. Unfortunately, there is no proper fallback heuristic for Cross: One side needs broadcast, which can kill any plan if it is the wrong side.

In the spirit of robustness and stability, I would like to take the Cross temporarily out of the equation by offering only a construct that explicitly declares which side is the smaller.

As soon as the heuristics model is improved, or we have implemented the incremental plan rollout, we could re-introduce the self-deciding Cross.

Comments are welcome!

**Comment by rmetzger** [comment]
I would not recommend to put any effort into this, if there is no user complaining.
Could be, that you spend 5 hours for a feature that is first needed in two years.

I think having a specialized interface makes the user aware of the situation, so I think your suggestion is in general a good idea.

**Comment by uce** [comment]
I know that @andrehacker has complained about this. I would go for the change. :baby_chick:

**Comment by ktzoumas** [comment]
Better not change the interface twice. Perhaps keep the name cross and
instruct the users to put the large (partitioned) data stream first?

**Comment by StephanEwen** [comment]
How about introducing the two new versions (which are essentially like the original Cross plus a compiler hint) in addition? We can advise users to stick with those for the near future until the incremental optimization works.

I have the feeling that the Hadoop ecosystem programmers like the idea of having concise explicit control, which is what these two new versions would give them.

That way we do not break APIs.

**Comment by fhueske** [comment]
Why not keep cross with undefined order and simply add one of crossWithSmall or crossWithLarge.
Having a cross with an explicitly specified input order might always be helpful. 
Until the optimizer is able to do a good decision here, we advice to use cross with explicit order.

The problem that I see with giving users the advice to put the large stream first, is that the processing strategy might change once the optimizer can do a rational decision (or only thinks it can...).

**Comment by andrehacker** [comment]
+1 for adding the two explicit versions until non of the other approaches is taken. I like the naming!

The problem is significant, because for any Cross with a file, the file broadcasted (at least if the other output is not from file and therefore the size in bytes is unknown. This is a common case as long as we use Cross as a solution for closures/global variables).

Here the picture from such a situation in my job:
![compiler-wrong-broadcast-strategy](https://f.cloud.github.com/assets/659564/1429797/27b7b358-40b8-11e3-8b9f-983ae6bc31ba.png)

**Comment by StephanEwen** [comment]
Fixed in cfb20f9362d832fd2f813e9a8f8575aa25f1ca70
