### ISSUE TITLE
Rework optimizer cost functions.

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#22]
The optimizer cost functions and cost heuristics need to be faithfully implemented to produce good plans and fall back to robust plans in case of missing estimates.

**Comment by rmetzger** [comment]
This is related: https://github.com/dimalabs/ozone/pull/90

**Comment by rmetzger** [comment]
Is this the fix for the issue? https://github.com/stratosphere/stratosphere/pull/479

**Comment by StephanEwen** [comment]
Fixed by #479
