### ISSUE TITLE
Show cluster status info in JobManager Web Frontend (such as number of registered machines)

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#233]
It would be good to have additional information in the JobManager Info Frontend, such as the number of worker machines that are registered, etc. Saves the check in the log if all machines went up successfully...

**Comment by rmetzger** [comment]
+1 I suggested exactly the same.
There is code for that in my LocalDistributedExecutor
(JobManager.getNumberOfTaskTracker()) pull request (which is still not
ready :( )

**Comment by StephanEwen** [comment]
This is implemented for a while by now.
