### ISSUE TITLE
Stratosphere does not work out of the box on Mac OS X

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#235]
The TaskManager fails to allocate memory.

**Comment by uce** [comment]
Can you please be more specific? How can I "reproduce"/see this?

**Comment by rmetzger** [comment]
Sure,
I was in a hurry during the IMPRO lecture.

If you check out the BigDataClass exercise on MacOS X into eclipse and try
to run the main() method, it will fail with an OutOfMemory exception.

Could be that we can not do anything about this because you can probably
not change the run configuration in eclipse.

On Wed, Nov 6, 2013 at 5:01 PM, Ufuk Celebi notifications@github.comwrote:

> Can you please be more specific? How can I "reproduce"/see this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stratosphere/stratosphere/issues/235#issuecomment-27885777
> .

## 

Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Comment by asteriosk** [comment]
I had the same problem. But I think there is nothing that could could do about it (apart from mentioning it in the tutorial) as the VM heap size has to be set by the "Run Configuration"...

**Comment by rmetzger** [comment]
There is a maven-eclipse plugin which can for example add folders to the source path. Someone should dig deeper into that to see if there is a way.

**Comment by StephanEwen** [comment]
What is the status of this issue?

Is the problem that when starting examples out of eclipse, the default heap size is too small?  If yes, what is the size? Stratosphere should scale down with head sizes.

Or is there anything else?

**Comment by fhueske** [comment]
@uce , @asteriosk : Any updates / comments on this issue?

**Comment by rmetzger** [comment]
The issue still persists.

**Comment by StephanEwen** [comment]
What is the renaining problem?
Am 07.02.2014 10:39 schrieb "Robert Metzger" notifications@github.com:

**Comment by rmetzger** [comment]
The problem is that the default heapsize on Mac OS X is too small for Stratosphere to start successfully (with the LocalExecutor).
So if a new (OSX) user wants to run the WC example from eclipse, it will fail with a OOM Exception. We either have to reduce our memory footprint or put a clear notice onto all quickstart/documentations.

@JonathanH5: Can you add a notice box to http://stratosphere.eu/quickstart/java.html  above "Build Project" that says """
A note to Mac OS X users: The default JVM heapsize for Java is too small for Stratosphere. You have to manually increase it. Choose "Run Configurations -> Arguments and write into the "VM Arguments" box: "-Xmx800m" in Eclipse.
"""

**Comment by StephanEwen** [comment]
Hmmm... it runs for me with -Xmx100m on Linux. Does the Mac jvm eat vastly
more memory, or does it by default stay with a tiny amount?
Am 07.02.2014 12:08 schrieb "Robert Metzger" notifications@github.com:

**Comment by StephanEwen** [comment]
Fixed in #465
