### ISSUE TITLE
Downloading sources not possible from Eclipse

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#237]
We generate source attachments, but eclipse is unable to download them.
I think I'm going to fix this.

https://github.com/stratosphere/stratosphere/pull/126

**Comment by StephanEwen** [comment]
Did work for me by now. Is this issue resolved?

**Comment by rmetzger** [comment]
Okay, I tried it on a fresh Ubuntu (I have a virtual machine for such tests). It does actually work.
