### ISSUE TITLE
Create FAQ section on the Website

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#241]
Create an FAQ Section in the Wiki and link it from the Website (next to Documentation?)

**Comment by uce** [comment]
Why do we want this as a Wiki?

I would like to have it consistent with the documentation (therefore on the webpage) even though it would be easier to edit with a Wiki.

**Comment by uce** [comment]
Our Documentation is terribly outdated. :mask: Will also look into it. :cake:

**Comment by rmetzger** [comment]
This issue is related https://github.com/stratosphere/stratosphere/issues/77

**Comment by uce** [comment]
This has been fixed, the [FAQ](http://stratosphere.eu/faq) still needs some updating though.
