### ISSUE TITLE
Support for custom objects in Scala-frontend

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#243]
It is extremely important to support the usage of complex custom objects (e.g. the Vector classes from mahout math). Nobody will want to rewrite those to be able to use Stratosphere. The ability to register a custom serializer for those should be sufficient as a first step.

**Comment by StephanEwen** [comment]
Fixed in cbfc5c2097f2286f6e1b27beb695d3d2292c9570
