### ISSUE TITLE
Rename Input and Output Formates

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#246]
I think we should rename the input and output formats because the names are misleading. Delimited*Format sounds like a CSV style input format, but it is a line input format. Record Input Format has no intuitive meaning to most people.

How about we name them
-  RecordInputFormat to CSVInputFormat (even though delimiters are not necessarily commas)
-  DelimitedInputFormat to LineInputFormat

**Comment by aljoscha** [comment]
Agreed on CSVInputFormat, but LineInputFormat would make people think that they get individual lines in the records. But they don't, that's what TextFile() (and TextDataSourceFormat) is for.

**Comment by StephanEwen** [comment]
Okay. What could we call the DelimitedInputFormat? Should we just keep it? Does the term 'delimited' raise confusion with delimited fields?

**Comment by aljoscha** [comment]
Maybe BlockInputFormat.

**Comment by fhueske** [comment]
I agree that the formats should be renamed. 
CSVIF is fine.
How about ByteRecordIF for DelimitedIF? It splits the data into records of bytes which must be manually parsed, since the IF is an abstract class.

**Comment by StephanEwen** [comment]
Subsumed by #257
