### ISSUE TITLE
Start Webfrontend with Jobmanager?

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#249]
Currently, the Pact web frontend needs to be manually started by running a separate script. I don't think that running the frontend on another machine as the JM is very common.
Should we start it with the Jobmanager start script (or as another thread of the JM process) with an option to disable it?

**Comment by aljoscha** [comment]
I don't know how many people use the web interface. I don't, when I can avoid having to.

**Comment by fhueske** [comment]
Same here.
@StephanEwen integrated the Pact web interface with the JM info interface for a demo. Having both things together in a nice web interface that starts with the JM would be good though in my opinion.

**Comment by StephanEwen** [comment]
I also would not start the compiler web frontend in any case. it allows to upload stuff, and trigger the execution of arbitrary programs, which is nothing you want generally exposed.

**Comment by StephanEwen** [comment]
We resolved the issue as follows:
-  The job manager info web interface is started with the job manager (it already is)
-  The compiler visualization is optional for demo purposes and not started with the job manager
