### ISSUE TITLE
Website shows "Build Status: build error"

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#251]
The Travis build status icon on the bottom of the [Stratosphere Github start page](https://github.com/stratosphere/stratosphere) shows "build error".

However, when clicking on the icon, the Travis website says "Status: passed".

**Comment by rmetzger** [comment]
Mh, so currently, both badges show "build:error" which is correct because the last build failed.

I hope the current build is going through. Lets see if the badge on our readme updates accordingly.

**Comment by fhueske** [comment]
Hmm, seems to be fine again.... 
Its probably a Travis issue anyways. I'm closing this issue for know.
