### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#257]
Here is a comprehensive list of all renamings that we want to make before the release. Since renaming will break user code, we should do that once and coordinated, if we do it at all.
-  Match -> Join
-  Contract -> Operation
  -  MapContract -> MapOperator
  -  ReduceContract -> ReduceOperator
  -  MatchContract -> JoinOperator
  -  CoGroupContract -> CoGroupOperator
  -  CrossContract -> CrossOperator
-  RecordInputFormat -> CsvInputFormat
-  RecordOutputFormat -> CsvOutputFormat
-  PlanAssembler -> Job (or StratosphereJob)
-  Plan -> remains Plan (no change)
-  ScalaPlan -> Plan

The next version of Pact program construction works without a Plan object and will be called "Program"

---

We also want to reorganize the code project structure (aka the maven dependency structure) to make it simpler for developers and users. As this also breaks programs (in terms of configured dependencies), we want to do this in the same refactoring.

![projects](https://f.cloud.github.com/assets/1727146/1501858/5a9d9184-4892-11e3-91ed-987ae2ea487e.png)

---

This issue subsumes issues #222 #246

---

Please comment and raise concerns early!

**Comment by rmetzger** [comment]
We have some submodules which are only conditionally included into the build. nephele-yarn and pact-hbase.

Affected by this change
- Users have to change their dependencies + code
- pending pull request
- other unmerged work 
- Quickstarts
- BigDataClass.org
- stratosphere2 should also do this change to be able to pull our changes
- Documentation, slides, everything out in the web 
- Source code documentation

But I totally agree with all changes!
We should do these changes as soon as possible!

What does "bleibt" and "oder" mean?

**Comment by rmetzger** [comment]
When doing the renaming, we can also fix this issue https://github.com/stratosphere/stratosphere/issues/122

**Comment by andrehacker** [comment]
Just one comment: For me, CoGroup was always like a Reduce for multiple inputs.
Therefore I would propose to either change them to "Reduce and CoReduce" or "Group and CoGroup".
Or simply call them both "Reduce" or "Group", with two Builder classes: one for a single and one for multiple inputs.
(All other contracts have a very different semantic, but CoGroup and Reduce are almost the same in terms of semantic)

I guess you already discussed a lot about renaming, so if my proposal is not new - just ignore it ;-)
André

**Comment by uce** [comment]
If we go with @andrehacker's proposal, we could also think about having just a single builder which decides to use CoGroup or Reduce depending on the inputs.

---

We should also rename the scripts. Replace the `pact-` prefix with `stratosphere-` and for the visualization script remove the `nephele-` prefix.

**Comment by uce** [comment]
And JobManager and TaskManager are also very Hadoop inspired. Why not rename them to **master** and **worker**?

I know that @rmetzger is against this, because the comments will get out of sync, but they are out of sync already and need fixing anyways.

**Comment by aljoscha** [comment]
So is this package restructuring still happening? I'm all for it.

**Comment by uce** [comment]
Just noticed: We also have to rename the config keys (like `pact.parallelization.degree`) if we want to get away from the `pact` name.

---

Btw: I'm also all for it.

**Comment by fhueske** [comment]
I agree with most changes but I am not sure if it is a good idea to replace Pact by Stratosphere and keep Nephele as it is. Stratosphere is the name of the whole thing and naming only a part of the system like that might confuse people. Pact might not be the best name, but Stratosphere is worse in my opinion. 
If Pact should go, I think we should use a new name for that...

**Comment by fhueske** [comment]
Wrong button, sorry...

**Comment by rmetzger** [comment]
We should also rename the `PactRecord` and all the other types with `Pact*`

**Comment by uce** [comment]
Please also make sure that we rename all packages containing `type` like `eu.stratosphere.pact.common.type.Value` for example to `types`, becasue `type` is a Scala keyword.

**Comment by StephanEwen** [comment]
I am currently reorganizing the maven projects according to the components in the sketch above. I am now struggling where to put the clients and the compiler web-frontend. Any preferences?

Right now I see these options:
- Make an own project for clients
- Make it part of the compiler project, as the clients need the compiler/runtime anyways. At least the LocalExecutor needs to runtime and the remote executor needs the compiler until we moved the compiler to the master.

**Comment by rmetzger** [comment]
`Pact-Assembler-Class` has been renamed to `program-class`.

**Comment by fhueske** [comment]
@StephanEwen, @rmetzger: Is this issue resolved and can it be closed?

**Comment by StephanEwen** [comment]
This issue is resolved.

**Comment by fhueske** [comment]
Alright, I close it then.
