### ISSUE TITLE
Gerrit Code Review or Github’s fork

### ISSUE THREAD

**Issue by physikerwelt** [stratosphere/stratosphere#260]
Just given the open source community a chance to comment on that:
I propose to enable this project for
http://gitenterprise.me/

**Comment by sscdotopen** [comment]
Do we have any problems with github and the pull requests? If not, we should live like: "Don't fix it if it ain't broken".

**Comment by physikerwelt** [comment]
https://upload.wikimedia.org/wikipedia/commons/9/98/Ericsson_Taxen_%282%29.jpg

**Comment by ktzoumas** [comment]
Nice phone. I am closing this for now.

@physikerwelt I propose that you open a new issue with an informative text on what problems this can solve for the project, or what processes it can improve on.

**Comment by physikerwelt** [comment]
@ktzoumas gerrithubt simply adds another (maybe simpler) way to contribute to the project (see the link http://gitenterprise.me/ for a detailed comparison). It can be set up within 5 minutes does create only little management overhead.
