### ISSUE TITLE
Fix stalling JobManagerITCase.testBroadcastChannels() (on travis)

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#263]
The test is currently disabled
https://github.com/stratosphere/stratosphere/blob/master/nephele/nephele-server/src/test/java/eu/stratosphere/nephele/jobmanager/JobManagerITCase.java?source=cc#L530

It does not fail on my own computers, only on travis but not always on travis:
If it fails, it just hangs.
Logs: https://s3.amazonaws.com/archive.travis-ci.org/jobs/13760959/log.txt (https://travis-ci.org/rmetzger/stratosphere/jobs/13760959)
https://travis-ci.org/rmetzger/stratosphere/jobs/13744608
https://travis-ci.org/rmetzger/stratosphere/jobs/13760618
(The logs are from some test builds with the local distributed executor https://github.com/stratosphere/stratosphere/pull/262, with this test enabled.)

The fails are random, I don't see a correlation between jvm versions or build profiles.

**Comment by StephanEwen** [comment]
I would ignore (disable) that test for now, because the code it tests is
known to be broken and is not used right now.

**Comment by StephanEwen** [comment]
The Broadcast/Multicast logic has been removed, as it was inherently unstable and unpredictable. It was not used anyways.
