### ISSUE TITLE
Simplify ./bin/stratosphere (former ./bin/pact-client.sh)

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#264]
I was using the pact-client.sh to day, and its interface seems to be a bit over-engineered.

For example

```
Action "cancel" cancels a submitted PACT program.
  "cancel" action arguments:
     -i,--jobid <jobID>   JobID to cancel
```

Its just annoying to enter `cancel -i` if you want to cancel a job. The `-i` does not add any information or value at all!

The `list` action should always list all jobs, the arguments should be seen as filters.

It would be nice to make the `-a` of `run` optional. Everybody is used to enter the arguments after the .jar file.
I was confused for 2 minutes today why my program is not working (I forgot to add the stupid '-a` for the argument!)

**Comment by uce** [comment]
Yes, let's do this together with #266.

And I think we should also come up with renamings for the scripts (in #257).

**Comment by StephanEwen** [comment]
I agree, we need a simpler syntax.

**Comment by fhueske** [comment]
`./bin/pact-client.sh` was renamed to `./bin/stratosphere`

**Comment by StephanEwen** [comment]
Simplification would still be nice. For example:
- omitt the -j flag after the commands run and info. The jar has to come
  there anyways.
- allow all flags at the beginning. -w may currently only come after -j,
  -v only after run and so. This still confuses me.
- everything after the jar should be parameters
- it would be good to have dop flags. I think setting the dop inside the
  programs is awkward.
  Am 07.02.2014 10:36 schrieb "Fabian Hueske" notifications@github.com:

**Comment by uce** [comment]
I agree; especially with the DOP stuff. We should then also add constructor parameters to the local and remote executor to set the plan DOP (which wouldn't break anything).

**Comment by rmetzger** [comment]
See also https://github.com/stratosphere/stratosphere/issues/361

**Comment by rmetzger** [comment]
Resolved by @StephanEwen in some commits.
