### ISSUE TITLE
Change Maven Artifact Names

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#27]
Currently, ozone uses the same artifact names as Stratosphere 0.2. That means it is not possible to work with both in parallel (as in code migration, cross testing, ...)

Ozone should have new artifact names and a new Version. I propose Version 0.5 (some leap from 0.2)

**Comment by aalexandrov** [comment]
I use 0.2-ozone as version name in my POMs, but a quick grep replace should be able to change it to whatever you want. 

I am not quite sure why we need different artifact names. Changing the version did the trick for the local m2 repository, and in eclipse you can set a custom name template (.e.g. `[artifactId]-[version]`) for imported Maven projects under the advanced options.

**Comment by StephanEwen** [comment]
At the moment, several people maintain installations of the stratosphere mainline version (stratosphere-0.2) and the ozone version. Since both will release newer versions, the best way to avoid name clashes in the repositories is to go with different artifact names.

However, since we may abandon the name "ozone" and continue distributing it under the label "stratosphere", we could leave the artifact names and only change the version as suggested.

**Comment by aalexandrov** [comment]
Should I prepare suggest a push request for that?

**Comment by StephanEwen** [comment]
Can you elaborate on the Eclipse template you mentioned? Is that a thing you need to do to make the setup work?

**Comment by aalexandrov** [comment]
No, it will work with the standard naming convention for the eclipse projects out of the box. Bit if you already have the "default" stratosphere packages imported in eclipse using the standard package names (pact-compiler, pact-runtime, etc.), you have to modify the names of the Ozone projects as you import them. 

One of the options that the maven importer gives you is to use {packageID}-{version} as naming template for the eclipse projects. I used that and now in the workspace I have the old packages (e.g. pact-compiler) next to the new ones (e.g. pact-compiler-0.2-ozone).

**Comment by StephanEwen** [comment]
Fixed though Alexander's pull request in 35ff4dcd2ed84aa8711e4d3fea1caae622428457
