### ISSUE TITLE
BulkIteration member function is not implemented

### ISSUE THREAD

**Issue by lukacsg** [stratosphere/stratosphere#275]
The implementation of the "public void setTerminationCriterion(Contract criterion)" member function in BulkIteration class is missing.

<code>
public void setTerminationCriterion(Contract criterion) {
                throw new UnsupportedOperationException("Termination criterion support is currently not implemented.");
        }
</code>

https://github.com/stratosphere/stratosphere/blob/master/pact/pact-common/src/main/java/eu/stratosphere/pact/generic/contract/BulkIteration.java

**Comment by StephanEwen** [comment]
It is on the list for the coming release ;-) Until then, you can use
-  An absolute number of iterations, OR
-  The iteration aggregators to define a convergence criterion.

For the second option, have a look at the PageRank Example on how to use it:
-  An example aggregator (that collects many statistics about evolution of the solution): https://github.com/stratosphere/stratosphere/blob/master/pact/pact-examples/src/main/java/eu/stratosphere/pact/example/pagerank/PageRankStatsAggregator.java
-  An example convergence criterion: https://github.com/stratosphere/stratosphere/blob/master/pact/pact-examples/src/main/java/eu/stratosphere/pact/example/pagerank/DiffL1NormConvergenceCriterion.java
-  The creation of such an aggregator can be seen in the page rank plan construction (line 78) https://github.com/stratosphere/stratosphere/blob/master/pact/pact-examples/src/main/java/eu/stratosphere/pact/example/pagerank/DanglingPageRank.java#L78
-  The usage of the aggregator can be seen in the CoGroup that computes the new rank (lines 64 and lines 97-100)
  https://github.com/stratosphere/stratosphere/blob/master/pact/pact-examples/src/main/java/eu/stratosphere/pact/example/pagerank/DotProductCoGroup.java#L64

**Comment by lukacsg** [comment]
Thanks! We will wait for the next release, while we can't define a convergence criterion or give an absolute number of iterations this time implementing our entity resolution algorithms. Should we leave the issue open?

**Comment by StephanEwen** [comment]
Lets keep the issue.

I assume using the aggregators for convergence checking is not applicable to your algorithm?

**Comment by sidlo** [comment]
We will see; at first we thought that our loop invariant cannot be implemented as a convergence criterion, but checking it again, it might work!

(We first thought that as a ConvergenceCriterion we must provide a measure that decreases in every step, and in our case, there is no such a measure. However, we have a simple condition of termination.)

**Comment by markus-h** [comment]
The method is implemented in https://github.com/stratosphere/stratosphere/pull/472.

**Comment by rmetzger** [comment]
I'll close this issue once the PR is merged.
