### ISSUE TITLE
Bug in webinterface: Failed jobs don't disappear

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#276]
I was running a job that failed. It seems that the nephele does not properly cleans all internal data structures if a job fails:

![failed](https://f.cloud.github.com/assets/89049/1564975/753d1f4a-5077-11e3-91d6-c58caac4b986.png)

This status does not change even if I successfully submit the next job: I can not see the progress of this job, because the "dead" job still remains there.

**Comment by fhueske** [comment]
Just to get a bit more info on this issue:
- Can you consistently reproduce this bug with your job? 
- Do you know if that happens with any failing job?

**Comment by markus-h** [comment]
I did some investigation on this issue and the solution was very easy. Because of a small typo in the EventCollector failed jobs were not correctly removed from the recentJobs list.

**Comment by fhueske** [comment]
Can be closed, right?

**Comment by StephanEwen** [comment]
I think so.
Am 07.02.2014 10:28 schrieb "Fabian Hueske" notifications@github.com:
