### ISSUE TITLE
Simplify Program Template and Readme Stub

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#277]
I think we can simplify the Program Template (which is also shown in the Readme on the github start page) a bit. Would make it easier to parse for beginners.
-  We don't need the PlanAssemblerDescriptor. It is barely ever read (I know only of explicit calls in the web frontend and the command line frontend)
- Why have the local executor functionality split between main() and execute()? Make it one and use the static call that starts and stops the executor automatically.

The result would be much more consice and quite a bit nicer in my opinion:

``` java
public class Tutorial implements PlanAssembler {

    @Override
    public Plan getPlan(String... args) {
        // your parallel program goes here
    }

    public static void main(String[] args) throws Exception {
        Tutorial tut = new Tutorial();
        Plan toExecute = tut.getPlan(args);
        long runtime = LocalExecutor.execute(toExecute);
        System.out.println("Runime: " + runtime);
    }
}

```

**Comment by uce** [comment]
:+1:

**Comment by StephanEwen** [comment]
Done
