### ISSUE TITLE
Cluster Setup: Shared Directory is not required

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#287]
The Cluster Setup instructions in the Quickstart states that a shared folder is required for a cluster setup. This is not true. Although this is convenient for small setups, it might even cause problems for large setups (e.g., in case of extensive logfile writing...) and it prohibits custom configurations for individual nodes, e.g., in case of heterogeneous hardware / software setups...

The start and stop scripts only require that the Stratosphere folder is located at the same path on each node (which might not even be given with a shared folder as each node can mount it to any path).

**Comment by rmetzger** [comment]
Thank you. I'll include the fix into the pull request for the new front page. https://github.com/stratosphere/stratosphere/pull/283

**Comment by rmetzger** [comment]
Preview: http://robertmetzger.de/stratosphere/quickstart/setup.html

**Comment by fhueske** [comment]
Can you change the first bullet point to:

"1. Copy Stratosphere to the same file system path on each node of your setup,"

or similar?

**Comment by rmetzger** [comment]
Sure.
