### ISSUE TITLE
Job compilation fails due to missing commons packages

### ISSUE THREAD

**Issue by aalexandrov** [stratosphere/stratosphere#30]
The _commons-lang_ and _commons-configuration_ are missing from the classpath. 

In particular, _commons-configuration_ is required by _hadoop-core_ and thereby by _pact-runtime_, while _commons-lang_ is required by _commons-configuration_.

In order to solve the issue the appropriate lines for including _commons-configuration_ and _commons-lang_ to the classpath should be added to _pact-client.sh_, _nephele-jobmanager.sh_ and _nephele-taskmanager.sh_ (not sure about the last two).

**Comment by StephanEwen** [comment]
Fixed in 06ef78044b5a571b162b9cc4b65168adc1ec2573
