### ISSUE TITLE
Create "Material" section under "Project" on Stratosphere.eu

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#303]
We should create a site on our website that contain all external resources on stratosphere.

For example a svg and (hi-res) png logo + some more images, like the operators and stuff we use for our posters.
All slides that are on slideshare and google docs (and publicly linked)
Youtube videos

This is important for people that create their own slides about stratosphere.

4 people asked me to send them a hi-res stratosphere logo. So there is definitively a need!

**Comment by uce** [comment]
:+1:

Hopefully, we will also have a new logo soon.

**Comment by StephanEwen** [comment]
I have a logo in works with a professional designer...
Am 27.11.2013 18:38 schrieb "Ufuk Celebi" notifications@github.com:

**Comment by rmetzger** [comment]
Fixed by https://github.com/stratosphere/stratosphere/pull/447
