### ISSUE TITLE
Add Maven plugin to generate test coverage reports

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#305]
It would be good to have the option to generate test coverage reports for Stratosphere.
The Maven plugin for test coverage is called [Cobertura](http://mojo.codehaus.org/cobertura-maven-plugin/).

Maybe, the generation can be en/disabled by the profile mechanism such that it does not influence the usual build process.

**Comment by StephanEwen** [comment]
Fixed in 39ddc96d85e998838f191ff409dc968430c10e1a
