### ISSUE TITLE
FileInputFormat builder pattern cannot be used for GenericDataSources

### ISSUE THREAD

**Issue by AHeise** [stratosphere/stratosphere#309]
And since FILE_PARAMETER_KEY is now private, we cannot set the file path without hacks.

```
public static ConfigBuilder configureFileFormat(FileDataSource target) {
                return new ConfigBuilder(target.getParameters());
}
```

**Comment by rmetzger** [comment]
Hi @AHeise,

You have to use the `setFilePath()` method now to set the file path. But yes, the builder pattern looks broken.

The bug was introduced by https://github.com/stratosphere/stratosphere/pull/284.
I'm assigning this to @StephanEwen.

I'm also a bit unhappy with this change: https://github.com/stratosphere/stratosphere/commit/9dd4635ad69bf107ab9f81c8e7ffd495475471e0#commitcomment-4705847

**Comment by StephanEwen** [comment]
Does it help if the file input format builder accepts GenericDataSource?

In the long run, we want to refrain from the config based parameterization and simply pass parameterized objects. Not exposing the config keys are a step into that direction.

**Comment by AHeise** [comment]
Yes, that would be a valid option and probably the easiest fix.

---

Von: Stephan Ewen [notifications@github.com]
Gesendet: Dienstag, 3. Dezember 2013 19:42
An: stratosphere/stratosphere
Cc: Heise, Arvid
Betreff: Re: [stratosphere] FileInputFormat builder pattern cannot be used for GenericDataSources (#309)

Does it help if the file input format builder accepts GenericDataSource?

In the long run, we want to refrain from the config based parameterization and simply pass parameterized objects. Not exposing the config keys are a step into that direction.

**Comment by StephanEwen** [comment]
FileInputFormat builder accepts GenericDataSource in 162652326ef0d75f68ff35bc966676eedd91a89d

Does that work for you? If yes, please close the issue, otherwise let me know where it still breaks.

**Comment by StephanEwen** [comment]
I assume this problem is solved?
