### ISSUE TITLE
Merge "Spagel" - Stratosphere Pregel/BSP into main code line

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#310]
There is code to have an BSP-style interface for Graph processing with Stratosphere's iterations feature.

I suggest to call it "Spagel", for the following reasons:
- it sounds like s-pregel (stratosphere pregel)
- Spark named their Pregel-implementation bagel
- its a german word.

I would like to have this code merged into the project soon.
A master student is going do compare Stratosphere with Giraph, so we need that interface anyways.

**Comment by aljoscha** [comment]
What is "Spagel"?

**Comment by asteriosk** [comment]
I secretly hope it's this:
http://www.urbandictionary.com/define.php?term=spagel

No idea if this was the intention of Robert though!

**Comment by rmetzger** [comment]
Oh, now I'm getting it. I misspelled Spargel (http://de.wikipedia.org/wiki/Spargel).

We should still keep the name.

**Comment by aljoscha** [comment]
Which name? Spagel, the dirty sex thing. I'm in. :+1:

**Comment by uce** [comment]
I like both. Initially, I was for SpaRgel, but maybe Spagel is better -- easier to spell and the dirty & sexy pun. On the other hand, it might be too similar to Bagel.

One way or the another: I also think that it is important to have the API soon! :+1:

**Comment by ktzoumas** [comment]
Alternative name: Pregelsphere (but I do prefer Spargel)

**Comment by uce** [comment]
@StephanEwen I think you wrote the initial API for this. Can you say whether we can use it in the near future? I would be happy to look at it, implement some tests and extend it if necessary. :stuck_out_tongue_closed_eyes:

**Comment by StephanEwen** [comment]
Merged in f2657cca2b981c1ab1f685d45186896c51fb7676

It is called "Pregelsphere" now, but there are discussions to rename it to "Spargel" (Asparagus)

**Comment by uce** [comment]
I don't like "Pregelsphere". Could we discuss the name? I think most people were for Spargel or Spagel.

:+1: Spagel, because SpaRgel is quite hard to pronounce in English.

**Comment by ktzoumas** [comment]
I also like Spargel (for asparagus)

**Comment by sscdotopen** [comment]
+1 for Spargel

**Comment by rmetzger** [comment]
+1 for Spargel (I have to be for this name since I suggested it)

**Comment by uce** [comment]
OK, let's go with Spargel then. :+1:  I can do the renaming:
- Rename the Maven module from pregelsphere to spargel
- Rename the package from ...vertexcentric to ....spargel
- Rename example VertexCentrixCC to SpargelConnectedComponents

**Comment by StephanEwen** [comment]
Fixed in 696c8fe49dd644476014e9f1eea7c8832104efbb
