### ISSUE TITLE
Add integration tests for reopen-able hash join

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#32]
The iteration aware hash join needs thorough integration tests like the regular hash join.

**Comment by rmetzger** [comment]
I need some additional input for this task. I think i covered most of the situations in these tests already:
pact/pact-runtime/src/test/java/eu/stratosphere/pact/runtime/hash/ReOpenableHashTableTest.java

I can adopt some additional cases such as "testBuildFirstWithMixedDataTypes()" or "testBuildFirstWithHighNumberOfCommonKeys()" 
Or do you want a test in the "pact-tests" project that does a whole iterative task with the reopenable hash join?

**Comment by StephanEwen** [comment]
Please adopt some of the test from the HashTableITCase, especially the ones
that heavily spill and spill recursively. Make them do it trhee rounds.

Best,
Stephan

**Comment by StephanEwen** [comment]
Integrated in 42cdca4006f6f521f0e497732f7fda0295b01d7d
