### ISSUE TITLE
localhost:8081 

### ISSUE THREAD

**Issue by fhmt** [stratosphere/stratosphere#324]
hello friends, 

i am a beginner at stratosphere project, but i like to progress. i tested stratosphere project on local system but i have some problems: 

1- when i enter  localhost:8080 address, web interface  opened for me and i uploaded wordcount.jar example and click runjob , then the message is " successfully job submitted" and i get output. but after that i do not see anythings! i can not  see jabmanager interface , i enter address: localhost:8081 but no page loaded. how can i see job processing stage?

**Comment by rmetzger** [comment]
Hey,

cool that you are interested in the project!

Can you show me the first few lines in your JobManager log file?
The file is located under `logs/nephele-<username>-jobmanager-<hostname>.log`
The progress monitoring interface sometimes does not start if a) it can not find its files or b) the port is already in use.
But I'm sure the logfile will show us the exact reason.

Best,
Robert

**Comment by fhmt** [comment]
thank you very much because your quick reply....

21:51:56,995 INFO  eu.stratosphere.nephele.discovery.DiscoveryService            - Discovery service socket is bound to /127.0.0.1:7001
21:51:57,032 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
21:51:57,033 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6123: starting
21:51:57,033 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 2 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 3 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 1 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 4 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting job manager in LOCAL mode
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 6 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 5 on 6123: starting
21:51:57,034 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 7 on 6123: starting
21:51:57,387 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 536870912, used: 0)
21:51:57,390 INFO  eu.stratosphere.nephele.instance.local.LocalInstanceManager   - Default instance type is default
21:51:57,397 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
21:51:57,398 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be localhost/127.0.0.1:6123
21:51:57,400 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information 127.0.0.1 to job manager
21:51:57,416 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
21:51:57,416 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
21:51:57,416 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
21:51:57,448 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 2048 buffers with a size 32768 bytes each
21:51:57,457 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled and spilled buffer merging enabled
21:51:57,586 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 536870912, used: 0)
21:51:57,586 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 409 megabytes of memory
21:51:57,871 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Trying to load eu.stratosphere.nephele.jobmanager.scheduler.local.LocalScheduler as scheduler
21:53:20,003 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Creating initial execution graph from job graph WordCount Example
21:53:20,260 INFO  eu.stratosphere.nephele.executiongraph.ExecutionGraph         - Job input vertex Input Lines generated 2 input splits
21:53:20,295 INFO  eu.stratosphere.nephele.jobmanager.splitassigner.InputSplitManager  - Trying to load input split assigner for type FileInputSplit
21:53:20,297 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Scheduling job WordCount Example
21:53:20,300 INFO  eu.stratosphere.nephele.jobmanager.scheduler.AbstractScheduler  - Requesting the following instances for job 1048a12f8f841c004e49c0ee9eec0c00
21:53:20,301 INFO  eu.stratosphere.nephele.jobmanager.scheduler.AbstractScheduler  -  default (8,8,4096,1,0) [1, 1]
21:53:20,303 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Input Lines (1/2)
21:53:20,315 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Status of job WordCount Example(1048a12f8f841c004e49c0ee9eec0c00) changed to SCHEDULED
21:53:20,315 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Count Words (1/2)
21:53:20,315 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Word Counts (1/2)
21:53:20,315 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Count Words (2/2)
21:53:20,316 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Word Counts (2/2)
21:53:20,316 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from CREATED to SCHEDULED for task Input Lines (2/2)
21:53:20,316 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Input Lines (1/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Word Counts (2/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Word Counts (1/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Input Lines (2/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Count Words (2/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from SCHEDULED to ASSIGNED for task Count Words (1/2)
21:53:20,317 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Input Lines (1/2)
21:53:20,318 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Input Lines (2/2)
21:53:20,318 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Input Lines (1/2)
21:53:20,318 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Input Lines (2/2)
21:53:20,332 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Input Lines (1/2) on 127.0.0.1
21:53:20,332 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Input Lines (2/2) on 127.0.0.1
21:53:20,364 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Input Lines (1/2)
21:53:20,364 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Input Lines (2/2)
21:53:20,366 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Input Lines (1/2)
21:53:20,366 INFO  eu.stratosphere.pact.runtime.task.DataSourceTask              - Start PACT code: Input Lines (1/2)
21:53:20,366 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code: Tokenize Lines (1/2)
21:53:20,366 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code: Count Words (1/2)
21:53:20,367 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Status of job WordCount Example(1048a12f8f841c004e49c0ee9eec0c00) changed to RUNNING
21:53:20,367 INFO  eu.stratosphere.pact.runtime.task.DataSourceTask              - Start PACT code: Input Lines (2/2)
21:53:20,367 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Input Lines (2/2)
21:53:20,367 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code: Tokenize Lines (2/2)
21:53:20,368 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code: Count Words (2/2)
21:53:20,381 INFO  eu.stratosphere.nephele.jobmanager.splitassigner.file.FileInputSplitList  - 127.0.0.1 receives remote file input split (distance 2147483647)
21:53:20,382 INFO  eu.stratosphere.nephele.jobmanager.splitassigner.InputSplitManager  - Input Lines (1/2) receives input split 1
21:53:20,383 INFO  eu.stratosphere.nephele.jobmanager.splitassigner.file.FileInputSplitList  - 127.0.0.1 receives remote file input split (distance 2147483647)
21:53:20,383 INFO  eu.stratosphere.nephele.jobmanager.splitassigner.InputSplitManager  - Input Lines (2/2) receives input split 0
21:53:20,502 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code: Tokenize Lines (1/2)
21:53:20,503 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code: Tokenize Lines (2/2)
21:53:20,507 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code: Count Words (1/2)
21:53:20,507 INFO  eu.stratosphere.pact.runtime.task.DataSourceTask              - Finished PACT code: Input Lines (1/2)
21:53:20,507 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Input Lines (1/2)
21:53:20,508 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Input Lines (1/2)
21:53:20,510 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code: Count Words (2/2)
21:53:20,510 INFO  eu.stratosphere.pact.runtime.task.DataSourceTask              - Finished PACT code: Input Lines (2/2)
21:53:20,510 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Input Lines (2/2)
21:53:20,511 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Count Words (1/2)
21:53:20,511 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Count Words (1/2)
21:53:20,511 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Input Lines (2/2)
21:53:20,512 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Count Words (1/2) on 127.0.0.1
21:53:20,520 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Count Words (1/2)
21:53:20,521 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Count Words (1/2)
21:53:20,521 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Count Words (1/2)
21:53:21,018 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Count Words (2/2)
21:53:21,019 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Count Words (2/2)
21:53:21,021 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Count Words (2/2) on 127.0.0.1
21:53:21,026 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Count Words (2/2)
21:53:21,028 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Count Words (2/2)
21:53:21,028 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Count Words (2/2)
21:53:21,055 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Word Counts (1/2)
21:53:21,055 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Word Counts (1/2)
21:53:21,056 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Word Counts (1/2) on 127.0.0.1
21:53:21,059 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Word Counts (1/2)
21:53:21,060 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Word Counts (1/2)
21:53:21,060 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Word Counts (1/2)
21:53:21,545 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from ASSIGNED to READY for task Word Counts (2/2)
21:53:21,545 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from READY to STARTING for task Word Counts (2/2)
21:53:21,547 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Starting task Word Counts (2/2) on 127.0.0.1
21:53:21,553 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Word Counts (2/2)
21:53:21,555 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from STARTING to RUNNING for task Word Counts (2/2)
21:53:21,555 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Word Counts (2/2)
21:53:21,560 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Count Words (1/2)
21:53:21,560 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Count Words (1/2)
21:53:21,562 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Count Words (1/2)
21:53:21,588 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Finished PACT code: Word Counts (1/2)
21:53:21,589 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Word Counts (1/2)
21:53:21,590 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Word Counts (1/2)
21:53:21,590 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Word Counts (1/2)
21:53:21,592 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Word Counts (1/2)
21:53:21,662 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Count Words (1/2)
21:53:21,663 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Count Words (1/2)
21:53:22,050 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Count Words (2/2)
21:53:22,050 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Count Words (2/2)
21:53:22,051 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Count Words (2/2)
21:53:22,065 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Finished PACT code: Word Counts (2/2)
21:53:22,065 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Word Counts (2/2)
21:53:22,066 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from RUNNING to FINISHING for task Word Counts (2/2)
21:53:22,066 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Word Counts (2/2)
21:53:22,067 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Word Counts (2/2)
21:53:22,122 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Input Lines (1/2)
21:53:22,123 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Input Lines (2/2)
21:53:22,124 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Input Lines (1/2)
21:53:22,126 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Input Lines (2/2)
21:53:22,152 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from FINISHING to FINISHED for task Count Words (2/2)
21:53:22,153 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - JM: ExecutionState set from FINISHING to FINISHED for task Count Words (2/2)
21:53:22,153 INFO  eu.stratosphere.nephele.jobmanager.scheduler.AbstractScheduler  - Releasing instance 127.0.0.1
21:53:22,156 INFO  eu.stratosphere.nephele.jobmanager.JobManager                 - Status of job WordCount Example(1048a12f8f841c004e49c0ee9eec0c00) changed to FINISHED

Best Regards,
Fahimeh

**Comment by rmetzger** [comment]
Hey,

which version of Stratosphere are you using? It looks to me like this version is a bit older.
The version you have does probably not include the web interface!
But I can tell you from the log files that the wordcount example did run successfully.

Robert

**Comment by fhmt** [comment]
first of all i have downloaded ozone-master version and after that downloaded stratosphere version at address : stratosphere.eu but none of them did not work correctly, and job could not submitted. so i download stratosphere.box and i worked with vagrant command. 
how to can access to job manager web interface? What should I do??

**Comment by rmetzger** [comment]
What operating system are you using?

If you have Linux or Mac, the version at Stratosphere.eu should work.
For Windows, I'm not sure.

The virtual machine images are not updated so often, sorry.

You can also try to update the version inside the virtual machine

Sent from my iPhone

On 08.12.2013, at 14:55, fhmt notifications@github.com wrote:

first of all i have downloaded ozone-master version and after that
downloaded stratosphere version at address : stratosphere.eu but none of
them did not work correctly, and job could not submitted. so i download
stratosphere.box and i worked with vagrant command.
how to can access to job manager web interface? What should I do??

—
Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/issues/324#issuecomment-30082036
.

**Comment by StephanEwen** [comment]
I agree with Robert, it seems you have an old version. The 'ozone-master' version was a branch that went into the mainline months ago, so something seems to be off there. Can you tell me where you downloaded that version?

The version from the web-site (http://dopa.dima.tu-berlin.de/bin/stratosphere-0.4-SNAPSHOT.tgz) should have a rather recent build. Which one did you use?

**Comment by StephanEwen** [comment]
I just downloaded the version from the web-site (http://dopa.dima.tu-berlin.de/bin/stratosphere-0.4-SNAPSHOT.tgz) and started it locally. On the Ubuntu Linux x64, the webinterface was at localhost:8081. 

Which OS are you using?

**Comment by fhmt** [comment]
i am using windows 7 and cygwin terminal.

**Comment by fhmt** [comment]
my problem is solved. 

thanks.
