### ISSUE TITLE
JobManager webinterface does not work with YARN Tracking UI Proxy

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#325]
YARN's web interface allows to track the application master using a special tracking url.
It is a proxy that routes the requests to the right container (that of the application master).
Since the request urls of the web interface are somewhat hard coded. Currently the ajax requests look like `/jobsInfo` but the proxy urls look like `http://localhost:8088/proxy/application_1386532236961_0001/`

**Comment by markus-h** [comment]
What do you mean by application master? So if I understand it right, the webinterface should be accessible when using a proxy, for example by using http://localhost:8088/proxy/application_1386532236961_0001/jobsInfo? So we'd need a new configuration value on the client side to specify a proxy url.

**Comment by rmetzger** [comment]
This picture explains what the application master is in the yarn context:
https://f.cloud.github.com/assets/5525371/1298189/1ac85602-30f0-11e3-9fd5-cd3993b38ce3.png

So its basically a Jvm that runs the JobManager with some yarn management stuff.

> So if I understand it right, the webinterface should be accessible when using a proxy, for example by using http://localhost:8088/proxy/application_1386532236961_0001/jobsInfo? 

Exactly!

Do you think it is possible to do this without an additional configuration value? I mean I'm sure that it is possible to find out the current url?
There should be a standard solution to that problem? http://stackoverflow.com/questions/4765740/relative-urls-in-ajax-requests ?

Probably changing `/jobsInfo` to `jobsInfo` should do the job?

**Comment by fhueske** [comment]
@rmetzger did you resolve this issue in 02f6328c09723afa0ce9a3e9bec6b72080aaa74a?

**Comment by rmetzger** [comment]
This issue is not resolved.
The JobHistory link to the analzye page is still hardcoded and not compatible to yarn's proxy!

**Comment by rmetzger** [comment]
I fixed the issue with commit: 5300f4b4b4cfdb00edbd5b4e87721640b0c7dc0c
