### ISSUE TITLE
scheduling algorithms

### ISSUE THREAD

**Issue by fhmt** [stratosphere/stratosphere#328]
Hi

i am a master student. my thesis is about stratosphere project . i have a question from all friends, my question is about scheduling at stratosphere project. i want to know more about scheduling algorithms. i know that the default scheduling at stratosphere is FIFO scheduler. Can be added  another scheduling algorithms for example real time scheduling or fair sharing scheduling to stratosphere project? my thesis topic is to add the new job scheduler to stratosphere project according to PACT programming model (map, reduce, match,cogroup,...)  

in your opinion, Whether it is implementable?

Best Regards,
Fahime

**Comment by rmetzger** [comment]
Hi Fahime,

lets discuss this on the mailing list. I'm already working on an answer there ;).

Best,
Robert

**Comment by fhmt** [comment]
ok , thanks Robert
