### ISSUE TITLE
Stratosphere setup documentation lacks description of temp dirs

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#347]
The setup documentation lacks the description of the temp dir configuration parameter (taskmanager.tmp.dirs). 
This is an important parameter for systems with more than one disk as temp I/O is equally distributed over multiple disks.

**Comment by aalexandrov** [comment]
I agree that taskmanager.tmp.dirs is an important configuration parameter, but I fear that we might pollute the quick start with too much information for a novice user. 

I would rather keep performance tuning aspects in the full version of the configuration documentation which (hopefully) should be read by people who want to move to performance-critical environment.

**Comment by fhueske** [comment]
Good point.

I think we need this separation between "getting quickly familiar" and "extensive feature description" also for the programming APIs. That would split the whole documentation into two parts. 

Any thoughts on that?

**Comment by StephanEwen** [comment]
Please take a look here:
https://github.com/StephanEwen/stratosphere/blob/rename/stratosphere-core/src/main/java/eu/stratosphere/configuration/ConfigConstants.java

These are the unified config constants that should be listed in the
configuration reference. All others are, I think, obsolete (either not
supported any more, or should not be exposed).

Let me know if the ConfigConstants are missing something.

**Comment by fhueske** [comment]
I added the configuration of temp directories to the cluster setup (not the quick start).
See PR #353.

I'll open a new issue for the update of the configuration page.
