### ISSUE TITLE
Not all JobClient ctors initialize accumulatorProtocolProxy

### ISSUE THREAD

**Issue by AHeise** [stratosphere/stratosphere#349]
Leads to NPE during job execution.

**Comment by andrehacker** [comment]
Thanks @AHeise for reporting, I will look into this now and I already see the constructor which is missing the initialization.
Not sure when this is called (would like to cover via testcase) - do you know how to reproduce?

**Comment by AHeise** [comment]
I use it in sopremo-testserver SopremoServerIT#testSuccessfulExecution. 

But it should be a copy and paste fix. You could also direct the second ctor to the third ctor and build the last param from the config.

**Comment by andrehacker** [comment]
Yes, the fix is one line, I will do it as proposed.

**Comment by AHeise** [comment]
Also you could make the proxy final, than the error would be reported by the compiler. (good advertisement for using finals wherever possible ;))

**Comment by StephanEwen** [comment]
Fixed in PR4
