### ISSUE TITLE
java quickstart "one of the following" is misleading

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#351]
http://stratosphere.eu/quickstart/java.html

"Use one of the following commands to create a project:"

and then there is 1. and 2.
but people don't read the sentence.
Two of the new stratosphere commiters ran into the problem.

**Comment by aalexandrov** [comment]
I have a fix for this. Should be pushed on my fork in ~ 5 mins if the asymmetric DSL gods are with us.

**Comment by aalexandrov** [comment]
I just noticed that now all the description on the quickstart is withing a p.lead. Do we want to keep it like that - my understanding is that the .lead class should be used for first sentences only.

**Comment by uce** [comment]
Your understanding is right. It was just a matter of "style" to make the text bigger for this special page, because (imho) the font size doesn't work well for short texts.

**Comment by aalexandrov** [comment]
I agree that the normal text size feels too small compared to the headers and leads, but if we use the .lead class things shift too much in the other directions (at least on my screen) - it looks as if you're shouting the instructions with large letters (especially as the text in the other section is smaller).

If we all agree that this the normal text size is a bit too small I think the appropriate way to fix this is to redefine the text-size css attribute in bootstrap.css.

Should I open an issue for that?

**Comment by rmetzger** [comment]
@aalexandrov: I agree with you that the font size in the quickstart is a bit too large.
The http://stratosphere.eu/downloads/ page uses the `lead`-class appropriately (probably still a little bit too much).

On the other hand, we should make sure that the pages look friendly (not like large text blocks you've to work through). I think this was Ufuk's intention and he did a good job!
