### ISSUE TITLE
Create a large Job to test all components

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#379]
The implementation of several Stratosphere Jobs at a company has shown that there are some minor bugs that occur when using plans with many operators. We can not use the plan from the company due to NDA restrictions.

The goal with this task is to implement a large stratosphere plan that contains all operators and features.
- Map, Join, Cross, CoGroup, Reduce, Union, Iterations
- Keyless reducer
- join with hash, join with sort
- CsvInputFormat, TextInputFormat
- write to hdfs and local file system (distributed!)
- JDBC IF/OF
- some operators with hardcoded DOP's
- operators with annotations/compiler hints.
- aggregators

Obviously, all these elements can't be used in a plan that does anything meaningful. I suggest to use the TPC-H data generator.

Bugs I want to cover:
- deployment issues (class loader)
- distributed file access
- the start/stop, submission tools
- dependency/rpc incompatibility issues (hdfs/hadoop versions)
- Compiler bugs (seem to happen with large/complex plans)
- Performance regressions (major performance issues should be detectable)
- Deadlocks/concurrency issues

Ideally, the job should be executed nightly on our OpenStack environment, testing the EC2 scripts, our scripts and the whole system.
I hope to find somebody inside TU that will take care of the automation and reporting.

The code probably fits best here: https://github.com/stratosphere/stratosphere-testing (see https://github.com/stratosphere/stratosphere-testing/issues/2)

A new student in the Stratosphere team ( @twalthr ) is going to implement this.

**Comment by twalthr** [comment]
While implementing the test I had some difficulties using the Java API: 

I wanted to concatenate the fields of two records in a join. Unfortunately, the existing `Record.concatenate()` function is not implemented and throws a `UnsupportedOperationException`. At moment I concatenate using the following lines, but this is quite inconvenient

```
Record newRecord = new Record(c.getNumFields() + n.getNumFields());

int[] cPositions = new int[c.getNumFields()];
for (int i = 0; i < cPositions.length; ++i) {
    cPositions[i] = i;
}
newRecord.copyFrom(c, cPositions, cPositions);

int[] nPositions = new int[n.getNumFields()];
int[] targetNPositions = new int[n.getNumFields()];
for (int i = 0; i < nPositions.length; ++i) {
    nPositions[i] = i;
    targetNPositions[i] = i + cPositions.length;
}
newRecord.copyFrom(n, nPositions, targetNPositions);
```

Is there a better way to do it?

**Comment by rmetzger** [comment]
@StephanEwen: Why is there a `Record.concatenate()` function that throws a `UnsupportedOperationException` ?

**Comment by twalthr** [comment]
Again I have problems in using the Java API. Is there any easy way to check two records for equality? `Record.equals()` is not implemented and `Record.equalsFields()` would require to specify all field types again and many additional lines of code for its parameters.

**Comment by rmetzger** [comment]
The large test job is now in a private repository.

**Comment by twalthr** [comment]
Actually, test job is not fully tested in environments with DOP>1.

**Comment by StephanEwen** [comment]
The latest master has fixes for the issues you reported: all reducer in
iterations, not fully reading the reducer input, cost overflow for high
number of max iterations.

can you pull the latest changes and see if it works?
Am 07.02.2014 10:26 schrieb "twalthr" notifications@github.com:

**Comment by twalthr** [comment]
There was another problem. But I had no time yet for further investigation (if it is a problem of the plan or stratosphere), I will try to test the job with the latest master...
