### ISSUE TITLE
Release 0.4.1 Planning

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#395]
With this issue, I want to plan the first bugfix release in the 0.4 line.

List of pull requests and commits for 0.4.1.
- `start-local.bat` fix for paths with spaces https://github.com/stratosphere/stratosphere/pull/394
- NPE in Scala interface https://github.com/stratosphere/stratosphere/pull/409
- improved error message in spargel/iterations https://github.com/stratosphere/stratosphere/pull/432
- fix in execution graph test https://github.com/stratosphere/stratosphere/pull/420
- NPE in Scala interface (commit: eedfe1e0e5598630dd446e89db4c68d122f3d32a) reporting issue: https://github.com/stratosphere/stratosphere/issues/434
- Tests failing with non-us locale https://github.com/stratosphere/stratosphere/issues/416 f17ccfb52eac786497dd2a7d150f5e361cfca5b1
- YARN URL fix: 5300f4b4b4cfdb00edbd5b4e87721640b0c7dc0c
- dist-binary fix: 00676c56a875a987ce23371c1665e7d28c1f46ee, travis fix: 82542d68edd5999cd7cd8330bb7a3b19852b8eb6

**Comment by fhueske** [comment]
- Configurable write modes for FileDataSink: #421
- fix for distributed writing to local FS: #421
- improved YARN package #485

**Comment by StephanEwen** [comment]
Subsumed by 0.5 release planning.
