### ISSUE TITLE
Rename LocalDistributedExecutor.startNephele to something without nephele

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#397]

**Comment by fhueske** [comment]
I propose `startStratosphere()` or `startInstances()`.

**Comment by aalexandrov** [comment]
+1 for `startStratosphere()` or `startSystem()` or just `start()`

**Comment by uce** [comment]
:+1: for `start()`.

**Comment by uce** [comment]
Renamed to `start()` in #407.
