### ISSUE TITLE
Generated quickstart job fails with IndexOutOfBounceException

### ISSUE THREAD

**Issue by RobertBuhren** [stratosphere/stratosphere#401]
A full log can be found here:

http://pastebin.com/ZqiMwS0n

**Comment by StephanEwen** [comment]
Hmmm, looks like a problem in the ContextChecker. Could you please check whether:
- It is actually a bug in the ContextChecker (it reports a problem where there is none)
- Or whether the job really has a problem. In that case, please give it a better error message

**Comment by fhueske** [comment]
I'm having a look at that right now.

**Comment by fhueske** [comment]
OK, the quickstart contains two job classes. An empty template called Job.java and the Wordcount Example job (WordCountJob.java).

The MANIFEST file of the jar file points to the job that is executed by default, which in case of the Quickstart project is the incompletely implemented Job.java. Therefore, the execution fails.

Other jobs than the default job, can be executed using the `--class` option of the CLI client. 

```
 ./stratosphere run -j ~/quickstart/target/quickstart-0.1.jar 
                           -c eu.stratosphere.quickstart.WordCountJob 
                           -a file:///path/to/input file:///path/to/output 1 
                           -w
```

See the [CLI Interface Documentation](http://stratosphere.eu/docs/0.4/program_execution/cli_client.html) for details.
