### ISSUE TITLE
Change title of website start page

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#411]
Google shows the title of the start page in is search results.
For stratosphere.eu that is currently: 
"Stratosphere >> Overview"
which is not telling anything.

I propose to change the page title to:
"Stratosphere - Big Data looks tiny from here"
or
"Stratosphere - Next Generation Big Data Analytics"

Google's more detailed explaining text is also not well chosen and should be updated. Currently it is:
"Stratosphere extends the well-known MapReduce model with new operators. These operators represent many common data analysis tasks more naturally and ..."

**Comment by uce** [comment]
I agree and I've pushed the following changes:

Title from _Overview_ to _Next Generation Big Data Analytics Platform_.

The _description_ metatag is now the same as the first paragraph of the startpage:

> Stratosphere is the next generation Big Data Analytics Platform. It combines the strengths of MapReduce/Hadoop with powerful programming abstractions in Java and Scala and a high performance runtime. Stratosphere has native support for iterations, incremental iterations, and programs consisting of large DAGs of operations."

**Comment by fhueske** [comment]
Well, actually Google ignores the description meta tag if it is identical on most pages of the website.
That's why I extracted it. Will rebase and update my PR.

**Comment by uce** [comment]
OK, thanks! :-)
