### ISSUE TITLE
Test in stratosphere-runtime creates directories and does not clean up

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#419]
After running `mvn clean install` in stratosphere-runtime, remain are five empty directories in the `./stratosphere-runtime/` with random names such as `./stratosphere-runtime/e9d591287b472593.dat`.
All tests ran successfully.
Maven reports `BUILD SUCCESS` and `Tests run: 65, Failures: 0, Errors: 0, Skipped: 0`.

Tests should properly clean up their setup.

**Comment by fhueske** [comment]
The test which is responsible for the directories is:

`eu.stratosphere.nephele.executiongraph.ExecutionGraphTest`

**Comment by StephanEwen** [comment]
Good discovery. Do you have a handle to a fix already?

**Comment by fhueske** [comment]
I had a look. The output directories of some tested tasks are not deleted.
The output paths are known, so cleaning up should be easy.

Will push a fix soon.
