### ISSUE TITLE
Use Iterable instead of Iterator for the messages in Spargel (cosmetic)

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#425]
Spargel provides an Iterator over the messages. Iterables are more handy as they allow for loops.

**Comment by StephanEwen** [comment]
Can we do an IterableIterator? One that is both, returning 'this' on the
'getIterator()' call?

Spargel provides an Iterator over the messages. Iterables are more handy as
they allow for loops.

—
Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/issues/425
.

**Comment by sscdotopen** [comment]
I think in our case this should be fine, people would not expect to be able to create two different iterators from the messages.

**Comment by rmetzger** [comment]
Fixed with PR https://github.com/stratosphere/stratosphere/pull/433
