### ISSUE TITLE
DecimalTextIntParser has no static method that simply returns an int

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#427]
DecimalTextIntParser has no static method that simply returns an int (in contrast to DecimalTextLongParser). That makes it hard to use.

**Comment by StephanEwen** [comment]
I agree, we should add this.

**Comment by fhueske** [comment]
Some of the other parsers are also lacking a static method.

**Comment by StephanEwen** [comment]
Fixed in a1555ce84ae47edb8cd696f672935cbeffd3481b
