### ISSUE TITLE
Implement HadoopDataSink into hadoop-compatibility package

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#455]
The `HadoopDataSink` is similar to the `HadoopDataSource`. 
See here for an example: https://github.com/stratosphere/stratosphere/blob/master/stratosphere-addons/hadoop-compatibility/src/main/java/eu/stratosphere/hadoopcompat/example/WordCount.java#L117 and the issue: https://github.com/stratosphere/stratosphere/issues/382

We also need a  `HadoopDataSink` that supports any kind of Hadoop-OutputFormat for Stratosphere.

API Example:

``` java
HadoopDataSink out = new HadoopDataSink(new SequenceFileOutputFormat<LongWritable, Text>(), "Write SequenceFile");
SequenceFileOutputFormat.setOutputPath(out.getJobConf(), new Path(output));
```

**Comment by rmetzger** [comment]
Hey @qmlmoon, have you started working on this task? Is the work in progress somewhere in GitHub? Somebody on the mailing list was asking for this: https://groups.google.com/d/msg/stratosphere-dev/qYvJRSoMYWQ/zPf_nGHp_M0J

**Comment by qmlmoon** [comment]
I push it to my Github. HadoopDataSink works in local mode for hadoop 1.2.1. Still need to delete temporary directory generated by hadoop and test cluster mode.
