### ISSUE TITLE
Fix tests failing with java 8

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#457]
Oracle is planning to announce Java 8 in March this year.
Stratosphere does currently not work with Java 8.

Someone should look into the issues and fix them until then. We should be prepared for this event if early adopters are using the new Java on their deskop systems for development.

**Comment by zentol** [comment]
I'll look into this.

**Comment by rmetzger** [comment]
Amazing!

**Comment by zentol** [comment]
i changed a few things and it compiles now on linux (at least for me),
would be nice if someone else could try this:

https://github.com/zentol/stratosphere/tree/java8

**Comment by rmetzger** [comment]
Let travis do the job.
You can add java8 to the `.travis.yml` file (See http://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/).
Then, open a pull request and it will test everything
