### ISSUE TITLE
Add warning box to pre-0.4 documentation + update link to mailinglist

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#458]
Hi,
two minor issues: 
1) Some documentation pages from the pre-0.4 documentation rank high on google, therefore, some users are confused about the mismatch. We should have a orange or red box on to of each pre-0.4 page that warns users and tells them that the documentation is for an old version.

2) I created a users-mailinglist. There are links to our current mailinglist on the front-page and on the contacts page.
They should now point to https://groups.google.com/forum/#!forum/stratosphere-users
(However, the stratosphere-dev list should be mentioned too)

**Comment by uce** [comment]
1) http://stratosphere.eu/docs/pre-0.4/

**Comment by uce** [comment]
2) http://stratosphere.eu/index.html and http://stratosphere.eu/contact.

**Comment by rmetzger** [comment]
Wow. I like the warning! Thanks for updating the links.
