### ISSUE TITLE
Implement new Java API for Stratosphere

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#463]
The Stratosphere team is going to implement a new Java API. We will keep the old java API, calling it the "java-record-api".

This issue is for planning and discussion of the new API. I will update it if new requirements come in.

@StephanEwen is going to lead the implementation effort. (Current working branch https://github.com/StephanEwen/stratosphere/tree/japi) (See the examples https://github.com/StephanEwen/stratosphere/blob/japi/stratosphere-examples/stratosphere-java-examples/src/main/java/eu/stratosphere/example/java/wordcount/WordCount.java)

**Requirements**:
- Support for any java object as types.
- a typesafe tuple-model.
- Predefined aggregations for sum, min, max etc.
- Key-extraction using an extractor function.
- A more fluent program description that feels native to java developers (a DataSet model, rather than a dataflow-model)
- reduce-function that returns the reduce-key

We are planning to implement more features. These requirements are just for the first version.

**Timeline**:
- New Java API is the main new feature of Release 0.5
- First working prototype: week of 17. Feb.
- 0.5 Release Candidate 1: 7. March 2014.

**Comment by sscdotopen** [comment]
Why not throw away the old API? Keeping it only creates legacy that needs
to be maintained.
Am 08.02.2014 16:45 schrieb "Robert Metzger" notifications@github.com:

**Comment by rmetzger** [comment]
I think we are going to throw it away once the new API is stable and adopted. Since the new API is in a separate package, we can change the quickstarts and the documented maven dependencies so that new users don't see the old one. 

But I think we have to keep it for a few months. The new API will probably also be a bit slower since it takes us a while to implement sophisticated object serialization with codegen etc. Therefore, "high performance" users can choose the record-api as an option.
We just need to make sure that we do not end up in the `mapred`, `mapreduce`-hell ;)

UPDATE: I deleted the other part of the message again. I should think before posting ;)

**Comment by sscdotopen** [comment]
If highend users choose the old api, you _cannot_ throw it away
afterwards...
Am 08.02.2014 16:59 schrieb "Robert Metzger" notifications@github.com:

**Comment by StephanEwen** [comment]
I think there is not really a problem here for the following reasons:
1. I expect that the new api will not be slower than the record api, if
   used in a similar way, i.e. a tuple-like fashion with our own value types.
   On the contrast, I expect it to be faster even. In that sense there should
   be no reason to stick with the record api, at least not performance wise.
2. The support for java's core types and arbitrary objects may have a
   certain overhead due to immutable objects and general purpose
   serialization. Since that is a new feature, it is up to users to make a
   decision for productivity at the price of a bit of performance.
   1. I think we will keep the old api for a while and make it clear that
      there will be no more features added to it. Almost all the maintenance we
      had to do in the last weeks was concerning the generic components that both
      the old and new api will build on top of.

**Comment by uce** [comment]
What will happen with the array data model addon with the next release?

**Comment by StephanEwen** [comment]
I think the array data model will be removed. It was an experiment to see how other data models work with the optimizer and to address some shortcomings in the record data model.

The new java api solves that better, though.

**Comment by StephanEwen** [comment]
The new API is in the master branch now. Several issues exist for detailed features there.
