### ISSUE TITLE
Create tgz-bundle for Stratosphere-YARN with nice scripts and examples

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#473]
See https://github.com/stratosphere/stratosphere/pull/470

**Comment by fhueske** [comment]
The YARN bundle should be created by defining a new Maven assembly in stratosphere-dist (or extending the current yarn assembly).
The assembly should contain:
- the uber jar in ./lib
- the standard YARN config in ./conf
- a bash script to start (and stop?) a YARN cluster, and a bash script to submit a job to the YARN cluster in ./bin.
- all example jar files in ./example
- the README, LICENCE, NOTICE files in ./

Furthermore, the current uber jar needs to be adapted. For example, the current jar creates a default config on its first invocation. This is no longer required as the config is shipped in the archive file.

**Comment by rmetzger** [comment]
I'm on it: https://github.com/rmetzger/stratosphere/tree/yarnImprovements
