### ISSUE TITLE
Exceptions on TaskManagers (usercode, input formats etc) are not displayed in the JobManager log

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#482]
The JobManager log file should contain the exceptions of a failing task. 

This is currently only possible by starting a job using the `-w` argument of the stratosphere client.
The exception should always be in the JobManager log file!

**Comment by ghost** [comment]
hello, 

I would like to work on this and provide a patch.

**Comment by rmetzger** [comment]
Cool.
I would suggest to take the wordcount example and throw a Runtime Exception in the mapper. Then, run the Job on a cluster with the `-w` option. You'll see your exception.
As a next step, start a _distributed_ Stratosphere cluster (e.g. not  `start-local.sh`). Running the job again (without `-w`) will also fail the job, but this time, you won't see your Exception in the jobmanager log file, only in one of the taskmanager's log files (or in all TMs).

It would be great if the exception is also shown in the JobManager log file. As a awesome bonus, we would also like to show the Exception in the JobManager's webinterface (on port 8081). Once you've managed to fix the first issue, the webinterface thing will be easy.

**Comment by StephanEwen** [comment]
The exceptions are already reported from task manager to the job Manager,
which forwards them to the client (and in -w Mode, the client prints the
exception).

If you can find the point where the job manager stores the exception for
the jobclient to pull the status (and the exception), you probably have a
good point to start. Logging it is most likely a quick fix then, forwarding
the exception to the web Frontend would be a very nice addition!

**Comment by StephanEwen** [comment]
This was fixed as part of #688 (https://github.com/stratosphere/stratosphere/pull/688/files#diff-0808a97b4666fab09f9746c60e4a9b36R669)
