### ISSUE TITLE
Display Exceptions in the JobManager webinterface

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#483]
Currently, users have to scan through the log files to understand why a job has failed.

The web interface should show the exception of a failed job to ease debugging (Because these exceptions are usually quite helpful).

This enhancement depends on a fix for https://github.com/stratosphere/stratosphere/issues/482.

**Comment by qmlmoon** [comment]
Is #482 fixed?

**Comment by StephanEwen** [comment]
Fixed by #688 in a2650c5749d1c3eba40364123d397fdafbcf30e4
