### ISSUE TITLE
Add Apache Rat-based license checking to maven

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#494]
http://creadur.apache.org/rat/

**Comment by zerolevel** [comment]
Hi rmetzger,
I have added the rat repository.
But it points to unavailable licenses in many files.
Should I create this push by adding licenses to them all ?  
Or just add the apache-rat(dependency and the plugin information) details in pom.xml ?

**Comment by StephanEwen** [comment]
If you could create a pull request that adds the missing licenses, that'd
be great :-)
Thanks a lot!

**Comment by rmetzger** [comment]
Hi,
cool that you've started working on the issue.

Have a look how Apache Giraph is integrating it (https://github.com/apache/giraph/blob/release-1.0/pom.xml).
They include it into the `verify` phase, so that a build will fail if it does not have the appropriate license headers. As you can see there, they exclude some directories. You should do that too where it makes sense (for example `target/` directories, the readme etc.)

And yes, please add the headers to files where it is missing. I would like to have a pull request where the plugin is added + the checks are passing.

**Comment by zerolevel** [comment]
hi stephan and rmetzger,

Please find the PULL request for this issue.

https://github.com/stratosphere/stratosphere/pull/546

Waiting to hear from you regarding this.

Mohit.

**Comment by zerolevel** [comment]
To check if RAT plugin works use the following command

 mvn org.apache.rat:apache-rat-plugin:check

**Comment by zerolevel** [comment]
Hii.
I have edited it as suggested by you.
I think this is ready to be merged now. ;)

**Comment by zerolevel** [comment]
Hi robert,

Can you give me some tasks from the sql repository you are working on. I would be happy to do them and get some experience.

Thanks.
Mohit

**Comment by rmetzger** [comment]
Hi,

sure. Help is always very welcome. Have a look at this issue here: https://github.com/rmetzger/stratosphere-sql/issues/3
I outline three possible tasks.
Make sure you coordinate with @camelia-c (via the comments there) so that you do not work at the same stuff.

Please tell me if you want more suggested tasks

**Comment by rmetzger** [comment]
Resolved in https://github.com/stratosphere/stratosphere/pull/546. Thanks!
