### ISSUE TITLE
Bleeding menu on Downloads and Documentation web pages

### ISSUE THREAD

**Issue by nullusDefectus** [stratosphere/stratosphere#504]
This is probably low priority, but I notice that the menu in the left sidebar on the Downloads and the Documentation page bleeds on to content when the page is scrolled down.

The page is responsive for the most part, except when I dock the page left/right on the screen. Notice that the menu isn't collapsed to the right-hand top corner of the page as it should.

My monitor is 24" set to 1920x1080 (native) resolution. I am running Chrome "33.0.1750.117 m" on Windows 8.1. 

![image](https://f.cloud.github.com/assets/6477490/2264720/00640024-9e76-11e3-945d-3e0f2c1eb363.png)

**Comment by uce** [comment]
Thank you for posting this. I will look into it after I'm back from holidays, if nobody else finds the time.

I think the left sub navigation needs a proper fix, where it collapses earlier and for the top navigation we should think about moving some links to a dropdown, for example Events and Contact to the existing Project dropdown?

**Comment by rmetzger** [comment]
Thanks for reporting the issue. I fixed it in commit: 3cf916d3b1083177fbd22474de4263e76df3106e

**Comment by nullusDefectus** [comment]
Thanks @rmetzger.

I notice a minor problem with the fix. When the screen is narrow and the left menu is collapsed, everything looks fine, but not when the left menu is expanded, about a half of the first entry in the left menu is hidden. I believe the difference is the changing height of the top menu, illustrated below with four different screen (progressively smaller) widths.

## Screen wide enough for full top-menu

![image](https://f.cloud.github.com/assets/6477490/2304108/6cd062a2-a204-11e3-8eb6-c048cd937acb.png)

## Narrower screen, but top menu not yet collapsed

![image](https://f.cloud.github.com/assets/6477490/2304109/83dd3830-a204-11e3-8785-5076a3cb1186.png)

## Even narrower screen (~20%?), top menu not yet collapsed

![image](https://f.cloud.github.com/assets/6477490/2304113/9bc2f0a2-a204-11e3-9188-fcba43d006b4.png)

## Screen narrow enough for top menu to collapse

![image](https://f.cloud.github.com/assets/6477490/2304114/bb56d9a6-a204-11e3-9db7-246f54dc63e4.png)

**Comment by rmetzger** [comment]
Hi, thanks for your feedback.
I'll ask somebody to fix the remaining issues with the website.

**Comment by nullusDefectus** [comment]
I notice a couple of other issues, but I will wait for the currently known issues to be fixed. 

A quick question: What is the expectation for the web site? Is it expected to be responsive among desktops, tablets, and phones? For example, I see a couple of issues when viewed from my tablet, but I don't want to report them if that is not a priority. Also, I can conserve the time it takes me to understand and document the problems.

**Comment by rmetzger** [comment]
Mh. Good question. I think we have not discussed that so far.

I personally want to have a very good user experience on desktops. The responsiveness is a nice bonus and should also work, but our project has a lot of other very important issues to take care about. Finding somebody who's able to do some HTML and CSS is rather simple compared to finding somebody who's able to develop a database engine ;)
Also, we get very positive feedback from many users for our website. Compare it to the Hadoop website, I think we have already a pretty good standing.
I'm very happy about your feedback and I think a step-by-step approach is the most efficient solution right now. Lets see how the fixing of the current issue works out, then, we'll address the next one.

**Comment by nullusDefectus** [comment]
:+1: 

Having managed products and businesses end to end, I completely understand your position on wanting to provide a good user experience and balancing it with making progress on other fronts.

Until I hear otherwise, I will limit my reports on web UI to just the desktop.

**Comment by rmetzger** [comment]
We resolved the issue (with PR https://github.com/stratosphere/stratosphere.github.io/pull/2)

**Comment by nullusDefectus** [comment]
Excellent. I will look at the revision in the next few days.

**Comment by MoeweX** [comment]
I think we can close this issue, because it was fixed around a month ago... .

**Comment by StephanEwen** [comment]
Right, closed.
