### ISSUE TITLE
Change TextInputFormat to recognize Windows linebreaks

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#505]
The TextInputFormat currently does not handle optional `\r` characters before `\n`. It requires them to be strictly present, or never.

For full convenience, the InputFormat needs to ignore `\r` before a `\n`.

**Comment by tuantrieu** [comment]
I am trying to understand the issue. I went through the functions readRecord and readLine but it is not clear to me. What you want is that if \r is the last character of a line, it should be removed from the line ?

**Comment by rmetzger** [comment]
Hi,

Newlines are represented in different fashions for the different operating systems (https://en.wikipedia.org/wiki/Newline).
The operating systems use the following: ([src](http://stackoverflow.com/questions/426397/do-line-endings-differ-between-windows-and-linux))
Windows: '\r\n'
Mac (OS 9-): '\r'
Mac (OS 10+): '\n'
Unix/Linux: '\n'

So in the Windows case, the `TextInputFormat` must use `\r\n` to split the lines, for the other operating systems `\n`. The current implementation is only using `\n`

**Comment by tuantrieu** [comment]
Thank,
So, the code has to be able to identify if the text file originates from Windows, then use \r\n to split the lines ?

**Comment by StephanEwen** [comment]
I suggest to do the following: If \n is configured as the delimiter, a
trailing \r should be removed if present.

**Comment by tuantrieu** [comment]
I made a small change in readLine() in DelimitedInputFormat to do this. And I tested by printing out lines in string and in bytes to see if \r removed. Then running word-count with it.

Please let me know if it does something wrong, I learn from your feedback.

**Comment by fhueske** [comment]
Hi @tuantrieu,

thanks for taking care of this!
Can you open a pull request against stratosphere staging branch to share your modifications?

**Comment by tuantrieu** [comment]
I am sorry. I thought committing the change did that. This is my first time using Github.
I just created a pull request https://github.com/tuantrieu/Stratosphere/pull/1

**Comment by rmetzger** [comment]
Hi,
no problem.
You have now created a pull request against your own repository. A pull request means "offer a repository to accept and use my change".
In your case, you have made a change in branch `My-Branch` and you want us to merge it into our `master`.
In the pull request menu, you have to choose our repository. You can read more here: https://help.github.com/articles/creating-a-pull-request

**Comment by fhueske** [comment]
Hi @tuantrieu,

no sorries, That's perfectly fine. 
The initial contribution is also meant to help you to get familiar with our development process.

**Comment by tuantrieu** [comment]
I tried again https://github.com/stratosphere/stratosphere/pull/577
Could you take a look ?

**Comment by fhueske** [comment]
Fixed in #582
