### ISSUE TITLE
Add setValue methods to Value types

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#519]
StringValue provides a function StringValue.setValue(StringValue s) to set its value to the value of another StringValue.

The other value types (e.g., IntValue, DoubleValue) do not provide such a method. 
For consistency reasons, these types should be extended by the corresponding functions.

**Comment by MikhailErofeev** [comment]
Hello, I want to realize this as my first contribution to project. 
Would it be nice to add interface MutableValue<V> with setValue(V) and implement it to basic types? Should this interface contains more methods?

**Comment by rmetzger** [comment]
Hi,
great idea! We are always happy about contributions!

I think introducing an interface `MutableValue<T> for a`setValue(T)` method is a good idea! Somebody might come up with a better name for the interface but renaming afterwards should not be a big problem ;)

**Comment by MikhailErofeev** [comment]
can't link pull request with this issue:( https://github.com/stratosphere/stratosphere/pull/525
Why don't you use Null-checkers annotations in project? They are very helpful in code analysis with IDE, imo.

**Comment by MikhailErofeev** [comment]
Looks like it' bad fix. It's broke compability with existing code in cases, when autoboxing falls (int -> Double, for example).

**Comment by StephanEwen** [comment]
Fixed in 2006980be27debb604b40dc8f5c0ea229a4ae0ac via #525
