### ISSUE TITLE
UnitTests for new Java API Runtime

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#547]
The runtime code of the Java API needs to be extensively tested. 
This includes the Serializers and Comparators for the various data types found in the
[eu.stratosphere.api.java.typeutils.runtime](https://github.com/stratosphere/stratosphere/tree/master/stratosphere-java/src/main/java/eu/stratosphere/api/java/typeutils/runtime) package.

**Comment by rmetzger** [comment]
+1
I would suggest to add a test for every bug we ever see. For example your sorting bug should covered by a test.

**Comment by StephanEwen** [comment]
+1

**Comment by rmetzger** [comment]
Tests for comparators are missing.

**Comment by fhueske** [comment]
Comparator tests are done #772.

**Comment by fhueske** [comment]
Are we also done with the serializer tests?

**Comment by StephanEwen** [comment]
Yep, they are done.

**Comment by fhueske** [comment]
OK, let's close it.
