### ISSUE TITLE
Tests for the operators of the new Java API

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#548]
The operators of the new Java API need to be tested for different data types (Tuples, Native Java Objects (Generic Avro Serialization), ...) and different key definitions (record fields, key extractors) in different combinations.

**Comment by fhueske** [comment]
I thought about the operator tests and made a [wiki page of tests that we should run](https://github.com/stratosphere/stratosphere/wiki/Operator-Tests-New-Java-API).
Please review, comment, extend.

Since this is a larger effort, it would be cool, if some of you guys would pick one or two operators and write tests for them. 
I started with the tests for [**Filter**](https://github.com/stratosphere/stratosphere/blob/a7d10395058f21f1c66375857c92544ef2a78ce9/stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/FilterITCase.java) and will continue with tests for **Reduce**.

If you decide to test an operator, have a look at the [filter tests](https://github.com/stratosphere/stratosphere/blob/a7d10395058f21f1c66375857c92544ef2a78ce9/stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/FilterITCase.java) and drop a line, so that it is clear what is currently being worked on.

**Comment by vasia** [comment]
Hey! I can work on this, e.g. for Map and FlatMap to start with. Is that OK?

**Comment by fhueske** [comment]
Yes, definitely! That would be great! More tests a always very welcome! :smile:

**Comment by vasia** [comment]
Hey @fhueske, I have pushed my Map operator test [here](https://github.com/vasia/ozone/blob/japi_operator_tests/stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/MapITCase.java). 
Could you take a look and let me know if that's what you had in mind? If yes, I'll continue with the FlatMap operator :) Thanks!

**Comment by fhueske** [comment]
Hi @vasia,
looks very good to me! Thank you!

I'll be working on tests for Join.

**Comment by markus-h** [comment]
I started working on cogroup

**Comment by markus-h** [comment]
@fhueske In your wiki page you wrote "check correctness of cogroup a tuple input with key field selector and a custom type input with key extractor"
Currently there is no support for mixing key extractor and field position keys. Should this be implemented?

**Comment by fhueske** [comment]
Yes, I think we should support that.

**Comment by markus-h** [comment]
I opened an issue for that: #675

**Comment by vasia** [comment]
Hey, you can find the test for the FlatMap [here](https://github.com/vasia/ozone/blob/japi_operator_tests/stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/FlatMapITCase.java). Let me know if you want me to add/change annything, otherwise I'll create a PR for both Map and FlatMap tests. Thanks!

**Comment by fhueske** [comment]
Hi @vasia. Looks very good. Please create a PR.
Thank you very much!

**Comment by markus-h** [comment]
I started to work on cross.

**Comment by markus-h** [comment]
Last but not least: groupReduce

**Comment by fhueske** [comment]
First of all, @markus-h and @vasia thanks for helping with the tests!

The current state of this issue is as follows:

Only one operator is not covered by integration tests:
- `JoinITCase`: I will take care of it. **DONE**

Unit tests to check for valid parameters similar to `GroupingTest` are missing for:
- Join **DONE**
- CoGroup

A few integration tests need some extensions:
- `CoGroupITCase`: left, right combinable CoGroup functions **NOT SUPPORTED**
- `FilterITCase`: broadcast variable **DONE**

There are also some tests that need to be extended but which require some other issues to be solve first:
- `GroupReduceITCase`: descending group sort waits for a fix of #588 
- `GroupReduceITCase`: combinable GroupReduce function due to #700
- `CrossITCase` (and `JoinITCase`): custom objects are not supported due to #691

**Comment by markus-h** [comment]
I think we don't need tests for combinable cogroup, because it is not supported yet. See #712

**Comment by fhueske** [comment]
Alright, we made some good progress (thanks @markus-h !)
The current status of this issues is as follows:

Unit tests to check for valid parameters similar to `GroupingTest` are missing for:
- CoGroup

There are also some tests that need to be extended but which require some other issues to be solve first:
- `GroupReduceITCase`: descending group sort waits for a fix of #588 
- `GroupReduceITCase`: combinable GroupReduce function due to #700
- `CrossITCase` (and `JoinITCase`): custom objects are not supported due to #691

**Comment by fhueske** [comment]
Just realized, we do not have any tests for the Aggregate operator...
We need unit tests to check for correct parameters and integration tests for result correctness.

**Comment by StephanEwen** [comment]
agree

**Comment by fhueske** [comment]
If we did not miss anything the only things left to close this issue are to enable some tests:
- `GroupReduceITCase`: descending group sort waits for a fix of #588 (@zentol: this is the test for sorting that I mentioned previously)
- `GroupReduceITCase`: combinable GroupReduce function due to #700

**Comment by zentol** [comment]
case 12 (combinable) in GroupReduceITCase fails for me.

```
arrays first differed at element [0]; expected:<231,[91,Hello World]> but was:<231,[I am fine.]>
```

i reran it and got

```
arrays first differed at element [0]; expected:<231,[91,Hello World]> but was:<231,[Comment#7]>
```

**Comment by fhueske** [comment]
The input data sets in `CollectionDataSets` are randomly shuffled. So the input looks a bit different everytime the test is executed. 
However, the result should be identical (maybe in different order). 

So there's still a bug somewhere.

**Comment by zentol** [comment]
For some reason the combine method is never called.

**Comment by StephanEwen** [comment]
I am looking into it...

**Comment by StephanEwen** [comment]
Makes sense that the combiner is not called:

Source (DOP1, because collection) -> AllGRoupReduce(DOP1)

Makes no sense to inject a combiner.

**Comment by fhueske** [comment]
Finally, we have tests for all operators in place. Thanks @markus-h, @vasia and @StephanEwen!
