### ISSUE TITLE
New Java API: reduce function does not allow to return input object.

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#563]
The reduce function of the new Java API does not work if the an input object is returned, i.e.,

New example:

```
public T reduce(T value1, T value2) throws Exception {
  value1.setVal(value1.getVal() + value2.getVal());
  return value1;
}
```

This is due to the internal mutable object runtime.

Wrong example:

```
public T reduce(T value1, T value2) throws Exception {
  value1 = value1 + value2;
  return value1;
}
```

**Comment by StephanEwen** [comment]
Can you elaborate a bit more, what does happen in this case? In the
example, it looks like the value1 reference (or value) is reassigned to
value1+value2. That does not modify any internal object, or am I
overlooking something?

**Comment by fhueske** [comment]
I observed the problem with the `ReferenceWrappingReducer` in [PlanReduceOperator](https://github.com/stratosphere/stratosphere/blob/master/stratosphere-java/src/main/java/eu/stratosphere/api/java/operators/translation/PlanReduceOperator.java) but expect this to have the same effect in [ReduceFunction](https://github.com/stratosphere/stratosphere/blob/master/stratosphere-java/src/main/java/eu/stratosphere/api/java/functions/ReduceFunction.java).

When looping over the iterator, the final hasNext() call in the wrapping `reduce(Iterator<Reference<T>> in, Collector<Reference<T>> out)` overwrites the curr object.
I think the problem is that return values are not _safe_ when returned from the user function as in the other function which serialize output values or immediately forward them to the next function.

I am currently working on a fix that copies the result of the function call into another mutable object using a Serializer.

**Comment by fhueske** [comment]
Damn, stupid example.
It should be something like:

```
public T reduce(T value1, T value2) throws Exception {
  value1.setVal(value1.getVal() + value2.getVal());
  return value1;
}
```

**Comment by StephanEwen** [comment]
Let's see if we can solve this without copying... Otherwise that kills
performance...

**Comment by StephanEwen** [comment]
Can you post a concrete example where it fails? Maybe add a unit test that fails due to this problem?

**Comment by fhueske** [comment]
I added a unit test for this to PR #578.

**Comment by fhueske** [comment]
In commit cf0eff3b1386486ed656aed1c1e8260c0cba5a09 I added JavaDocs to `T ReduceFunction.reduce(T value1, T value2)` function that tell the user that the second input object (`value2`) can be safely returned while the first input object (`value1`) must not be returned (checked by an integration test).
This is not the optimal solution, but I think the best we can do right now.
See also the discussion in #614
