### ISSUE TITLE
Add project operator to new JavaAPI

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#566]
Inspired by #552, I thought a project operator for Tuple DataSets would be really convenient.

Can we add a project operator to the new JavaAPI like this?

```
DataSet<Tuple4<Long, Integer, Double, String>> dataSet = ...
DataSet<Tuple2<String, Integer>> projectedDS = dataSet.project(3,1);
```

Where the fields 1 and 3 of the original tuple are moved into a Tuple2.
An operator like this would only work on DataSet of Tuples and not on arbitrary objects.

Do you think that could be done and is it worthwhile even if it is only working for Tuple Datasets?

**Comment by uce** [comment]
I think it's perfectly fine to have it only working with Tuple DataSets as we should aim at making it as convenient as possible for users. :+1: 

I leave the question whether it can be done to @StephanEwen.

**Comment by fhueske** [comment]
Added with #617.
