### ISSUE TITLE
Stratosphere yarn job should run as the user that submits the job

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#568]
We need to make sure that the JobManager and the TaskManagers are started as the user that invokes the job execution (or simplified, the yarn session script), rather than the yarn user.

Otherwise many common user/permission configuration will not work.

**Comment by rmetzger** [comment]
Mh, I already looked into the issue. There was a method call to set the user for containers (but it has been removed).

I'll have a closer look into the issue to resolve it.

**Comment by rmetzger** [comment]
I found a solution for "insecure" YARN setups (i.e. no Kerberos authentication)
