### ISSUE TITLE
Implement writeAsCSV(Path filePath, String rowDelimiter, String fieldDelimiter) for new Java API

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#570]
`DataSet.writeAsCSV(Path filePath, String rowDelimiter, String fieldDelimiter)` is currently not implemented.

**Comment by alexff91** [comment]
Hi, I think there is the realisation of this method:
https://github.com/aljoscha/stratosphere/commit/99660b21ccca6cb4ea2c7bd95aac3c6be0426c3e

**Comment by fhueske** [comment]
Fixed in #585 and merged into staging.
