### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by H-Theking** [stratosphere/stratosphere#583]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Your Job's Name 0.1
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.363s
[INFO] Finished at: Sat Mar 15 07:23:05 WAT 2014
[INFO] Final Memory: 4M/111M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to parse plugin descriptor for org.apache.maven.plugins:maven-resources-plugin:2.5 (/home/theking/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.jar): error in opening zip file -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException

**Comment by rmetzger** [comment]
Hi,
thank you for reporting the issue. I assume you were using the java quickstart.

**Comment by rmetzger** [comment]
The 0.4 java quickstart is working for me.
The `maven-resources-plugin-2.5.jar` file is probably corrupt (aborted download, transfer error etc.).
Delete the file using 

```
rm /home/theking/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.jar
```

Maven will download the dependency again.
I hope this solves your problem.

```
robert@robert-tower /tmp % curl https://raw.github.com/stratosphere/stratosphere-quickstart/master/quickstart.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1279  100  1279    0     0   2536      0 --:--:-- --:--:-- --:--:--  2532
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.2:generate (default-cli) @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.2:generate (default-cli) @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository missing. Using the one from [eu.stratosphere:quickstart-java:0.4] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Old (1.x) Archetype: quickstart-java:0.4
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: eu.stratosphere
[INFO] Parameter: packageName, Value: eu.stratosphere.quickstart
[INFO] Parameter: package, Value: eu.stratosphere.quickstart
[INFO] Parameter: artifactId, Value: quickstart
[INFO] Parameter: basedir, Value: /tmp
[INFO] Parameter: version, Value: 0.1
[INFO] project created from Old (1.x) Archetype in dir: /tmp/quickstart
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.559 s
[INFO] Finished at: 2014-03-15T09:18:50+01:00
[INFO] Final Memory: 13M/239M
[INFO] ------------------------------------------------------------------------



    A sample quickstart Stratosphere Job has been created.
    Switch into the directory using
         cd quickstart
    Import the project there using your favorite IDE (Import it as a maven project)
    Build a jar inside the directory using
         mvn clean package
    You will find the runnable jar in quickstart/target
    Consult our mailing list if you have any troubles: https://groups.google.com/forum/#!forum/stratosphere-dev



robert@robert-tower /tmp % cd quickstart
robert@robert-tower /tmp/quickstart % ls
pom.xml  src/
robert@robert-tower /tmp/quickstart % mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Your Job's Name 0.1
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/commons-logging/commons-logging/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/commons-logging/commons-logging/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/commons-logging/commons-logging/maven-metadata.xml (602 B at 1.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/httpcomponents/httpclient/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/maven-metadata.xml (2 KB at 9.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/jackson/jackson-core-asl/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/jackson/jackson-core-asl/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/jackson/jackson-core-asl/maven-metadata.xml (3 KB at 18.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/javax/mail/mail/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/mail/mail/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/javax/mail/mail/maven-metadata.xml (867 B at 5.9 KB/sec)
[INFO]      
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ quickstart ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/quickstart/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /tmp/quickstart/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/quickstart/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ quickstart ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ quickstart ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ quickstart ---
[INFO] Building jar: /tmp/quickstart/target/quickstart-0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.006 s
[INFO] Finished at: 2014-03-15T09:19:09+01:00
[INFO] Final Memory: 21M/239M
[INFO] ------------------------------------------------------------------------
mvn clean package  7.40s user 0.24s system 82% cpu 9.224 total
robert@robert-tower /tmp/quickstart %        
```

**Comment by H-Theking** [comment]
Another problem

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Your Job's Name 0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for eu.stratosphere:stratosphere-java:jar:0.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for eu.stratosphere:stratosphere-clients:jar:0.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ quickstart ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/theking/workspace/quickstart/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quickstart ---
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.jar
Downloading: http://repo.maven.apache.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
Downloading: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar
Downloading: http://repo.maven.apache.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar (14 KB at 0.5 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar (44 KB at 0.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:24.986s
[INFO] Finished at: Tue Mar 18 17:41:00 WAT 2014
[INFO] Final Memory: 8M/161M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project quickstart: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.codehaus.plexus:plexus-compiler-api:jar:2.2, org.apache.xbean:xbean-reflect:jar:3.4, log4j:log4j:jar:1.2.12: Could not transfer artifact org.codehaus.plexus:plexus-compiler-api:jar:2.2 from/to central (http://repo.maven.apache.org/maven2): No response received after 60000 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by rmetzger** [comment]
Hi,
there seems to be a network issue:

```
Could not transfer artifact org.codehaus.plexus:plexus-compiler-api:jar:2.2 from/to central (http://repo.maven.apache.org/maven2): No response received after 60000 -> [Help 1]
```

I think you have to retry until your connection is properly working.

**Comment by H-Theking** [comment]
Think its ok for now
