### ISSUE TITLE
Tuple field access indexes are off by one

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#599]
Tuple fields start at 1 (`Tuple1._1`) but are accessed with indexes starting at 0:
`Tuple1.getField(0)` and `Tuple1.T1()` return the same field `Tuple1._1`.

I find this confusing as would make it consistent for example by starting the `getField()` at 1 as well.

**Comment by fhueske** [comment]
The same applies for the key definitions, e.g., `DataSet.groupBy(0)` and `JoinOperatorSets.where(0)` (and so on) all refer to `Tuple._1`

**Comment by twalthr** [comment]
I also ran into this issue at the beginning. I would prefer to start all indexes at 0 as it is usual in computer science.

**Comment by fhueske** [comment]
I am fine either way as long as it is consistent :smirk:

**Comment by StephanEwen** [comment]
The tuples are inspired by the scala tuples. Those start at one. So the
choice is not easy...
Am 18.03.2014 09:25 schrieb "Fabian Hueske" notifications@github.com:

**Comment by fhueske** [comment]
Right, but I think we should have a decision rather soon, i.e., before we announce / release the API. Otherwise, we might silently break existing stuff.

**Comment by rmetzger** [comment]
I'm also in favor of zero-indexed tuples.
I would say Scala is inconsistent and we should not support that. The majority of our users are Java users, and not Scala users.

**Comment by rmetzger** [comment]
Rename it to "v0, v1, ..."

**Comment by twalthr** [comment]
Sorry, I need to ask again. I'm currently working in the TupleGenerator.
So v0,v1,.. was our final decision? I thought f0, f1,..
But _1,_2,.. should still exist for scala developers, right?

**Comment by fhueske** [comment]
I am in favor of replacing `private T1 _1;` by `public T0 f0;` and so on.
Also remove the getter `public T1 T1()` and setter `public void T1(T1 value)`.

This is a Java API and we should not think too much about the 1% Scala developers out there. These guys are probably smart enough and know that other languages start counting at 0 :smirk:

**Comment by fhueske** [comment]
Fixed in b6edba26c3443ebe33a3de4f482900fa424430f2
