### ISSUE TITLE
Add SetFields() Method to Tuples

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#600]
Add a `setFields()` method to tuples to set all fields of a tuple in one method call:
`public void Tuple3.setFields(T1 value1, T2 value2, T3 value3)`

**Comment by twalthr** [comment]
I will implement it.

**Comment by fhueske** [comment]
You know that you only need to change TupleGenerator for that, right?

**Comment by twalthr** [comment]
yes ;-)

**Comment by fhueske** [comment]
Fixed in b6edba26c3443ebe33a3de4f482900fa424430f2
