### ISSUE TITLE
Add JavaDocs to user-facing methods of new Java API

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#601]
We need to add JavaDocs to the user-facing methods of the new Java API to describe the operators and guide a user through sequences of function calls as for example required for a join:

```
DataSet.join(DataSet).where(int...).equalTo(int...).with(UDF)
```

**Comment by rmetzger** [comment]
:+1: 
I would also like to publish them on our website.

**Comment by fhueske** [comment]
I pushed JavaDocs for DataSet and Grouping. Will continue with the Join classes.

**Comment by fhueske** [comment]
I looked over the JavaDocs of DataSet, Operators, and ExecutionEnvironment and completed them.
This issue should be resolved by that. Note there are still JavaDocs missing for the Function classes see #657.
