### ISSUE TITLE
Delta iterations in new Java API

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#607]

**Comment by markus-h** [comment]
I'm on it.

**Comment by StephanEwen** [comment]
I have implemented a port of Spargel to the new java API. It does not use the new Java API classes for delta iterations, but rather directly instantiates the `eu.stratosphere.api.common` classes in the background.

It does however need the java api postpass to be able to handle delta iteration plan operators. Any chance you have gotten to that part already?

**Comment by markus-h** [comment]
No, sorry, not yet. But it should be very similiar to BulkIterations with
termination criterion, so you can try to do a quick copy paste.

2014-03-28 0:50 GMT+01:00 Stephan Ewen notifications@github.com:

**Comment by markus-h** [comment]
This issue can be closed.
See #643 merged in 74ce8d3
