### ISSUE TITLE
Add Union operator to new Java API

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#621]
Add support to union two (or more) identically typed data sets.
This is possible in the former API, so we need to support it here as well.

**Comment by rmetzger** [comment]
As far as I am aware, @filiphaase is working on this.

**Comment by rmetzger** [comment]
Please always write in the issue or open one if you start working on something. We had at least two cases in the past where people were working on the same topic without knowing.

**Comment by filiphaase** [comment]
Okay, thought assignment is enough ;)

**Comment by fhueske** [comment]
I think either is fine.

**Comment by rmetzger** [comment]
The problem with assignment is that there will be no email notification.
(And we do not really use the assignment feature).

**Comment by fhueske** [comment]
@filiphaase please add tests for Union analogous to `stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/FilterITCase.java` and `stratosphere-tests/src/test/java/eu/stratosphere/test/javaApiOperators/ReduceITCase.java`.

**Comment by fhueske** [comment]
well, I do. ;-)
And I guess it is exactly for this purpose.

**Comment by StephanEwen** [comment]
Fixed in e29cba57f0a03776287fea41046c21e6951b7fe0
