### ISSUE TITLE
Set write mode in new Japi

### ISSUE THREAD

**Issue by markus-h** [stratosphere/stratosphere#626]
I'm writing the output of a job using [...].writeAsCsv(outputPath);
When the file specified by the outputPath does not exist I get the following error:
 _Stream to output file could not be opened: Opening the file output stream failed: File or directory already exists. Existing files and directories are not overwritten in NO_OVERWRITE mode. Use OVERWRITE mode to overwrite existing files and directories._

As far as I can see I can only set the the writeMode in the FileOutputFormat class. But this class is instantiated in the DataSet class. Is there a clean way to switch to OVERWRITE in the new Japi that I have overseen? If not, what would (in your opinion) be a clean way to set this configuration in the new API?

**Comment by StephanEwen** [comment]
Good point. I think in these cases you would need to go with `dataset.write(new CsvOutputFormat(), filepath, writeMode)`

The writeMode parameter does not currently exist for the write(...) function, but we should add it in my opinion. And remove the redundant write(...) variant that takes a path as parameter.

Another option is to return the DataSink from the `write(...)` or `writeAsCsv(...)`method. That would allow you to fluently attach further options, like `setOverwrite()`.

**Comment by markus-h** [comment]
I think I like the first no fluid variant better. I will create a pull request shortly.

**Comment by markus-h** [comment]
Implemented in #630.

**Comment by StephanEwen** [comment]
Fixed in #630 via 5cc81cdd1f71c740669c7c4284524499d6e8617a
