### ISSUE TITLE
Add log view of task managers to web interface

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#633]
I think this is really important for more productive debugging.

Currently, we can only view the _job manager logs_ on the web interface. In failure cases, it is important to be able to also read the _task manager logs_.

I also suggest to implement some kind of caching for the logs in the interface as resending it everytime takes some time for large jobs. Furthermore, the current plain text presentation is too simple (e.g. add some tail view etc.).

**Comment by rmetzger** [comment]
You are right with the tail view and the caching.

BUT: There is some kind of error in the system that prevents the TaskManager's exceptions to show up in the JobManager. There is actually code to send the exception to the JobManager. (We even plan to show the exception in the webinterface: https://github.com/stratosphere/stratosphere/issues/483)
So I think it would be very very helpful to fix #483 first.

**Comment by uce** [comment]
I was aware of the plans to show the exceptions in the JM interface. But I really meant the whole log. Maybe we should add web interfaces for the TMs as well. I think this is a common approach. For example, Spark has web interfaces for both the master and workers.

**Comment by uce** [comment]
Still, #483 is a good starting point to improve stuff. :+1:
