### ISSUE TITLE
Bring Scala API up-to-date with new Java API

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#641]
I would like to integrate the TypeInformation work and also provide proper custom serializers, not how they are implemented now, with serializing to PactRecord.

Do you think I should be working on this now that the Java API looks somewhat finished? Or is there bigger fish to fry?

**Comment by StephanEwen** [comment]
I would like to finish the Java API first. Missing are still the union
operator and the advanced cases in the type extractor.
Am 01.04.2014 08:16 schrieb "Aljoscha Krettek" notifications@github.com:
