### ISSUE TITLE
Make Combine functions optional for CoGroupFunction.

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#644]
Currently, the `CoGroupFunction` of the new Java API forces the user to implement a `combineFirst()` and `combineSecond()` method.

We should make this optional, IMHO.

**Comment by StephanEwen** [comment]
+1!

**Comment by markus-h** [comment]
This is done here: #627

**Comment by fhueske** [comment]
Fixed in 2adafc6a9a59b73b5a0ce0b719db3e7c4d3e6767
