### ISSUE TITLE
Add Projection for Join and Cross Operators

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#648]
Currently, two types of joins are supported:
- Default join which emit Tuple2<IN1, IN2> types
- UDF join which calls a UDF for each joining pair and can return any type

We should add a third type of join that allows to project tuple fields.
This will reduce the need boilerplate code when joining tuples and removing redundant key fields.

**Comment by fhueske** [comment]
I am working on Projection for Joins.

**Comment by qmlmoon** [comment]
I'm starting working on Projection for Cross

**Comment by fhueske** [comment]
Projection for Join was added in PR #707

**Comment by fhueske** [comment]
@qmlmoon added Projection for Cross in PR #719

**Comment by fhueske** [comment]
Has been added in #707 and #719
