### ISSUE TITLE
Add TupleBuilder helper class

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#654]
If you want to create a `Tuple` data set as follows you have to write some quite verbose code:

``` java
DataSet<Tuple2<String, Integer>> data = env.fromElements(
                new Tuple2<String, Integer>("hello", 1),
                new Tuple2<String, Integer>("world", 2));
```

We could add a TupleBuilder along the following lines (this was proposed by @StephanEwen in https://gitter.im/stratosphere/stratosphere):

``` java
DataSet<Tuple2<String, Integer>> = env.fromElements(Tuples.build(
                t("hello", 1),
                t("world", 2)));
```

**Comment by filiphaase** [comment]
I'm starting to work on this issue now, or has anybody already implemented anything?

**Comment by fhueske** [comment]
I don't think so. 
Just assign yourself to the issue and it is yours ;-)

**Comment by fhueske** [comment]
Done in d0aaaa83cd1ec81cfd8d355d157cdf9b05d839fe
