### ISSUE TITLE
Rename DataSet.withBroadcastSet(DataSet, String) method

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#655]
To broadcast a data set you have to do the following:

``` java
lorem.map(new MyMapper()).withBroadcastSet(toBroadcast, "toBroadcastName")
```

In the operator you call:

``` java
getRuntimeContext().getBroadcastVariable("toBroadcastName")
```

I propose to have both method names consistent, e.g.
- `withBroadcastVariable(DataSet, String)`, or
- `getBroadcastSet(String)`.

**Comment by fhueske** [comment]
:+1:
I vote for BroadcastSet.

**Comment by StephanEwen** [comment]
Here is something I was thinking about for the future:

It is a very common case that the broadcast set/variable is just a single scalar value. It would be nice to support that elegantly as well. We could therefore have:
- `getBroadcastSet(String)` to get a collection of elements
- `getBroadcastVariable(String)` to get a scalar value

**Comment by twalthr** [comment]
+1
I also had the case at the Telekom, where only a scalar value sum/average needed to be broadcasted.

**Comment by uce** [comment]
I agree. But I would propose value instead of variable, i.e. `getBroadcastValue(String)`, which seems more natural to me (you also said "to get a scalar value" and not "scalar variable").

**Comment by fhueske** [comment]
:+1: for `broadcastSet` and `broadcastValue`

**Comment by aalexandrov** [comment]
:+1: for `broadcastSet` and `broadcastScalar`
