### ISSUE TITLE
Add RuntimeContext to open method of functions

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#656]
This is minor.

Is it reasonable to add the `RuntimeContext` as an argument to the `open(Configuration)` method of stub functions? Can we do this without breaking stuff?

I would find it nice to replace the possibly repeated calls to `getRuntimeContext().getBroadcastVariable()`, `getRuntimeContext().addAccumulator()`, etc. with something like `context.getBroadcastVariable()`.

**Comment by StephanEwen** [comment]
I am a bit skeptic here. That would definitely break compatibility. It does not add functionality. You can always write `RuntimeContext context = getRuntimeContext()` as the first line in open().

**Comment by uce** [comment]
Yes. I was also worried about compatibility.
