### ISSUE TITLE
Attach output of a contract as additional input for another contract (Broadcast variables / Closures)

### ISSUE THREAD

**Issue by andrehacker** [stratosphere/stratosphere#66]
Another PACT API feedback from user perspective.
### Requirement
- **Make the output (all records) of one or more contracts available in every udf call of another contract.**
- This should work in an efficient way. Using the Cross-Workaround, we receive the same pactrecord for every udf call and the first line is usually a deserialization (we cache the value, but then need an additional check if we already cached).
- It should be as explicit as possible to use this functionality (broadcast/attach). In my opinion it is a very common pattern. This gives the system more knowledge about our intention and more options for optimization.
### Problem
- **The often proposed workaround, to use Cross, only works for the special case where 1) the input to broadcast consists of a single record and 2) we want to broadcast the output of a single contract only and 3) it only works for Map, not for Reduce, CoGroup or Match**
- Using Cross for broadcasting of a single output record feels more like a workaround than a natural fit (especially because it works only for a very special cases) Broadcasting, distributing or attaching feels much more natural.
### Solutions
1. Implement a Distributed cache in the hadoop way. It has functionality to read or write files.
2. Provide generic workaround contracts (like "flatten" multiple records to a single one).
3. Add explicit support to broadcast and attach the output of a previous contract to a contract as an additional input. Before the udf is called, another method should be called with all the inputs so that the udf can deserialize the records, optionally customize them and store in-memory.
   I didn't think too long about this, but a api (here for Map) could look like this:

```
MapContract myMap = MapContract.builder(MyMap.class)
  .input(myDataSource)
  .attachAsAdditionalInput(contract1ToAdd)
  .attachAsAdditionalInput(contract2ToAdd
  .build()
```

And a new method in MapStub that is called before  the first `map()` call

```
public void additionalInputs(Iterator<PactRecord>[] iterators) {
  // read records from additional inputs, process and cache in-memory 
}
```
### Discussion
- In Hadoop the usual way to solve this is the distributed cache. This is very powerfull and flexible, but is probably not a good fit for this requirement. The output is not stored as a file (as it is for hadoop) and we want to pipeline it.
- I currently use workaround contracts, but this is just a (slow) workaround and not a good long term solution in my opinion
- I would vote for adding explicit support - probably there are many more options than the one I described.
### Use Cases / Examples
- In my current machine learning job I want to basically scan/map over the training data (tf-idf vectors) and during the processing I need the output of two prior contracts. The first output to be broadcasted is a single record (a model = vector). The second output to be broadcasted consists of multiple records. I had to write two workaround contracts. First experiments showed that the pact implementation is slower than Hadoop, an I guess the many workarounds are a reason.
  - The first Reduce workaround "flattens" all output records to a single record. I had to emit a constant key (because the functionality to reduce without key didn't work and I didn't know about it)
  - The second Cross workaround makes one out of two records, to overcome the limitation of two inputs in Cross.

**Comment by StephanEwen** [comment]
We have this issue on the ToDo list under the name GlobalVariable or BroadcastVariable.

Are you interested in implementing this feature? I'd be happy to introduce you into the code that you would need to change. It is a good project if you want to learn the entire stack. (API, compiler, dataflow generator, runtime).

**Comment by rmetzger** [comment]
@aalexandrov is going to take care of the implementation of broadcast variables.
Write once, read only.

(Stratosphere 2 is probably going to add a more advanced implementation in the feature)

**Comment by rmetzger** [comment]
Today, I discussed the implementation of a machine learning algorithm on Stratosphere with some students.
They also need this feature to broadcast a normalization vector to a later operator. 
They can use a cross, but this is certainly not the nicest way to solve the problem.
I hereby emphasize the importance of this feature.

**Comment by StephanEwen** [comment]
Is implemented as of two weeks ago.
