### ISSUE TITLE
DOP of sink after all reduce higher than expected

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#663]
Consider the following situation: the program DOP is 8; the last transformation is an all reduce (i.e. reduce without a grouping); after this, the result is written out.

How many files should this result in? I was expecting a single file, but found that it will create 8 files.

ATM I haven't checked if the sink still has a higher DOP or if there is a problem with the reduce op.

**Comment by StephanEwen** [comment]
At the moment, all nodes will use the default degree-of-parallelism, unless they explicitly state a different one. The AllReduce states a DOP of 1 (by definition). The sinks then have the default DOP again.

I agree that this may be not what you want in that case. Do we need different rules in how to determine the DOP of an operator, or is this simply a special case for sinks?

**Comment by fhueske** [comment]
I'd say this should be a specific rule for DataSinks. A DataSink should adopt the DOP of its preceding task if its DOP was not explicitly defined.
If an AllReduce is followed by a regular operator it might make sense that this operator is run in parallel and we should not change this default behavior.

What do you think?

**Comment by StephanEwen** [comment]
This suggestion was implemented in 44ccde6503469391bca67cc0c71aedca13435f3a
