### ISSUE TITLE
Remove record examples

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#665]
Now that we are having more and more examples for the new Java API, I would like to remove the examples for the record api. Too many (quasi duplicate) examples can be really confusing.

I would suggest to move the record examples to the stratosphere-artifacts repository.

**Comment by fhueske** [comment]
In general I am in favor of doing this.
However, we should make sure that we do not cut on test coverage here since many integration tests are based on these examples.

**Comment by StephanEwen** [comment]
We could also move them to stratosphere-tests, to keep using them as end-to-end integration tests. That way we loose no test coverage and keep a slim and clean examples project.

**Comment by fhueske** [comment]
:+1: 
In the long run, we should try to remove some overlap in the integration tests. A lot of them are very similar, do not add any benefit, but increase build time by several minutes.
But for now, moving is fine with me.

**Comment by fhueske** [comment]
Record examples were moved in c41569eb01ac9ab83e17554a50ccdc7e4ac49327
