### ISSUE TITLE
Implement a Filter Operator on Compiler/Runtime Level

### ISSUE THREAD

**Issue by filiphaase** [stratosphere/stratosphere#669]
The current implementation of the filter operator is a wrapper around the flat-map operator (see eu.stratosphere.api.java.operators.translation.PlanFilterOperator).

Therefore the compiler handles every filter as a flat-map, meaning that their cardinality estimation for the output size is the same(currently inputSize*5). Since the filter  reduces the number of records, we should fix this issue in the future by implementing an own filter operator for the compiler- and runtime level.

**Comment by rmetzger** [comment]
Can we move this issue to the 0.6 release?

**Comment by fhueske** [comment]
I think it would be good to have at least the selectivity estimation error fixed for the release.

**Comment by filiphaase** [comment]
I think the selectivity estimation error is fixed in the PR from @markus-h  (https://github.com/stratosphere/stratosphere/pull/716), he's using (inputSize \* 0.5) there.

His implementation is still using the FLAT_MAP-driver, but I don't see a problem with that. 
So I think we could close the issue when his PR is merged.

**Comment by fhueske** [comment]
#716 was merged.
