### ISSUE TITLE
TypeExtractor.getForClass(...) should work for subclasses of tuples

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#682]
The method currently rejects subclasses of tuple. If the subclass defines all generic parameters, it should be accepted by the type extractor.

**Comment by twalthr** [comment]
I can do that tomorrow. But than I have to change the API, since a tuple is a `ParameterizedType` not a `Class`.

**Comment by StephanEwen** [comment]
Which part of the API is affected by that? The method getForClass(...) would still accept a class, right? Are the methods that need to change user facing, or internal?

**Comment by twalthr** [comment]
Your right, we could change the argument to `Type`. But actually `getForClass()` is intended for Classes only. One should use `TypeExtractor.createTypeInfo(Type t)` as this supports all types not only Classes.

**Comment by rmetzger** [comment]
Merged.
