### ISSUE TITLE
Cross (and probably Join) not working for custom type objects

### ISSUE THREAD

**Issue by markus-h** [stratosphere/stratosphere#691]
By creating the testcases for the cross operator I noticed that it is currently not possible to use cross on custom type objects.
The reason for that is that the two copy methods in the AvroSerializer are currently not implemented.
The same problem probably applies for the join operator.

I think this issue is quite critical. Testcases for the cross are already created (withoud warranty for correctness) but commented out.

**Comment by fhueske** [comment]
`CrossITCase` contains a deactivated test case to check for the problem.
Once, this issue is fixed, the test should be activated.

**Comment by fhueske** [comment]
Moving from Avro to [Kryo](https://github.com/EsotericSoftware/kryo) might be the way to go here.
Kryo's website states: 

_"Kryo is a fast and efficient object graph serialization framework for Java. The goals of the project are speed, efficiency, and an easy to use API. The project is useful any time objects need to be persisted, whether to a file, database, or over the network. Kryo can also perform automatic deep and shallow copying/cloning. This is direct copying from object to object, not object->bytes->object."_

There is also an issue #610 and a PR for this #706

**Comment by rmetzger** [comment]
I'm looking into this issue.

**Comment by StephanEwen** [comment]
I actually have a kryo serializer running (more or less. still need to test how it behaves in corner cases). Will merge it today hopefully.

**Comment by rmetzger** [comment]
So its an alternative implementation to https://github.com/stratosphere/stratosphere/pull/706 ?
If yes, tell the student to avoid any additional work on his side.

**Comment by StephanEwen** [comment]
It is baesd on his pull request, but i fixed it up similarly as you did. I
still want to investigate how it behaves with generic classes and so. I
think I will make a mix of his, your, and my pull request ;-)

**Comment by StephanEwen** [comment]
Fixed with the introducetion of Kryo in the generic serializers/comparators
