### ISSUE TITLE
GroupReduce with Key Selection Function does not call combine()

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#700]
The `TupleUnwrappingGroupReducer` implements an empty `combine()` which means that a `GroupReduceFunction` that is used on a `Grouping` with `KeySelector` cannot use its combiner.

While digging a bit deeper into the code, I am not sure, if a `GroupReduceFunction` will ever use its combiner (even in `Grouping` with field positions and maybe even when applied without a `Grouping`). The `GroupReduceOperatorBase` has a flag attribute `combinable` which seems to be always false, hence telling the optimizer that all `GroupReduceFunction`s do not support `combine()`.

We should check this!

**Comment by fhueske** [comment]
The `GroupReduceITCase` should be extended to check if the combiner of a combinable `GroupReduceFunction` is called for non-grouped, field-pos-grouped, and key-selector-grouped datasets.

**Comment by markus-h** [comment]
I started working on this issue.

**Comment by markus-h** [comment]
Is there runtime support for combine in combination with an all-reduce?

**Comment by StephanEwen** [comment]
The old Java API had that. Once we add the Combinable annotation/flag to
the new API, it should work for both the grouped reduce and the all-reduce.

**Comment by markus-h** [comment]
I am working on this that is why I'm asking. I set the flag, but as far as I can see only the AllReduceDriver is used and it does not call the combine method. 
After post pass the source has driver strategy NONE and the reduce has ALL_GROUP. For the pact contract combinable is true. The combine method in my udf is not called.

**Comment by StephanEwen** [comment]
The optimizer plan does not inject a combine node?

**Comment by markus-h** [comment]
As far as I can see: no.

**Comment by markus-h** [comment]
I spent some more time on this issue. I think the compiler sees that the DataSource is directly locally connected to the all-reduce UDF function, therefore it would not be of any use to plug in a combiner locally. So in my opinion it is not a bug, but a feature.

**Comment by fhueske** [comment]
Can you try to increase the DOP (> 1) of the DataSource? Then, the data must be shuffled and a Combiner would be important to reduce the shipped data volume.

**Comment by markus-h** [comment]
Even with DOP > 1 the data is not shipped through the network and therefor the shipping strategy remains FORWARD and everything is passed locally. Since we have an all-reduce there is no real shuffling as long as we stay on one node.
I think in a cluster environment it should work.

**Comment by StephanEwen** [comment]
Can you try it with a LocalDistributedExecutor? Then you should see
shipping behavior.

**Comment by markus-h** [comment]
I have some trouble to get the testcase to run with LocalDistributedExecutor. I tried a naive
`LocalDistributedExecutor lde = new LocalDistributedExecutor();
                lde.start(2);
                lde.run(env.createProgramPlan());`
but I get different kind of errors.

**Comment by StephanEwen** [comment]
Can you post those?

**Comment by fhueske** [comment]
The original issue (combine for key-selector reduce operators) has been resolved.

@markus-h Can you open an issue for combine support for all-reduce transformations?
