### ISSUE TITLE
Spargel can not set convergenceCriterion 

### ISSUE THREAD

**Issue by JavierJia** [stratosphere/stratosphere#704]
The Spargle iteration packed the `DeltaIteration` as a private field. 
There is no way to set `getAggregators().registerAggregationConvergenceCriterion` to indicate to stop the iterations.

**Comment by markus-h** [comment]
Hi Jianfeng! 
Sorry for the late answer. I think full access to the wrapped DeltaIteration would not be very nice. What do you think: Would it be enough to provide the SpargelIteration with an own getAggregators method?

**Comment by JavierJia** [comment]
Hi @markus-h 
I think it should be enough for this specific issue, that I want to stop the iteration automatically than let it run until the max-iterations.

Actually in deeper code analyse, sometimes the `DeltaIteration` would not be enough for Graph computing. For example, if we want to implement a `Single source shortest path` algorithm, the `Delta` of computing node is increasing, rather than decreasing. But this part should be another separate issue :new: . Do you think so ?

**Comment by StephanEwen** [comment]
Hi!

The sssp algorithm works actually well with delta iterstions in the
following way: The work set (candidate paths/steps) is increasing for most
of the time, but the delta (the number of nodes that finds a new shortest
path) will go down eventually.

But: An existing limitation is that Delta iterations cannot remove elements
from the solution. You could still tombstone elements, though.

Greetings,
Stephan

**Comment by rmetzger** [comment]
Hey @JavierJia,
we merged the "getAggregators()" into the code.
