### ISSUE TITLE
CoGroup does not call combineFirst/Second

### ISSUE THREAD

**Issue by markus-h** [stratosphere/stratosphere#712]
I tried to write a test for combinable cogroup (see  #548). I extended the new API to set the correct flag for combinableFirst/Seconed so that it is correctly passed to the optimizer, but the combine methods are not called. I tried to right click in eclipse and "open call hierarchy" on the combine methods (usually that gives me the place where the method is called) but it stayed empty. Is there runtime support von combineFirst/Second on cogroup? If yes, in what driver are the combine methods called? 
I do not find any example where combineFirst/Second are used. I tested it with the CoGroupConnectedComponentsITCase and set a breakpoint inside the combineFirst but it is not called.

**Comment by StephanEwen** [comment]
There is currently no runtime or optimizer support for CoGroup combining.
The functioned are placeholders for now.

**Comment by markus-h** [comment]
Ok, I didn't know that.

**Comment by fhueske** [comment]
I think in this case we should remove / deactivate the combine methods in the `CoGroupFunction` class.

**Comment by fhueske** [comment]
I'll take care of this

**Comment by fhueske** [comment]
`combineFirst()` and `combineSecond()` have been removed in this commit a6d188cda8ba527db6e0f3cee57df85821be53af.
