### ISSUE TITLE
./bin/stratosphere client is unable to submit record-API jobs

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#724]
Because it calls the main method instead of getPlan().

**Comment by rmetzger** [comment]
The error has probably been introduced by https://github.com/stratosphere/stratosphere/commit/ca41f6aec9d87d57c08aae38a9516754683cbfc7

```
./bin/stratosphere run -j ../../rmetzger/testjob/target/testjob-0.1-SNAPSHOT.jar -c eu.stratosphere.test.testPlan.DistributedCacheTest  -a 2 hdfs:///user/robert/datasets/a hdfs:///user/robert/datasets/b hdfs:///user/robert/test/distCa
```

**Comment by rmetzger** [comment]
The issue is invalid, sorry.

**Comment by StephanEwen** [comment]
What was the source of the problem then? I am curious...

**Comment by rmetzger** [comment]
Well, its unbelievably stupid. 
I forgot to implement the `Program` interface for the main class.

**Comment by StephanEwen** [comment]
Happens ;-)
