### ISSUE TITLE
Implement tests für Basic- and TupleComparators

### ISSUE THREAD

**Issue by zentol** [stratosphere/stratosphere#744]
@filiphaase and myself are working on this.  

Regarding the TupleComparator, how exactly is this one specified?
some specific things i wonder about whether they are intended:

a)
if you look at the following code taken from the compare method:

```
int i = 0;
try {
    for (; i < this.keyPositions.length; i++) {
        int cmp = this.comparators[i].compare(firstSource, secondSource);
        if (cmp != 0) {
            return cmp;
        }
    }
    return 0;
}
```

it is evident that the _values_ of the keypositions arent really used, but only the _number_ of positions. this means that the comparison only works if the first n fields are used as keys without skipping a field. (and match the type)

b)
if one uses all fields as keys, you hit an EOFException.

**Comment by StephanEwen** [comment]
Okay, not using the field positions is clearly a bug ;-)

I do not understand why we can hit an EOFException?

I asume one problem here is that we need to deserialize the tuple if we
want to access the individual fields.

**Comment by zentol** [comment]
could we pass a comparator for every field, regardless of whether or not it is used as a key (or pass _any_ kind of information covering the type of all fields)? we could then adjust the offsets accordingly and access the fields without deserializing.

**Comment by zentol** [comment]
clarification: only if a String is used as a key an EOFException occurs.

**Comment by zentol** [comment]
lets say you have two tuple2<Integer,Integer>. if the tuplecomparator returns a result on the first field, is it supposed to skip the remaining bytes of the second integer? (because it doesn't, which breaks my testcases atm)

**Comment by StephanEwen** [comment]
Yes, I see. That is specific to the way the tests happen, I guess.

The sorter code that runs this part seeks the views to the beginning of the
record before starting the comparisons. Can you do something similar?

**Comment by zentol** [comment]
okay, if thats how it works then i will adjust the tests accordingly :)

**Comment by StephanEwen** [comment]
If you compare on the second field of the tuple, the sorter will seek to
the beginning of the tuple as well. That means you may need to deserialize
the leading fields, unfortunately.
