### ISSUE TITLE
Implement a special type for Hadoop Writables

### ISSUE THREAD

**Issue by twalthr** [stratosphere/stratosphere#747]
As mentioned in #579:

Please add also Types that implement Hadoop's Writable interface. They should have a special serializer that calls the write() and readFields() method.

A discussion about the necessary dependencies can be found on the mailing list:
https://groups.google.com/forum/#!searchin/stratosphere-dev/writable/stratosphere-dev/OybICx1IxLM/SeLUp2wH0N4J

**Comment by twalthr** [comment]
Actually most `Writables` are AtomicTypes, right? Would the following lines of code ok or should I not treat them as AtomicTypes?

``` java
@Override
    public TypeComparator<T> createComparator(boolean sortOrderAscending) {
        if(Comparable.class.isAssignableFrom(typeClass)) {
            return new WritableComparator<T>(sortOrderAscending);
        }
        else {
            throw new UnsupportedOperationException("Writable does not implement Comparable interface.");
        }
    }
```

**Comment by StephanEwen** [comment]
Yes, we see writables as atomic types.

But please check that when creating the comparator from the type
information, such that you get the error early.

**Comment by StephanEwen** [comment]
Can you keep this in the addons/hadoop-compatibility package? I think it would be nice if the stratosphere-java project had no hadoop dependency.

**Comment by fhueske** [comment]
Done with PR #776.
