### ISSUE TITLE
inconsistent read/write in StringValue

### ISSUE THREAD

**Issue by zentol** [stratosphere/stratosphere#748]
the static writeString() method in StringValue adds an offset of 1 to differentiate between null and "". while the readString() method accounts for this, the non-static read()/write() methods do not.

this currently causes issues in the StringComparator, which uses writeString() to serialize but read() to deserialize, causing it to read an additional character.

is there a reason why these methods behave differently?

**Comment by StephanEwen** [comment]
The reason is that you can statically read a null. But if you have already
a StringValue instance which deserializes itself  from the stream, it is
naturally not null.

**Comment by zentol** [comment]
would it be a problem to add the offsets to the non static methods?

**Comment by StephanEwen** [comment]
I think you can add the offsets to the non static method as well

**Comment by StephanEwen** [comment]
Fixed in d2a5178014470591c155989158d3d8629a6ee0ef
