### ISSUE TITLE
Multiple Aggregations producing wrong result

### ISSUE THREAD

**Issue by markus-h** [stratosphere/stratosphere#757]
I started writing the integration tests for the aggregate operator and have some trouble with my first example:

```
DataSet<Tuple3<Integer, Long, String>> ds = CollectionDataSets.get3TupleDataSet(env);           
DataSet<Tuple2<Integer, Long>> aggregateDs = ds
                        .aggregate(Aggregations.SUM, 0)
                        .aggregate(Aggregations.MAX, 1);
```

What I expect is the SUM and MAX of all fields. I get always the correct sum but for the MAX the result is changing, sometimes producing 4 or 5 instead of the correct 6.
Has somebody an idea where the problem could lie?

**Comment by StephanEwen** [comment]
You Aggregate over an aggregate.

DataSet.aggregare(a).aggregate(b) = b(a(dataset)).

DataSet.aggreage(a).and(b) = a,b(dataset)
Am 06.05.2014 10:09 schrieb "markus-h" notifications@github.com:

**Comment by markus-h** [comment]
Oh I see, I overlooked the and operator.

**Comment by StephanEwen** [comment]
I guess we need good comments or docs for that,
