### ISSUE TITLE
Redesign stratosphere.eu website

### ISSUE THREAD

**Issue by dimalabs** [stratosphere/stratosphere#76]

**Comment by rmetzger** [comment]
Preview of @aalexandrov's work: http://rmetzger.github.io/ozone/

**Comment by aalexandrov** [comment]
New version of the website is available, minus the input from @ktzoumas , at http://aalexandrov.github.io/ozone. I encourage everybody to check for errors (dead links, inappropriate text, etc.). The homepage will probably be reworked in the coming weeks but this is not time critical.

Once we have the full text for the Stratosphere workshop I'll merge the gh-pages branch with the main repository.

@ktzoumas: Can you do a pull request with your modification of the `events/2013/workshop.html` page to my fork of the ozone repository?

**Comment by aalexandrov** [comment]
Closed by pull request #104.
