### ISSUE TITLE
Implement extractInputFormatTypes() for TypeExtractor 

### ISSUE THREAD

**Issue by twalthr** [stratosphere/stratosphere#767]
TypeExtractor.extractInputFormatTypes() is not implemented yet.

**Comment by StephanEwen** [comment]
I will take a quick stab at this.

**Comment by twalthr** [comment]
I also can do it since I need it later this afternoon for the Hadoop Input Format.

**Comment by StephanEwen** [comment]
Sounds good.

**Comment by StephanEwen** [comment]
Fixed in #776
