### ISSUE TITLE
Add tests for the type comparators

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#772]
We need tests for the comparators (all subclasses of `TypeComparator`)
- Basic types
- Value types
- CopyableValue types
- Generic types

**Comment by StephanEwen** [comment]
- BasicType is done
- Tuple Type is done

Pending:
- Value / Generic (should be equivalent)

**Comment by fhueske** [comment]
Added generic comparator tests with 1b6a3acfb7d1991ad8e76425e31792d38403b136 and value comparator tests with 4cdc6335910fcf0612585e8d787b7980641285c0.
