### ISSUE TITLE
Move the group order from the Grouping

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#783]
Currently, the `Grouping` class (used for grouped reduce, reduceGroup, aggregate, coGroup) has the option to specify a group order. Half of the operators need to throw an exception when encountering it because they do not support group order.

I would suggest to move this either to the operators that support group order (`reduceGroup`, `coGroup`) or to a subclass of `Grouping` that is created for these operators.

**Comment by StephanEwen** [comment]
I would vote to make a subclass of `Grouping`.

**Comment by fhueske** [comment]
:+1:

**Comment by markus-h** [comment]
Good idea! Just a small remark: I think coGroup is at the moment not implemented through Grouping but as a first class function at DataSet. So reduceGroup is currently the only operator accessed through Grouping that can be sorted.

**Comment by fhueske** [comment]
Very good point. We should also support sorted groups for CoGroup. 
I would make this a separate issue though.

**Comment by fhueske** [comment]
Fixed with #790
