### ISSUE TITLE
Checkstyle marks imports as unused when only referred to in javadocs

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#786]
You can import a class to use its short name in javadocs links. Checkstyle fails with an unused import error then.

**Comment by rmetzger** [comment]
This pull request contains a fix for that: https://github.com/stratosphere/stratosphere/pull/779/files#diff-15

**Comment by StephanEwen** [comment]
Ah, nice! Will merge as soon as the patch to divide reduce and groupReduce is done.

**Comment by StephanEwen** [comment]
Solved in 340ebde779d5028dfdf38b2bed40566d57985335
