### ISSUE TITLE
Add JAR packaging for new Java API examples 

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#810]
Currently, all JAR examples that are packaged are from the old Record API

**Comment by fhueske** [comment]
Will take care of this.

**Comment by rmetzger** [comment]
It seems that, due to commit c41569eb01ac9ab83e17554a50ccdc7e4ac49327 (I guess), the example jar files are empty.

**Comment by fhueske** [comment]
Fixed in 465a6a4df6416b3010f8a11c3113b2d06c2e9d44
