### ISSUE TITLE
Fix version warnign for Maven JAR plugin in root pom.xml

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#811]
I am getting a lot of warnings that the Maven JAR plugin added to fix the "version in Uberjar" problem has no version.

**Comment by rmetzger** [comment]
Yes, I forgot to add the version to the jar plugin. I'll fix this with my
next pull request.

On Wed, May 14, 2014 at 6:10 PM, Stephan Ewen notifications@github.comwrote:

> I am getting a lot of warnings that the Maven JAR plugin added to fix the
> "version in Uberjar" problem has no version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stratosphere/stratosphere/issues/811
> .

## 

Robert Metzger, Kontakt: metzgerr@web.de, Mobil: 0171/7424461

**Comment by StephanEwen** [comment]
Cool, thanks

**Comment by fhueske** [comment]
Fixed with PR #797
