### ISSUE TITLE
Web job submission client errors when trying to run KMeans

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#830]
I tried the run the quickstart KMeans example with the new example program and followed the instructions on the [website](http://stratosphere.eu/quickstart/example.html).

I had to adapt the Python script and the data generation command, but when I tried to submit the job on the webclient, I got this error message:

```
Unknown local strategy 'SORTED_PARTIAL_REDUCE' in JSON generator.
```

**Comment by StephanEwen** [comment]
Fixed as part of 2bb3e982a71420caf81fbc9b2459a21ae690f446
