### ISSUE TITLE
Add DOP option to CLI and web submission client

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#831]
We want to go away from specifying the DOP within the program itself but rather doing this on an execution environment / client level.
Therefore, the example programs have been implemented without specifying a DOP.

However, I am not aware of the possibility to set the DOP of an individual program (there might be config parameters for that). Please let me know, if this feature exists.

I think we should add options for setting the DOP to the CLI client and also to the web submission client. I think this is a rather critical thing and should block the 0.5 release.

**Comment by StephanEwen** [comment]
I have a fix here: https://github.com/StephanEwen/stratosphere/commit/0fdb48648c03788c78ed64a603211b2ffdd41947

Wating for Travis to complete and will then file a pull request.

**Comment by fhueske** [comment]
We need to update the documentation of the [CLI](http://stratosphere.eu/docs/0.4/program_execution/cli_client.html) and [Webclient](http://stratosphere.eu/docs/0.4/program_execution/web_interface.html) on the website accordingly.

**Comment by StephanEwen** [comment]
Fixed in 7e4888dfe6ded643c3a21d7e64d5eda47ebf4526 and f5e3a861ac1228335ee1b5a9a4527fffdf6b3b2c.

Website docu updates are on the way.

**Comment by fhueske** [comment]
Website documentation has been updated.
Thanks!
