### ISSUE TITLE
Remove all System.exit() calls from example programs

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#843]
This kills the CLI client and the WebClient. The firstone ungracefully, for the second one, the WebServer simply goes down. In general, there should never by System.exit() calls anywhere in the code, except for the main executables: JobManager, TaskManager, YarnAppMaster, CliFrontend, WebFrontend.

This is a release blocker in my opinion.

We should think about security managers that prevent calling this method from example programs.

**Comment by fhueske** [comment]
eh, shame on me.

Will do that.

**Comment by fhueske** [comment]
Has been fixed in 8dc3ac4f1cb6a4f53b2fd0be0d7ff35a20cb574d and 7fa8e25c9c6d6be1abb12a376ac9a713fbefe367
