### ISSUE TITLE
Parallelism parameter is not evaluated by CLI client in INFO action

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#847]
The parallelism parameter (-p) is not evaluated if used in the info action together with the execution plan parameter (-e).

**Comment by StephanEwen** [comment]
This bug is not CLI Frontend related. The environment parallelism is not evaluated at all for Optimizer Plan command in the new Java API. I have a fix for that...

**Comment by StephanEwen** [comment]
Fixed in e5f617d1557414456db1f00e7d5adeaded749870
