### ISSUE TITLE
Add Tab in Webfrontend that lists all configuration values

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#849]
Hadoop also allows to inspect the configuration values from the webinterface.
I think it is not too much work and a very helpful feature.

**Comment by rmetzger** [comment]
Showing some details about the connected TaskManagers would also be great.

**Comment by uce** [comment]
+1

**Comment by StephanEwen** [comment]
+1

**Comment by MoeweX** [comment]
Done, waiting for merge #919 
What informations from the TaskManagers do you want? I can try to include it, too.

**Comment by rmetzger** [comment]
As part of our move to the Apache Software Foundation, we are now using their JIRA for issue tracking.
I also imported this issue to JIRA: https://issues.apache.org/jira/browse/FLINK-849
Lets continue the discussion there.
