### ISSUE TITLE
Dokumentation improvement

### ISSUE THREAD

**Issue by oresti** [stratosphere/stratosphere#851]
Create a short tutorial for intelliJ users in Readme.md file.
For example: how to run the WordCount example (locally) from the IDE in less then 5 minutes after pulling the latest stratosphere git repo.
=> Encourage the usage of IDE's and local-execution for newbies.

My Idea:
1) File->Import Project->From External Model->Maven->Check all 6 checkboxes->NextNextNext ...
2) Collapse stratosphere-java-examples->eu.stratosphere.example.java.wordcount.WordCount.java -> RightClick on the file -> Click "Run WordCount.main() -> Enjoy
3) Next: show where to put new projects and data.txt files
(BTW: Great job for making the examples run on a mouse click with default params ! )

Also:
To the readers of [Quickstart](http://stratosphere.eu/quickstart/setup.html#example):
Ok its great to run the WordCount.jar from the CLI but what next? How can the user analyze/modify WordCount.java or maybe write a new CustomJob.java project?
A side-note there would be great.

**Comment by oresti** [comment]
I just saw that you do have a doku in the Quickstart for that in [here](http://stratosphere.eu/quickstart/java.html)

**Comment by rmetzger** [comment]
Hey,
thanks for creating the issue. 
Since you're obviously tried out Stratosphere recently, do you have any further suggestions on how to improve the overall experience, especially for new users?
I don't know how we can make it more obvious that it is really easy to run Stratosphere from an IDE.

**Comment by oresti** [comment]
Hi,
for the quick-start introduction I do not have any more suggestions and I am really amazed about how easy it is to run (and work on) Stratosphere.

Maybe a wikipedia article as an additional reference point?
Also: try to point out the obvious fact that "Stratosphere is much easier/better that MR" as much as possible :)

Keep up the good work!

**Comment by rmetzger** [comment]
Cool. Thanks for the kind words.

Somebody has actually drafted a Wikipedia article. I'm going to push that
again once we have the new name in the Apache Incubator.

Sent from my iPhone

On 23.05.2014, at 18:16, oresti notifications@github.com wrote:

Hi,
for the quick-start introduction I do not have any more suggestions and I
am really amazed about how easy it is to run (and work on) Stratosphere.

Maybe a wikipedia article as an additional reference point?
Also: try to point out the obvious fact that "Stratosphere is much
easier/better that MR" as much as possible :)

Keep up the good work!

—
Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/issues/851#issuecomment-44031143
.
