### ISSUE TITLE
DistributedCache doesn't preserve executable flag

### ISSUE THREAD

**Issue by zentol** [stratosphere/stratosphere#852]
all files distributed with the DistributedCache are marked as not executable, which causes a problem for the python interface. (I currently try to package all scripts/dependencies into binaries and distribute those, since we cant distribute directories).

a fix for this would to to modify Filecache.CopyProcess.call() to include

```
new File(tmp.toString()).setExecutable(true);
```

but this is more of a shotgun approach, since now all files are executable. Is this an acceptable solution?

**Comment by uce** [comment]
I'm not familiar with the DistributedCache, but `File` also offers the `boolean canExecute()`. So it should be possible to encode this for each executable file in an internal DistributedCache data structure and then just call it on each of the executable files?

**Comment by zentol** [comment]
generally yes, but using `File` wont work (completely), since the distributedCache (afaik) also accepts hdfs:// files (generally all files that are supported by our `FileSystem`.)

**Comment by fhueske** [comment]
I wouldn't make all files executable. 
What about preserving the execution flag for local files and also adding an optional parameter when registering files in the DC?

**Comment by zentol** [comment]
ok, using `File` does in fact work.

I'm also currently extending the cache to allow the distribution of directories.

While working on that i noticed (or rather realised) that the DC only allows the distribution of files that already exist in a distributed FS. (which actually kind of makes the original issue irrelevant)
I would like to extend it so that you can pass a local file and have it loaded into the DFS.
