### ISSUE TITLE
Web interface: task number not readable with low tasks counts

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#853]
The number of tasks per execution stage is not readable with low task counts, i.e. if you have stragglers as in the screenshot below, it's hard to see if there is any progress at all.

![screen shot 2014-05-24 at 18 06 10](https://cloud.githubusercontent.com/assets/1756620/3074992/57038d24-e35d-11e3-8294-793ceba5322f.png)

**Comment by MoeweX** [comment]
Tobias ist dabei das zu ändern zusammen mit einer größeren Änderung (#766).
