### ISSUE TITLE
Web interface: show runtime of subtasks

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#854]
When I click on the detailed view of a task, I see all subtasks as in the screenshot below. I would also like to show the runtime per stage, e.g. I want to know how long the yellow subtask was in running.

![screen shot 2014-05-24 at 18 09 36](https://cloud.githubusercontent.com/assets/1756620/3074999/d0ebe1d6-e35d-11e3-9f18-26ac5ce96999.png)

**Comment by fhueske** [comment]
:+1:
