### ISSUE TITLE
Web interface: flow vs stack layout

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#855]
I don't understand the real difference between the flow and stack layout in the web interface. Let's stick with one of the two.

![screen shot 2014-05-24 at 18 11 37](https://cloud.githubusercontent.com/assets/1756620/3075006/3336865c-e35e-11e3-98ca-ea1feeaf7415.png)
![screen shot 2014-05-24 at 18 11 48](https://cloud.githubusercontent.com/assets/1756620/3075007/333c1a04-e35e-11e3-8be8-6c8c0185b809.png)

**Comment by MoeweX** [comment]
Hi,

both layouts are created by @markus-h . What do you think?

**Comment by fhueske** [comment]
Another issue with these visualization is that the Finished time of a tasks is shown, not the Finishing time. 

A task switches from Running to Finishing state when it has processed all its input. It goes from Finishing to Finished once all its output channels are closed by its successor tasks. That means the Finished time depends on the successor task and not on the task itself.

I propose to display only the time in which the task is actually running (from state switch to Running to switch to Finishing).

**Comment by markus-h** [comment]
The difference of the two styles is just a matter of layout and what people like more. It is no problem to remove one of them but I also don't see a real disadvantage when we keep both. Personally I like the stack layout more.

@fhueske After reading your description I agree that finishing would be more sensible to finished
