### ISSUE TITLE
Simulate remote network transfers for debugging and testing

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#86]
There are at least two cases of bugs which were only visible when running Stratosphere on a distributed system. (The deadlock bugs uce fixed and a null pointer exception reported by André).
We should cover the distributed operation of our system in testcases, since this is our primary use-case.

It seems that nephele does only use network transfers if task managers have different ip  adresses or ports. I think it is important to have test cases that test the remote network 

The LocalExecutor uses a special mode that has only one TaskManager, running in a thread.

The TestBase and TestBase2 of pact-tests has another implementation of a local execution mode. It also had a variable called "num task managers", but it was not used anywhere.

I started to write some code, but there is still some work to do:
https://github.com/rmetzger/ozone/tree/gith_local_distributed_executor
My implementation starts the JobManager as a regular "Cluster" JobManager. I'm already able to start multiple TaskManagers, that connect successfully to the JM.
The job submission is not working until now.

**Comment by uce** [comment]
What's the status on this? What needs to be done? I think that this is a really nice (and long overdue) addition to the LocalExecutor.

What about adding an extra argument to the execute methods of `LocalExecutor` instead of having a new `DistributedLocalExecutor`?

**Comment by rmetzger** [comment]
Okay, I created a Pull Request. I'll prepare a second pull request for the test-integration and a combined LocalExecutor
