### ISSUE TITLE
Code from documentation does not compile [0.5-rc2]

### ISSUE THREAD

**Issue by knub** [stratosphere/stratosphere#889]
http://stratosphere.eu/docs/0.5/programming_guides/scala.html#data-sinks

``` scala
val out: DataSet[(String, Int)]
val sink = out.write("file:///some/file", CsvOutputFormat())

val plan = new ScalaPlan(Seq(sink)) // <-- compile error
```

ScalaPlan expects a `GenericDataSinkBase`, however `out.write` returns a `ScalaSink` which inherits from `AnyRef`.

**Comment by knub** [comment]
Argh, was using Plan(Seq(sink)) instead of ScalaPlan(Seq(sink)). I'm sorry!

**Comment by StephanEwen** [comment]
That's fine...

Let us know if you find inconsistencies in the Documentation.
