### ISSUE TITLE
Clean up distribution default config

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#898]
Just a small remark: I vote to simplify the default config we ship, because it gives the impression that you actually have to configure a lot of stuff. See [https://github.com/stratosphere/stratosphere/blob/master/stratosphere-dist/src/main/stratosphere-bin/conf/stratosphere-conf.yaml](https://github.com/stratosphere/stratosphere/blob/master/stratosphere-dist/src/main/stratosphere-bin/conf/stratosphere-conf.yaml).

**Comment by StephanEwen** [comment]
I agree. How about the following:

#### Active entries (not commented out)
- jobmanager.rpc.address: localhost
- jobmanager.rpc.port: 6123
- jobmanager.heap.mb: 256
- taskmanager.heap.mb: 512
- parallelization.default: 1

#### Suggested entries (commented out)
- taskmanager.tmp.dirs: /tmp
- fs.hdfs.hadoopconf: /path/to/hadoop/conf/
- taskmanager.network.numberOfBuffers: 2048 (This one will go in the next rounds when we reworked the memory management)

**Comment by StephanEwen** [comment]
We could add to the suggested entries
- jobmanager.web.port: 8081
- webclient.port: 8080 (may go as well when we unify the web frontends)
