### ISSUE TITLE
Add flag for visualization of pact plan with the nephele SWT visualization

### ISSUE THREAD

**Issue by mhuelfen** [stratosphere/stratosphere#9]
The visualization of pact iterations contains unwanted items like "Fake Tail" and "Bulk-Iteration Sync" 
to visualize only the wanted parts, a flag for visualization should be added accessible from to the Classes:
eu.stratosphere.nephele.managementgraph.GroupVertex
eu.stratosphere.nephele.managementgraph.ManagementGroupVertex

**Comment by sscdotopen** [comment]
We decided against adding such a flag, as it would cause too much code complexity to the hierarchy of vertices in Nephele. We see no other need for hiding tasks then in the iterations setting.
