### ISSUE TITLE
Building for Hadoop v1 and v2 (yarn)

### ISSUE THREAD

**Issue by andrehacker** [stratosphere/stratosphere#95]
### How to build

We now use the profile activation via properties (-D), and no longer via profile (-P)
#### Build hadoop v1 (default)

Build the default (currently hadoop 1.2.1)
`mvn clean package`

Build for a specific hadoop v1 version
`mvn -Dhadoop-one.version=1.1.2 clean package`
#### Build hadoop v2 (yarn)

Build the yarn using the default version defined in the pom
`mvn -Dhadoop.profile=2 clean package`

Build for a specific hadoop v1 version
`mvn -Dhadoop.profile=2 -Dhadoop-two.version=2.1.0-beta clean package`
### Why we need the script to generate poms

**Problem 1**: Let's assume you want to use stratosphere with yarn. If you run `mvn -Dhadoop.profile=2 install` the jars and the pom are copied to your local repo. If you now use this dependency in eclipse, eclipse will read the pom, add the dependency for hadoop v1 (hadoop-core) which is not what you want.
**Problem 2**: If you have two projects using stratosphere, one based on yarn, the other based on hadoop_v1, you cannot work with both of them, because there is only a single version in your local repository that is either for v1 or yarn.
**Problem 3**: If we want to publish stratosphere-0.2-ozone to the public maven repo, we can just deliver a single pom that either defaults to hadoop1 or to hadoop2.

**Solution**: We create two maven-versions: 0.2-ozone-hadoop1 and 0.2-ozone-hadoop2
This requires to have different poms, and for this we created a script. **The script is only needed if you have one of the above problems**. If building a stratosphere distribution with the correct dependencies then you can use the profiles. **You need the script only if you want to publish into a local or remote repositry**
### How the script works

The script can be used for hadoop1 and hadoop2. If you use it for hadoop2, it will create a modified copy of all poms with the name pom.hadoop2.xml. In these poms, the version was changed to 0.2-ozone-hadoop2 and the default profile is hadoop2. Read the comments in the script to learn more.
To use the specialized pom: `mvn -f pom.hadoop2.xml ...`
### Why we use properties for activation

There are two major ways to switch between profiles: Properties (-Dproperty=value) and explicit profile specification (-Pprofile). Using the -P option implies the usage of activeByDefault. The activeByDefault profile will be deactivated as soon as any other profile becomes active. This is however not a good long-term solution, because if we want to use profiles for other things, the default hadoop profile would be deactivated as well. This is why we use properties for activation: The default profile is activated, if the property hadoop.profile is not set, and the hadoop2 profile is activated if the hadoop.profile property is set to 2.
To explain all the details of profile activation is a bit complex, you can read it here: http://maven.apache.org/guides/introduction/introduction-to-profiles.html
### How do others do it?

Our solution is inspired by hbase. Actually, the script was copied from them.
As you can see in the maven repository they use different versions for hadoop1 and hadoop2: http://mvnrepository.com/artifact/org.apache.hbase/hbase
Their discussion can be found here: https://issues.apache.org/jira/browse/HBASE-8224

**Comment by rmetzger** [comment]
This bug produces the following error message for me, when using pact-client.sh to submit a job:

```
ERROR: The job was not successfully submitted to the nephele job manager: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot compute input splits for 'Invoices file': org.apache.hadoop.ipc.RemoteException: Server IPC version 7 cannot communicate with client version 4
```

**Comment by rmetzger** [comment]
Okay, I created a little sample project that demonstrate the problem: https://github.com/rmetzger/maven-bug

You mentioned the following bug:

> If you use the hadoop_yarn profile, the lib directory will not contain the correct hadoop-yarn jars, but instead the old hadoop-core-1.2.1.jar

My sample project does not have this behavior. I guess it's because I did not not use the `dependencyManagement` tag in the profiles. If I do so, it does not find the hadoop package.

Sadly, I can not reproduce the behavior. Can you help me?

**Comment by rmetzger** [comment]
i asked at the m2e mailing list yesterday, how the profile activation works with Eclipse. It seems that it is very cumbersome to activate it. But somebody recommended the JBoss Eclipse tools that contain a tool to switch maven profiles. 
This is the update site for kepler: http://download.jboss.org/jbosstools/updates/stable/kepler/
The plugin is called `Maven Profiles Management   1.5.0.Final-v20130719-2050-B70  org.jboss.tools.maven.profiles.feature.feature.group`
More information is here: http://www.jboss.org/tools/download/installation/update_4_1.html#fromsite
This is the answer on the mailing list. http://dev.eclipse.org/mhonarc/lists/m2e-users/msg04366.html

**Comment by uce** [comment]
@rmetzger Did you try it? Is it working? If it is too cumbersome for you even, I won't bother trying. :palm_tree:

**Comment by rmetzger** [comment]
If you want profile support with m2e, you need to open the projects according to the profiles.
You have to set to profile for every sub-project.

The JBoss Plugin seems to work! At least the jars in the classpath seem to be correct. Even though the Dependency Hierachy in Eclipse looks wrong (it ignores the profiles).
I think we need to create a "Stratosphere Eclipse Plugin" that pulls all the plugins required to work with Stratosphere. We require 3 eclipse plugins for Scala and one for yarn-developers.
BUT: There is also another solution for users that  want to develop jobs: The improved generate-pom-scripts (https://github.com/stratosphere/stratosphere/pull/156) allow to replace the existing pom with the yarn build as default.

I'm going to document this properly in the Wiki.
